"""
build_business_ps2.py  (part 2 of the library: domains E-I)
==========================================================
Lapse, surrender, retention, claims/risk and profitability Problem Statements.
Shares the builder helpers defined in `build_business_ps`.
"""

from __future__ import annotations

import business_intents as bi
from build_business_ps import (
    ps, step, PERF_METRICS, RISK_METRICS, VALUE_METRICS,
    P_TABLES, ALL_TABLES, REL_CORE, REL_CLAIM, REL_SURR, REL_RET,
)

LAPSE_DIMS = ["product", "channel", "zone", "payment_mode", "income_band",
              "age_band", "sa_band", "smoker", "premium_to_income_band",
              "premium_payment_type", "policy_age_band", "medical_underwriting"]


# =====================================================================
# E. LAPSE / PERSISTENCY ANALYSIS
# =====================================================================

def domain_lapse():
    ps("What factors across the whole book are associated with policy lapse?",
       bi.LAPSE_ANALYSIS,
       "Rank every available dimension by how strongly it separates lapse rates.",
       bi.TIER_MULTI_STEP,
       ["What factors are associated with policy lapse?",
        "What drives lapse in our portfolio?",
        "What is causing policies to lapse?",
        "Which factors explain lapse?",
        "What should we look at to understand lapse?"],
       [step("s1", "Portfolio lapse baseline", "portfolio_overview", {},
             "The book lapse rate every segment is measured against."),
        step("s2", "Strongest associations across all dimensions", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {}, "min_n": 25, "top_k": 10},
             "Scan every candidate dimension and rank by deviation."),
        step("s3", "Lapse by payment mode", "compare_to_baseline",
             {"dimension": "payment_mode", "metric": "lapse_rate"},
             "Billing frequency is the most operationally actionable factor."),
        step("s4", "Lapse by product", "compare_to_baseline",
             {"dimension": "product", "metric": "lapse_rate"},
             "Product design effect."),
        step("s5", "Lapse by affordability strain", "compare_to_baseline",
             {"dimension": "premium_to_income_band", "metric": "lapse_rate"},
             "Affordability effect.")],
       ALL_TABLES,
       ["policy_status", "payment_mode", "product_name", "sales_channel", "zone",
        "annual_income", "annual_premium", "age", "is_smoker"],
       ["lapse_rate", "persistency_rate"],
       ["lapse", "diagnostic", "risk"],
       "driver_analysis", "driver_analysis", REL_CORE,
       caveat="Every figure here is an observed association between a segment and "
              "its lapse rate. The dataset contains no lapse-reason field, so none "
              "of these can be stated as a cause.")

    ps("Which products have the highest lapse risk?",
       bi.LAPSE_ANALYSIS, "Rank products on lapse with reliability flags.",
       bi.TIER_ANALYTICAL,
       ["Which products have the highest lapse risk?",
        "Which product lapses most?",
        "Rank products by lapse rate.",
        "Where is lapse worst by product?"],
       [step("s1", "Lapse by product vs baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "lapse_rate"},
             "Rate, gap and sample size per product."),
        step("s2", "Volume context", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "policy_share", "sum_assured_share",
                          "persistency_rate"],
              "sort_by": "policy_share"},
             "How much of the book each product represents.")],
       P_TABLES, ["product_name", "policy_status"], ["lapse_rate", "persistency_rate"],
       ["lapse", "product", "risk"], "leaderboard", "leaderboard", REL_CORE)

    ps("Which customer segments have the highest lapse risk?",
       bi.LAPSE_ANALYSIS, "Rank customer segments on lapse.",
       bi.TIER_MULTI_STEP,
       ["Which customer segments have the highest lapse risk?",
        "Which customers lapse most?",
        "Which demographic segments lapse most?",
        "Who lapses the most in our book?"],
       [step("s1", "Lapse by income band", "compare_to_baseline",
             {"dimension": "income_band", "metric": "lapse_rate"}, "Income effect."),
        step("s2", "Lapse by age band", "compare_to_baseline",
             {"dimension": "age_band", "metric": "lapse_rate"}, "Life-stage effect."),
        step("s3", "Lapse by affordability strain", "compare_to_baseline",
             {"dimension": "premium_to_income_band", "metric": "lapse_rate"},
             "Affordability effect."),
        step("s4", "Ranked customer-side associations", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {},
              "dimensions": ["income_band", "age_band", "sa_band", "smoker",
                             "premium_to_income_band", "gender", "marital_status"],
              "min_n": 25, "top_k": 8},
             "Rank only the customer dimensions.")],
       ["policies", "customers"], ["annual_income", "age", "policy_status", "is_smoker"],
       ["lapse_rate"], ["lapse", "customer", "risk"],
       "risk_segmentation", "risk_segmentation", REL_CORE,
       caveat="Associations only - the dataset has no lapse-reason or behavioural data.")

    ps("Which sales channels have the highest lapse risk?",
       bi.LAPSE_ANALYSIS, "Rank channels on lapse with volume context.",
       bi.TIER_ANALYTICAL,
       ["Which sales channels have the highest lapse risk?",
        "Which channel lapses most?",
        "Rank channels by lapse rate.",
        "Which distribution route has the worst persistency?"],
       [step("s1", "Lapse by channel vs baseline", "compare_to_baseline",
             {"dimension": "channel", "metric": "lapse_rate"}, "Rate and gap per channel."),
        step("s2", "Volume and value context", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["policy_count", "policy_share", "avg_annual_premium",
                          "persistency_rate"],
              "sort_by": "policy_share"},
             "How much is at stake in each channel.")],
       P_TABLES, ["sales_channel", "policy_status"], ["lapse_rate", "persistency_rate"],
       ["lapse", "channel", "risk"], "leaderboard", "leaderboard", REL_CORE)

    ps("Which payment modes are associated with higher lapse?",
       bi.LAPSE_ANALYSIS,
       "Billing frequency is one of the few directly changeable levers in this dataset.",
       bi.TIER_MULTI_STEP,
       ["Which payment modes are associated with higher lapse?",
        "Does monthly payment lapse more than annual?",
        "How does payment frequency affect persistency?",
        "Compare payment modes on persistency."],
       [step("s1", "Lapse by payment mode vs baseline", "compare_to_baseline",
             {"dimension": "payment_mode", "metric": "lapse_rate"},
             "Rate and gap per billing frequency."),
        step("s2", "Full payment-mode scorecard", "multi_metric_table",
             {"dimension": "payment_mode",
              "metrics": ["policy_count", "policy_share", "avg_annual_premium",
                          "avg_customer_income", "avg_premium_to_income",
                          "lapse_rate", "surrender_rate", "persistency_rate"],
              "sort_by": "lapse_rate"},
             "Context on who chooses each mode."),
        step("s3", "Payment mode x product grid", "crosstab_metric",
             {"dim_a": "payment_mode", "dim_b": "product", "metric": "lapse_rate", "min_n": 20},
             "Whether the mode effect holds within products.")],
       P_TABLES, ["payment_mode", "policy_status", "annual_premium", "annual_income"],
       ["lapse_rate", "persistency_rate"],
       ["payment", "lapse", "comparison"],
       "comparison", "comparison", REL_CORE,
       caveat="Customers who choose monthly billing may differ systematically from "
              "those who pay annually; the gap is not evidence that changing the "
              "billing mode would change the outcome.")

    ps("Is lapse risk concentrated in particular product, channel and segment "
       "combinations?",
       bi.LAPSE_ANALYSIS,
       "Move from one-dimensional lapse rates to the specific cells that hurt.",
       bi.TIER_MULTI_STEP,
       ["Are lapse risks concentrated in particular products, channels and customer segments?",
        "Where exactly does lapse concentrate?",
        "Which combinations lapse most?",
        "Show me the worst lapse pockets."],
       [step("s1", "Product x channel lapse grid", "crosstab_metric",
             {"dim_a": "product", "dim_b": "channel", "metric": "lapse_rate", "min_n": 15},
             "Worst product-channel cells."),
        step("s2", "Product x payment mode lapse grid", "crosstab_metric",
             {"dim_a": "product", "dim_b": "payment_mode", "metric": "lapse_rate", "min_n": 15},
             "Worst product-billing cells."),
        step("s3", "Zone x channel lapse grid", "crosstab_metric",
             {"dim_a": "zone", "dim_b": "channel", "metric": "lapse_rate", "min_n": 15},
             "Worst geographic-distribution cells."),
        step("s4", "Portfolio lapse baseline", "portfolio_overview", {},
             "The number each cell is judged against.")],
       P_TABLES, ["product_name", "sales_channel", "zone", "payment_mode", "policy_status"],
       ["lapse_rate"], ["lapse", "concentration", "risk"],
       "grid", "grid", REL_CORE,
       caveat="Two-way cells are small. Cells under the sample threshold are dropped, "
              "and the survivors should be treated as investigation leads.")

    ps("What should management investigate to improve persistency?",
       bi.LAPSE_ANALYSIS,
       "Convert lapse evidence into a short, prioritised investigation list.",
       bi.TIER_MULTI_STEP,
       ["What should management investigate to improve persistency?",
        "How do we improve persistency?",
        "What can we do about lapse?",
        "Give me a persistency action plan.",
        "Where should we start on lapse?"],
       [step("s1", "Portfolio lapse baseline", "portfolio_overview", {},
             "Size the problem before prioritising it."),
        step("s2", "Strongest associations across all dimensions", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {}, "min_n": 25, "top_k": 10},
             "Rank every candidate factor by deviation."),
        step("s3", "Product priority weighted by materiality", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "lapse_rate", "weight": 0.5, "direction": "high"},
                             {"metric": "policy_share", "weight": 0.25, "direction": "high"},
                             {"metric": "premium_share", "weight": 0.25, "direction": "high"}]},
             "Rank products by how much lapse actually costs."),
        step("s4", "Existing retention effectiveness", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False},
             "Whether the current retention machine already works.")],
       ALL_TABLES, ["policy_status", "product_name", "payment_mode", "retention_status"],
       ["lapse_rate", "policy_share", "retention_success_rate"],
       ["lapse", "attention", "recommendation", "retention"],
       "action_plan", "action_plan", REL_RET)

    ps("Which zones have the highest lapse risk?",
       bi.LAPSE_ANALYSIS, "Geographic view of persistency.",
       bi.TIER_ANALYTICAL,
       ["Which zones have the highest lapse risk?",
        "Which region lapses most?",
        "Rank zones by lapse rate.",
        "Where geographically is persistency worst?"],
       [step("s1", "Lapse by zone vs baseline", "compare_to_baseline",
             {"dimension": "zone", "metric": "lapse_rate"}, "Rate and gap per zone."),
        step("s2", "Zone scorecard", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["policy_count", "policy_share", "persistency_rate",
                          "surrender_rate", "avg_sum_assured"],
              "sort_by": "persistency_rate"},
             "Fuller picture per zone."),
        step("s3", "Branch-level detail", "compare_to_baseline",
             {"dimension": "branch", "metric": "lapse_rate", "min_n": 25},
             "Whether the zone effect is really a branch effect.")],
       P_TABLES, ["zone", "branch_name", "policy_status"], ["lapse_rate", "persistency_rate"],
       ["lapse", "zone", "risk"], "leaderboard", "leaderboard", REL_CORE)

    ps("How does persistency vary with policy vintage and remaining term?",
       bi.LAPSE_ANALYSIS,
       "Understand when in a policy's life lapse actually happens.",
       bi.TIER_ANALYTICAL,
       ["When do policies lapse?",
        "How does lapse vary with policy age?",
        "Do older policies lapse more?",
        "How does lapse vary by policy term?"],
       [step("s1", "Lapse by policy vintage band", "compare_to_baseline",
             {"dimension": "policy_age_band", "metric": "lapse_rate"},
             "Lapse by how long the policy has been on the books."),
        step("s2", "Lapse by policy term band", "compare_to_baseline",
             {"dimension": "tenure_band", "metric": "lapse_rate"},
             "Lapse by contract length."),
        step("s3", "Premium realisation by vintage", "multi_metric_table",
             {"dimension": "policy_age_band",
              "metrics": ["policy_count", "lapse_rate", "persistency_rate",
                          "avg_annual_premium"],
              "sort_by": "policy_age_band", "ascending": True},
             "How much premium each vintage still contributes.")],
       P_TABLES, ["issuance_date", "policy_tenure_years", "policy_status"],
       ["lapse_rate", "persistency_rate"],
       ["lapse", "portfolio"], "trend", "leaderboard", REL_CORE,
       caveat="Older policies have had longer to lapse, so vintage bands carry "
              "unequal exposure; this is a stock view, not a hazard curve.")

    ps("Does medical underwriting or rider attachment relate to persistency?",
       bi.LAPSE_ANALYSIS,
       "Test whether policies with more engagement at sale stick better.",
       bi.TIER_ANALYTICAL,
       ["Does medical underwriting affect lapse?",
        "Do policies with riders lapse less?",
        "Does underwriting intensity relate to persistency?",
        "Are riders associated with better retention?"],
       [step("s1", "Lapse by medical underwriting flag", "compare_to_baseline",
             {"dimension": "medical_underwriting", "metric": "lapse_rate"},
             "Underwritten versus not."),
        step("s2", "Lapse by rider attachment", "compare_to_baseline",
             {"dimension": "rider", "metric": "lapse_rate"},
             "With rider versus without."),
        step("s3", "Full contrast", "multi_metric_table",
             {"dimension": "rider",
              "metrics": ["policy_count", "avg_sum_assured", "avg_annual_premium",
                          "lapse_rate", "persistency_rate", "claim_rate"],
              "sort_by": "lapse_rate"},
             "Whether rider policies differ in other ways too.")],
       P_TABLES, ["medical_underwriting_flag", "rider_count", "policy_status"],
       ["lapse_rate", "rider_attachment_rate"],
       ["lapse", "underwriting"], "comparison", "comparison", REL_CORE)

    ps("Why does a specific product have a high lapse rate?",
       bi.LAPSE_ANALYSIS,
       "Decompose one product's lapse into the segments that generate it.",
       bi.TIER_MULTI_STEP,
       ["Why does Whole Life have a high lapse rate?",
        "Why is lapse high in Annuity?",
        "What is driving lapse in Term Life?",
        "Explain the lapse rate on Endowment."],
       [step("s1", "Product lapse vs every other product", "compare_to_baseline",
             {"dimension": "product", "metric": "lapse_rate"},
             "Confirm the product is genuinely worse before explaining it."),
        step("s2", "Lapse by channel inside the product", "multi_metric_table",
             {"dimension": "channel", "metrics": ["policy_count", "lapse_rate"],
              "filters": {"product": "$product"}, "sort_by": "lapse_rate", "min_n": 8},
             "Which distribution route generates the lapses."),
        step("s3", "Lapse by payment mode inside the product", "multi_metric_table",
             {"dimension": "payment_mode", "metrics": ["policy_count", "lapse_rate"],
              "filters": {"product": "$product"}, "sort_by": "lapse_rate", "min_n": 8},
             "Whether billing frequency is involved."),
        step("s4", "Strongest segment deviations inside the product", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {"product": "$product"},
              "min_n": 10, "top_k": 8},
             "Rank every remaining dimension by deviation from the product average."),
        step("s5", "Product characteristics vs portfolio", "segment_profile",
             {"filters": {"product": "$product"}},
             "Whether the product's customers or economics differ structurally.")],
       ALL_TABLES,
       ["product_name", "sales_channel", "payment_mode", "policy_status",
        "annual_income", "annual_premium", "sum_assured"],
       ["lapse_rate", "persistency_rate", "avg_premium_to_income"],
       ["lapse", "product", "diagnostic"],
       "diagnostic", "diagnostic", REL_CORE,
       parameters={"product": {"dimension": "product", "default": "Whole Life",
                               "description": "Product to diagnose"}},
       caveat="This decomposition shows where the lapses sit, which is association, "
              "not proof of cause. Segment sizes inside one product are small.")


# =====================================================================
# F. SURRENDER ANALYSIS
# =====================================================================

def domain_surrender():
    ps("What is driving policy surrender across the book?",
       bi.SURRENDER_ANALYSIS,
       "Explain surrender using the stated reasons plus the segments where it clusters.",
       bi.TIER_MULTI_STEP,
       ["What is driving policy surrender?",
        "Why do customers surrender?",
        "What causes surrenders?",
        "What is behind our surrender numbers?"],
       [step("s1", "Stated surrender reasons", "multi_metric_table",
             {"dimension": "surrender_reason",
              "metrics": ["policy_count", "avg_sum_assured", "avg_annual_premium"],
              "sort_by": "policy_count", "min_n": 1},
             "The reason field recorded at surrender."),
        step("s2", "Surrender by product vs baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "surrender_rate"},
             "Which products surrender above the eligible-product average."),
        step("s3", "Strongest segment deviations", "driver_scan",
             {"metric": "surrender_rate", "focus_filters": {}, "min_n": 40, "top_k": 8},
             "Rank every dimension by deviation in surrender rate."),
        step("s4", "Surrendered-policy profile", "segment_profile",
             {"filters": {"policy_status": "Surrendered"}},
             "How surrendered policies differ from the book.")],
       ALL_TABLES,
       ["surrender_reason", "surrender_value_paid", "surrender_charge",
        "product_name", "policy_status", "sum_assured"],
       ["surrender_rate", "avg_surrender_charge"],
       ["surrender", "diagnostic", "risk"],
       "driver_analysis", "driver_analysis", REL_SURR,
       caveat="Only 40 surrenders exist in the dataset, so every breakdown below is "
              "based on very small counts and should be read as directional.")

    ps("Which products have the highest surrender risk?",
       bi.SURRENDER_ANALYSIS,
       "Rank surrender-eligible products; exclude products that cannot be surrendered.",
       bi.TIER_ANALYTICAL,
       ["Which products have the highest surrender risk?",
        "Which product surrenders most?",
        "Rank products by surrender rate.",
        "Where is surrender worst by product?"],
       [step("s1", "Surrender by product vs baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "surrender_rate"},
             "Rate and gap per surrender-eligible product."),
        step("s2", "Surrender economics by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "surrender_rate", "total_surrender_value_paid",
                          "avg_surrender_charge", "avg_sum_assured"],
              "sort_by": "surrender_rate"},
             "What each product's surrenders cost.")],
       ["policies", "surrenders", "products"],
       ["product_name", "policy_status", "surrender_value_paid", "surrender_charge"],
       ["surrender_rate", "avg_surrender_charge"],
       ["surrender", "product", "risk"], "leaderboard", "leaderboard", REL_SURR,
       caveat="Term Life and Health Rider carry no surrender value and are excluded "
              "from the denominator rather than reported as 0%.")

    ps("Which channels have elevated surrender rates?",
       bi.SURRENDER_ANALYSIS, "Distribution view of surrender.",
       bi.TIER_ANALYTICAL,
       ["Which channels have elevated surrender rates?",
        "Which channel surrenders most?",
        "Rank channels by surrender.",
        "Is surrender a channel problem?"],
       [step("s1", "Surrender by channel vs baseline", "compare_to_baseline",
             {"dimension": "channel", "metric": "surrender_rate"}, "Rate and gap per channel."),
        step("s2", "Channel context", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["policy_count", "surrender_rate", "lapse_rate",
                          "avg_sum_assured", "avg_customer_income"],
              "sort_by": "surrender_rate"},
             "Whether surrender and lapse move together by channel.")],
       ["policies", "surrenders"], ["sales_channel", "policy_status"],
       ["surrender_rate", "lapse_rate"],
       ["surrender", "channel"], "leaderboard", "leaderboard", REL_SURR)

    ps("Which customer segments are more likely to surrender?",
       bi.SURRENDER_ANALYSIS, "Customer-side view of surrender risk.",
       bi.TIER_MULTI_STEP,
       ["Which customer segments are more likely to surrender?",
        "Who surrenders their policies?",
        "Which customers surrender most?",
        "What kind of customer surrenders?"],
       [step("s1", "Surrender by income band", "compare_to_baseline",
             {"dimension": "income_band", "metric": "surrender_rate"}, "Income effect."),
        step("s2", "Surrender by age band", "compare_to_baseline",
             {"dimension": "age_band", "metric": "surrender_rate"}, "Life-stage effect."),
        step("s3", "Surrender by sum-assured band", "compare_to_baseline",
             {"dimension": "sa_band", "metric": "surrender_rate"}, "Policy-size effect."),
        step("s4", "Surrendered-policy profile", "segment_profile",
             {"filters": {"policy_status": "Surrendered"}},
             "Full contrast against the book.")],
       ["policies", "customers", "surrenders"],
       ["annual_income", "age", "sum_assured", "policy_status"],
       ["surrender_rate"], ["surrender", "customer", "risk"],
       "risk_segmentation", "risk_segmentation", REL_SURR,
       caveat="40 surrenders spread across segments produce very small cell counts.")

    ps("Are high-value policies disproportionately represented among surrenders?",
       bi.SURRENDER_ANALYSIS,
       "Test whether the book loses its best business to surrender.",
       bi.TIER_MULTI_STEP,
       ["Are high-value policies disproportionately represented among surrenders?",
        "Do our biggest policies surrender more?",
        "Is surrender concentrated in large policies?",
        "Are we losing high-value business to surrender?"],
       [step("s1", "Surrendered vs portfolio value profile", "segment_profile",
             {"filters": {"policy_status": "Surrendered"},
              "metrics": ["policy_count", "avg_sum_assured", "median_sum_assured",
                          "avg_annual_premium", "avg_customer_income",
                          "avg_premium_to_income"]},
             "Directly compare surrendered policy size with the book."),
        step("s2", "Surrender rate by sum-assured band", "compare_to_baseline",
             {"dimension": "sa_band", "metric": "surrender_rate"},
             "Whether surrender rises with policy size."),
        step("s3", "Surrender value paid by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "surrender_rate", "total_surrender_value_paid",
                          "avg_surrender_charge"],
              "sort_by": "total_surrender_value_paid"},
             "Where the money actually went out.")],
       ["policies", "surrenders", "customers"],
       ["sum_assured", "surrender_value_paid", "surrender_charge", "policy_status"],
       ["surrender_rate", "avg_sum_assured", "total_surrender_value_paid"],
       ["surrender", "value", "concentration"],
       "segment_contrast", "segment_contrast", REL_SURR)

    ps("Which customers should be prioritised for surrender-prevention intervention?",
       bi.SURRENDER_ANALYSIS,
       "Produce an actionable list of in-force policies resembling the surrender profile.",
       bi.TIER_MULTI_STEP,
       ["Which customers should be prioritized for intervention?",
        "Who is at risk of surrendering next?",
        "Which policies should we protect from surrender?",
        "Give me a surrender-prevention target list."],
       [step("s1", "Surrendered-policy profile", "segment_profile",
             {"filters": {"policy_status": "Surrendered"}},
             "Establish what a surrender looks like in this book."),
        step("s2", "Highest-risk surrender-eligible products", "compare_to_baseline",
             {"dimension": "product", "metric": "surrender_rate"},
             "Which products to draw the list from."),
        step("s3", "Ranked in-force policies on the risky products", "entity_shortlist",
             {"base": "policy",
              "filters": {"policy_status": "In-Force", "product": "$risky_products"},
              "score_components": [{"column": "sum_assured", "weight": 0.4, "direction": "high"},
                                   {"column": "annual_premium", "weight": 0.3, "direction": "high"},
                                   {"column": "premium_to_income", "weight": 0.3, "direction": "high"}],
              "top_n": 20,
              "columns": ["policy_number", "customer_name", "product_name", "sales_channel",
                          "zone", "sum_assured", "annual_premium", "annual_income",
                          "premium_to_income", "policy_status"]},
             "Rank by what is at stake, restricted to the high-surrender products.")],
       ["policies", "customers", "surrenders"],
       ["policy_status", "product_name", "sum_assured", "annual_premium", "annual_income"],
       ["surrender_rate", "avg_sum_assured"],
       ["surrender", "customer", "attention", "recommendation"],
       "shortlist", "shortlist", REL_SURR,
       parameters={"risky_products": {"source": "step:s2", "field": "product_name",
                                      "take": 3,
                                      "description": "Top surrender-rate products"}},
       caveat="This is a profile-similarity shortlist built from 40 historical "
              "surrenders, not a calibrated propensity model.")

    ps("What patterns distinguish surrendered policies from retained policies?",
       bi.SURRENDER_ANALYSIS,
       "Contrast the two groups on every measurable characteristic.",
       bi.TIER_MULTI_STEP,
       ["What patterns distinguish surrendered policies from retained policies?",
        "How do surrendered policies differ from in-force ones?",
        "Compare surrendered and retained policies.",
        "What is different about policies that surrender?"],
       [step("s1", "Surrendered-policy profile", "segment_profile",
             {"filters": {"policy_status": "Surrendered"}}, "The surrender group."),
        step("s2", "In-force policy profile", "segment_profile",
             {"filters": {"policy_status": "In-Force"}}, "The retained group."),
        step("s3", "Surrender reasons", "multi_metric_table",
             {"dimension": "surrender_reason",
              "metrics": ["policy_count", "avg_sum_assured"],
              "sort_by": "policy_count", "min_n": 1},
             "What customers said when they left."),
        step("s4", "Product mix of surrenders", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "surrender_rate"],
              "filters": {"policy_status": "Surrendered"}, "sort_by": "policy_count",
              "min_n": 1},
             "Which products the surrenders came from.")],
       ["policies", "customers", "surrenders"],
       ["policy_status", "surrender_reason", "sum_assured", "annual_income"],
       ["surrender_rate", "avg_sum_assured", "avg_customer_income"],
       ["surrender", "comparison", "diagnostic"],
       "segment_contrast", "segment_contrast", REL_SURR)

    ps("What do surrenders cost the business in value paid and charges recovered?",
       bi.SURRENDER_ANALYSIS,
       "Quantify the financial footprint of surrender activity.",
       bi.TIER_ANALYTICAL,
       ["What do surrenders cost us?",
        "How much surrender value have we paid out?",
        "What is the total surrender charge collected?",
        "What is the financial impact of surrenders?"],
       [step("s1", "Surrender economics by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "surrender_rate", "total_surrender_value_paid",
                          "avg_surrender_charge"],
              "sort_by": "total_surrender_value_paid", "min_n": 1},
             "Value out and charges recovered per product."),
        step("s2", "Surrender economics by reason", "multi_metric_table",
             {"dimension": "surrender_reason",
              "metrics": ["policy_count", "total_surrender_value_paid",
                          "avg_surrender_charge"],
              "sort_by": "total_surrender_value_paid", "min_n": 1},
             "Value out by stated reason."),
        step("s3", "Portfolio baseline", "portfolio_overview", {},
             "Scale the surrender outflow against the book.")],
       ["policies", "surrenders"],
       ["surrender_value_paid", "surrender_charge", "surrender_reason", "product_name"],
       ["total_surrender_value_paid", "avg_surrender_charge", "surrender_rate"],
       ["surrender", "economics"], "economics", "economics", REL_SURR)

    ps("Which zones show elevated surrender activity?",
       bi.SURRENDER_ANALYSIS, "Geographic view of surrender.",
       bi.TIER_ANALYTICAL,
       ["Which zones have higher surrender risk?",
        "Where geographically do policies surrender?",
        "Rank zones by surrender rate.",
        "Is surrender concentrated in a region?"],
       [step("s1", "Surrender by zone vs baseline", "compare_to_baseline",
             {"dimension": "zone", "metric": "surrender_rate"}, "Rate and gap per zone."),
        step("s2", "Zone surrender context", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["policy_count", "surrender_rate", "lapse_rate",
                          "total_surrender_value_paid"],
              "sort_by": "surrender_rate"},
             "Volume, attrition and value out per zone.")],
       ["policies", "surrenders"], ["zone", "policy_status", "surrender_value_paid"],
       ["surrender_rate"], ["surrender", "zone"], "leaderboard", "leaderboard", REL_SURR,
       caveat="Zone surrender counts are in single digits; differences are not "
              "statistically meaningful at this sample size.")

    ps("Do surrenders cluster in particular policy vintages?",
       bi.SURRENDER_ANALYSIS,
       "Check whether surrender happens early (mis-selling signal) or late (maturity-seeking).",
       bi.TIER_ANALYTICAL,
       ["When do policies surrender?",
        "Do surrenders happen early or late in the policy?",
        "How does surrender vary with policy age?",
        "Is early surrender a problem?"],
       [step("s1", "Surrender by policy vintage band", "compare_to_baseline",
             {"dimension": "policy_age_band", "metric": "surrender_rate"},
             "Surrender rate by how long the policy has run."),
        step("s2", "Vintage context", "multi_metric_table",
             {"dimension": "policy_age_band",
              "metrics": ["policy_count", "surrender_rate", "avg_surrender_charge",
                          "total_surrender_value_paid"],
              "sort_by": "policy_age_band", "ascending": True},
             "Charges and value out by vintage.")],
       ["policies", "surrenders"], ["issuance_date", "policy_status", "surrender_charge"],
       ["surrender_rate", "avg_surrender_charge"],
       ["surrender", "portfolio"], "trend", "leaderboard", REL_SURR)


# =====================================================================
# G. RETENTION STRATEGY
# =====================================================================

def domain_retention():
    ps("Which retention contact channels are most effective?",
       bi.RETENTION_STRATEGY,
       "Direct retention capacity to the outreach method that actually saves policies.",
       bi.TIER_MULTI_STEP,
       ["Which retention channels are most effective?",
        "Which contact channel saves the most policies?",
        "What is the best way to reach at-risk customers?",
        "Rank retention channels by effectiveness.",
        "Which outreach method works best?"],
       [step("s1", "Success rate by contact channel", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate",
                          "retention_loss_to_lapse_rate", "avg_retention_incentive",
                          "incentive_per_retained_policy"],
              "sort_by": "retention_success_rate", "ascending": False},
             "Effectiveness and cost per contact channel."),
        step("s2", "Success rate vs baseline", "compare_to_baseline",
             {"dimension": "contact_channel", "metric": "retention_success_rate"},
             "Which channels genuinely beat the average."),
        step("s3", "Offer effectiveness", "multi_metric_table",
             {"dimension": "offer",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False},
             "Whether the offer extended matters as much as the channel.")],
       ["retention", "policies"],
       ["contact_channel", "retention_status", "offers_extended", "agent_incentive_amount"],
       ["retention_success_rate", "incentive_per_retained_policy"],
       ["retention", "channel", "comparison"],
       "leaderboard", "leaderboard", REL_RET,
       caveat="Contact channel was not randomly assigned; channels may have been "
              "chosen based on how salvageable the case already looked.")

    ps("Does retention effectiveness differ by customer segment?",
       bi.RETENTION_STRATEGY,
       "Find which customers respond to outreach so effort is not wasted.",
       bi.TIER_MULTI_STEP,
       ["Does retention effectiveness differ by customer segment?",
        "Which customers can we actually save?",
        "Are some segments easier to retain?",
        "Where does retention outreach work best?"],
       [step("s1", "Success by income band", "multi_metric_table",
             {"dimension": "income_band",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False, "min_n": 20},
             "Saveability by means."),
        step("s2", "Success by age band", "multi_metric_table",
             {"dimension": "age_band",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False, "min_n": 20},
             "Saveability by life stage."),
        step("s3", "Success by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False, "min_n": 20},
             "Saveability by product."),
        step("s4", "Success vs baseline by contact channel", "compare_to_baseline",
             {"dimension": "contact_channel", "metric": "retention_success_rate"},
             "The channel effect for reference.")],
       ["retention", "policies", "customers"],
       ["retention_status", "annual_income", "age", "product_name"],
       ["retention_success_rate", "retention_contacts"],
       ["retention", "customer", "comparison"],
       "leaderboard", "leaderboard", REL_RET)

    ps("Which customers are the best candidates for retention intervention right now?",
       bi.RETENTION_STRATEGY,
       "Produce a ranked, named call list weighted by value at risk.",
       bi.TIER_MULTI_STEP,
       ["Which customers should the retention team prioritize?",
        "Which customers are the best candidates for retention intervention?",
        "Give me a retention call list.",
        "Who should we contact first about retention?",
        "Which high-value customers are at risk?"],
       [step("s1", "Where lapse risk concentrates", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {}, "min_n": 25, "top_k": 6},
             "Establish which segments the list should over-weight."),
        step("s2", "Product-level lapse risk", "compare_to_baseline",
             {"dimension": "product", "metric": "lapse_rate"},
             "Which products contribute the most risk."),
        step("s3", "Ranked in-force policies by value at risk", "entity_shortlist",
             {"base": "policy", "filters": {"policy_status": "In-Force"},
              "score_components": [{"column": "annual_premium", "weight": 0.4, "direction": "high"},
                                   {"column": "sum_assured", "weight": 0.25, "direction": "high"},
                                   {"column": "premium_to_income", "weight": 0.35, "direction": "high"}],
              "top_n": 20,
              "columns": ["policy_number", "customer_name", "customer_id", "product_name",
                          "sales_channel", "zone", "payment_mode", "annual_premium",
                          "sum_assured", "annual_income", "premium_to_income"]},
             "Rank live policies by premium at stake and affordability strain."),
        step("s4", "Most effective outreach channel", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False},
             "Tell the team how to make the contact, not just whom to call.")],
       ALL_TABLES,
       ["policy_status", "annual_premium", "sum_assured", "annual_income",
        "product_name", "retention_status", "contact_channel"],
       ["lapse_rate", "retention_success_rate", "avg_annual_premium"],
       ["retention", "customer", "value", "attention", "recommendation"],
       "shortlist", "retention_shortlist", REL_RET,
       caveat="Ranking is by value at stake and affordability strain, both observed "
              "in the data. It is not a trained lapse-propensity score.")

    ps("Which high-value customers are currently at risk?",
       bi.RETENTION_STRATEGY,
       "Cross value against risk so the biggest exposures surface first.",
       bi.TIER_MULTI_STEP,
       ["Which high-value customers are at risk?",
        "Are we about to lose any big customers?",
        "Show me at-risk high value policies.",
        "Which valuable policies look shaky?"],
       [step("s1", "Customers with existing attrition and high value", "entity_shortlist",
             {"base": "customer", "filters": {"has_attrition": True},
              "score_components": [{"column": "value_score", "weight": 0.6, "direction": "high"},
                                   {"column": "attrition_ratio", "weight": 0.4, "direction": "high"}],
              "top_n": 20,
              "columns": ["customer_id", "full_name", "annual_income", "policy_count",
                          "inforce_policies", "lapsed_policies", "surrendered_policies",
                          "total_annual_premium", "total_sum_assured", "attrition_ratio",
                          "product_name"]},
             "Customers who already lost a policy and still hold value."),
        step("s2", "Value concentration by income band", "concentration",
             {"dimension": "income_band", "value_metric": "total_annual_premium", "top_n": 2},
             "How much premium the top segments carry."),
        step("s3", "Lapse risk by income band", "compare_to_baseline",
             {"dimension": "income_band", "metric": "lapse_rate"},
             "Whether the valuable segments are also the risky ones.")],
       ["policies", "customers"],
       ["annual_income", "annual_premium", "sum_assured", "policy_status"],
       ["lapse_rate", "premium_share"],
       ["retention", "value", "customer", "risk"],
       "shortlist", "shortlist", REL_CORE)

    ps("Which customer, product and channel combinations show the poorest retention?",
       bi.RETENTION_STRATEGY,
       "Locate the specific cells where retention effort fails.",
       bi.TIER_MULTI_STEP,
       ["What customer/product/channel combinations show poor retention?",
        "Where does retention fail?",
        "Which combinations retain worst?",
        "Show me the weakest retention pockets."],
       [step("s1", "Retention success: product x contact channel", "crosstab_metric",
             {"dim_a": "product", "dim_b": "contact_channel",
              "metric": "retention_success_rate", "min_n": 10},
             "Which product-outreach cells fail."),
        step("s2", "Retention success: channel x contact channel", "crosstab_metric",
             {"dim_a": "channel", "dim_b": "contact_channel",
              "metric": "retention_success_rate", "min_n": 10},
             "Whether originating channel interacts with outreach method."),
        step("s3", "Retention success by zone", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": True},
             "Geographic variation in save rate."),
        step("s4", "Retention baseline", "compare_to_baseline",
             {"dimension": "contact_channel", "metric": "retention_success_rate"},
             "The average every cell is judged against.")],
       ["retention", "policies", "customers"],
       ["retention_status", "contact_channel", "product_name", "sales_channel", "zone"],
       ["retention_success_rate"],
       ["retention", "product", "channel", "concentration"],
       "grid", "grid", REL_RET)

    ps("What retention strategy should management prioritise?",
       bi.RETENTION_STRATEGY,
       "Assemble channel, segment and target evidence into one recommendation.",
       bi.TIER_MULTI_STEP,
       ["What retention strategy should management prioritize?",
        "What should our retention strategy be?",
        "How should we spend retention budget?",
        "Give me a retention plan.",
        "Where should management focus retention efforts?"],
       [step("s1", "Current retention performance", "portfolio_overview", {},
             "How well retention works today, at what cost."),
        step("s2", "Most effective outreach channels", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate",
                          "incentive_per_retained_policy"],
              "sort_by": "retention_success_rate", "ascending": False},
             "Effectiveness against cost per save."),
        step("s3", "Products to target, weighted by premium at stake", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "lapse_rate", "weight": 0.4, "direction": "high"},
                             {"metric": "premium_share", "weight": 0.35, "direction": "high"},
                             {"metric": "avg_annual_premium", "weight": 0.25, "direction": "high"}]},
             "Where the retention spend earns most."),
        step("s4", "Segments to target", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {}, "min_n": 25, "top_k": 6},
             "Which customer segments to over-weight in the campaign.")],
       ALL_TABLES,
       ["retention_status", "contact_channel", "agent_incentive_amount",
        "product_name", "annual_premium", "policy_status"],
       ["retention_success_rate", "incentive_per_retained_policy", "lapse_rate",
        "premium_share"],
       ["retention", "recommendation", "attention"],
       "action_plan", "action_plan", REL_RET)

    ps("What does the retention funnel look like from contact to outcome?",
       bi.RETENTION_STRATEGY,
       "Show what happens to contacted policies rather than just the save rate.",
       bi.TIER_ANALYTICAL,
       ["What happens to policies after retention contact?",
        "What is our retention funnel?",
        "How many contacted policies were saved?",
        "Show me retention outcomes."],
       [step("s1", "Outcome mix by contact channel", "crosstab_metric",
             {"dim_a": "contact_channel", "dim_b": "retention_status",
              "metric": "retention_contacts", "min_n": 1},
             "Every outcome for every channel."),
        step("s2", "Headline retention metrics", "portfolio_overview", {},
             "Contacts, saves and cost."),
        step("s3", "Outcome mix by offer", "crosstab_metric",
             {"dim_a": "offer", "dim_b": "retention_status",
              "metric": "retention_contacts", "min_n": 1},
             "Whether the offer changed the outcome mix.")],
       ["retention", "policies"],
       ["retention_status", "contact_channel", "offers_extended"],
       ["retention_contacts", "retention_success_rate"],
       ["retention"], "distribution", "distribution", REL_RET)

    ps("Is retention spend proportionate to the value it saves?",
       bi.RETENTION_STRATEGY,
       "Check cost-per-save across channels and segments.",
       bi.TIER_ANALYTICAL,
       ["Is our retention spend efficient?",
        "What does it cost to save a policy?",
        "How much incentive do we pay per retained policy?",
        "Which retention channel is most cost effective?"],
       [step("s1", "Cost per save by contact channel", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate",
                          "total_retention_incentive", "avg_retention_incentive",
                          "incentive_per_retained_policy"],
              "sort_by": "incentive_per_retained_policy", "ascending": True},
             "Effectiveness against spend."),
        step("s2", "Value of what is being saved", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["avg_annual_premium", "avg_sum_assured"],
              "sort_by": "avg_annual_premium", "ascending": False},
             "Whether the cheapest channel also saves the smallest policies.")],
       ["retention", "policies"],
       ["agent_incentive_amount", "retention_status", "contact_channel", "annual_premium"],
       ["incentive_per_retained_policy", "retention_success_rate"],
       ["retention", "economics"], "economics", "economics", REL_RET,
       caveat="Only the agent incentive is recorded. Staff time, call costs and "
              "any premium concession are not in the dataset, so this is a partial "
              "cost view.")

    ps("How does the retention team perform by zone and branch?",
       bi.RETENTION_STRATEGY, "Operational view for retention management.",
       bi.TIER_ANALYTICAL,
       ["How does retention perform by zone?",
        "Which zone retains best?",
        "Rank branches on retention success.",
        "Is retention performance geographic?"],
       [step("s1", "Retention by zone", "compare_to_baseline",
             {"dimension": "zone", "metric": "retention_success_rate"},
             "Zone save rates against the average."),
        step("s2", "Retention by branch", "multi_metric_table",
             {"dimension": "branch",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": True, "min_n": 15},
             "Branch-level detail where samples allow."),
        step("s3", "Contact channel mix by zone", "crosstab_metric",
             {"dim_a": "zone", "dim_b": "contact_channel",
              "metric": "retention_contacts", "min_n": 1},
             "Whether zones use different outreach methods.")],
       ["retention", "policies"], ["zone", "branch_name", "retention_status", "contact_channel"],
       ["retention_success_rate", "retention_contacts"],
       ["retention", "zone"], "leaderboard", "leaderboard", REL_RET)

    ps("Which retention offers work best and for whom?",
       bi.RETENTION_STRATEGY, "Evaluate the offer catalogue rather than just the channel.",
       bi.TIER_ANALYTICAL,
       ["Which retention offers work best?",
        "Does a grace period extension work better than fee-free reinstatement?",
        "Which offer saves more policies?",
        "Compare retention offers."],
       [step("s1", "Success by offer", "multi_metric_table",
             {"dimension": "offer",
              "metrics": ["retention_contacts", "retention_success_rate",
                          "retention_loss_to_lapse_rate", "avg_retention_incentive"],
              "sort_by": "retention_success_rate", "ascending": False},
             "Effectiveness per offer."),
        step("s2", "Offer x contact channel grid", "crosstab_metric",
             {"dim_a": "offer", "dim_b": "contact_channel",
              "metric": "retention_success_rate", "min_n": 10},
             "Whether offer and channel interact."),
        step("s3", "Offer x product grid", "crosstab_metric",
             {"dim_a": "offer", "dim_b": "product",
              "metric": "retention_success_rate", "min_n": 10},
             "Whether some offers suit some products.")],
       ["retention", "policies"],
       ["offers_extended", "retention_status", "contact_channel", "product_name"],
       ["retention_success_rate"],
       ["retention", "comparison"], "comparison", "comparison", REL_RET,
       caveat="Offers were not randomly assigned, so differences may reflect which "
              "cases each offer was chosen for.")


# =====================================================================
# H. CLAIMS & RISK
# =====================================================================

def domain_claims():
    ps("What is driving claims risk in the portfolio?",
       bi.CLAIMS_RISK,
       "Separate contractual payouts from underwriting losses, then locate the risk.",
       bi.TIER_MULTI_STEP,
       ["What is driving claims risk?",
        "Where is our claims risk coming from?",
        "What is behind our claims numbers?",
        "What should the claims team look at?"],
       [step("s1", "Portfolio claims baseline", "portfolio_overview", {},
             "Claim rate, risk-claim rate and both loss ratios."),
        step("s2", "Claim-type mix", "multi_metric_table",
             {"dimension": "claim_type",
              "metrics": ["claim_count", "early_claim_rate", "repudiation_rate"],
              "sort_by": "claim_count", "min_n": 1},
             "Which claim types dominate and how they behave."),
        step("s3", "Risk-claim rate by product", "compare_to_baseline",
             {"dimension": "product", "metric": "risk_claim_rate"},
             "Which products generate underwriting claims."),
        step("s4", "Risk loss ratio by product", "compare_to_baseline",
             {"dimension": "product", "metric": "risk_loss_ratio"},
             "Which products cost most per rupee of premium."),
        step("s5", "Strongest segment associations with claims", "driver_scan",
             {"metric": "risk_claim_rate", "focus_filters": {}, "min_n": 40, "top_k": 8},
             "Rank every dimension by deviation in risk-claim rate.")],
       ["policies", "claims", "customers", "products"],
       ["claim_type", "claim_amount", "claim_status", "is_early_claim",
        "product_name", "total_premium_paid"],
       ["claim_rate", "risk_claim_rate", "loss_ratio", "risk_loss_ratio"],
       ["claims", "risk", "diagnostic"],
       "driver_analysis", "driver_analysis", REL_CLAIM,
       caveat="149 claims across the whole book means product- and segment-level "
              "claim counts are small; treat rankings as indicative.")

    ps("Which products have disproportionate claim activity?",
       bi.CLAIMS_RISK, "Rank products on claim frequency and severity.",
       bi.TIER_ANALYTICAL,
       ["Which products have disproportionate claim activity?",
        "Which product claims most?",
        "Rank products by claim rate.",
        "Where are claims concentrated by product?"],
       [step("s1", "Claims by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "claim_rate", "risk_claim_rate",
                          "avg_claim_amount", "total_claim_amount", "loss_ratio",
                          "risk_loss_ratio"],
              "sort_by": "risk_claim_rate"},
             "Frequency and severity per product."),
        step("s2", "Risk-claim gap to baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "risk_claim_rate"},
             "Which products genuinely deviate."),
        step("s3", "Claim amount concentration by product", "concentration",
             {"dimension": "product", "value_metric": "total_claim_amount", "top_n": 3},
             "How concentrated the claim spend is.")],
       ["policies", "claims"], ["product_name", "claim_amount", "claim_type"],
       ["claim_rate", "risk_claim_rate", "loss_ratio"],
       ["claims", "product", "risk"], "leaderboard", "leaderboard", REL_CLAIM)

    ps("Which claim types dominate which products?",
       bi.CLAIMS_RISK,
       "Understand the claim mix so 'high claims' can be interpreted correctly.",
       bi.TIER_ANALYTICAL,
       ["Which claim types dominate different products?",
        "What is the claim mix per product?",
        "Which products get death claims?",
        "Show me claim type by product."],
       [step("s1", "Claim count grid: product x claim type", "crosstab_metric",
             {"dim_a": "product", "dim_b": "claim_type", "metric": "claim_count",
              "min_n": 1},
             "The full claim mix grid."),
        step("s2", "Claim type totals", "multi_metric_table",
             {"dimension": "claim_type",
              "metrics": ["claim_count", "early_claim_rate", "repudiation_rate"],
              "sort_by": "claim_count", "min_n": 1},
             "Overall shape of the claim book."),
        step("s3", "Product loss ratios for context", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["loss_ratio", "risk_loss_ratio", "total_claim_amount"],
              "sort_by": "loss_ratio"},
             "Link the mix back to the economics.")],
       ["policies", "claims"], ["claim_type", "product_name", "claim_amount"],
       ["claim_count", "loss_ratio", "risk_loss_ratio"],
       ["claims", "product"], "grid", "grid", REL_CLAIM)

    ps("Are early claims concentrated in particular segments?",
       bi.CLAIMS_RISK,
       "Early claims are the closest available signal to anti-selection.",
       bi.TIER_MULTI_STEP,
       ["Are early claims concentrated in particular segments?",
        "Where do early claims come from?",
        "Which products have early claims?",
        "Is early claiming a problem anywhere?"],
       [step("s1", "Early-claim rate by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["claim_count", "early_claim_rate", "repudiation_rate"],
              "sort_by": "early_claim_rate", "min_n": 5},
             "Which products see claims soon after issue."),
        step("s2", "Early-claim rate by channel", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["claim_count", "early_claim_rate"],
              "sort_by": "early_claim_rate", "min_n": 5},
             "Whether a distribution route is over-represented."),
        step("s3", "Early-claim rate by underwriting flag", "multi_metric_table",
             {"dimension": "medical_underwriting",
              "metrics": ["claim_count", "early_claim_rate", "repudiation_rate"],
              "sort_by": "early_claim_rate", "min_n": 5},
             "Whether medically underwritten cases behave differently."),
        step("s4", "Early-claim rate by claim type", "multi_metric_table",
             {"dimension": "claim_type",
              "metrics": ["claim_count", "early_claim_rate"],
              "sort_by": "early_claim_rate", "min_n": 1},
             "Which claim types the early cases are.")],
       ["policies", "claims", "customers"],
       ["is_early_claim", "claim_type", "product_name", "sales_channel",
        "medical_underwriting_flag"],
       ["early_claim_rate", "repudiation_rate"],
       ["claims", "underwriting", "anomaly", "risk"],
       "leaderboard", "leaderboard", REL_CLAIM,
       caveat="21 early claims in total. This is a signal worth investigating, not "
              "evidence of anti-selection.")

    ps("Are there signs of adverse-selection-like patterns in the available data?",
       bi.CLAIMS_RISK,
       "Assemble the weak signals the dataset can actually support, and say what it cannot.",
       bi.TIER_MULTI_STEP,
       ["Are there signs of adverse-selection-like patterns in the available data?",
        "Do we have an anti-selection problem?",
        "Is anyone selecting against us?",
        "Are there signs of adverse selection?"],
       [step("s1", "Early claims by product and channel", "crosstab_metric",
             {"dim_a": "product", "dim_b": "channel", "metric": "early_claim_rate",
              "min_n": 5},
             "Where early claims cluster."),
        step("s2", "Non-underwritten versus underwritten outcomes", "multi_metric_table",
             {"dimension": "medical_underwriting",
              "metrics": ["policy_count", "risk_claim_rate", "risk_loss_ratio",
                          "avg_sum_assured", "smoker_share", "avg_customer_age"],
              "sort_by": "risk_claim_rate"},
             "Whether skipping underwriting is associated with more risk claims."),
        step("s3", "Smoker outcomes", "multi_metric_table",
             {"dimension": "smoker",
              "metrics": ["policy_count", "risk_claim_rate", "risk_loss_ratio",
                          "avg_sum_assured"],
              "sort_by": "risk_claim_rate"},
             "Whether declared smokers show elevated risk claims."),
        step("s4", "Portfolio baseline", "portfolio_overview", {},
             "Anchor every comparison.")],
       ["policies", "claims", "customers"],
       ["is_early_claim", "medical_underwriting_flag", "is_smoker", "claim_type",
        "sum_assured"],
       ["early_claim_rate", "risk_claim_rate", "risk_loss_ratio"],
       ["claims", "underwriting", "anomaly", "risk"],
       "diagnostic", "diagnostic", REL_CLAIM,
       caveat="Adverse selection cannot be established from this dataset. There is "
              "no application-stage disclosure data, no declined-risk data and no "
              "pricing data. What follows are observed differences only.")

    ps("Which products, customers or channels contribute disproportionately to claims cost?",
       bi.CLAIMS_RISK,
       "Move from claim frequency to where the money actually goes.",
       bi.TIER_MULTI_STEP,
       ["Which products, customers or channels contribute disproportionately to claims?",
        "Where does our claims spend go?",
        "Who costs us the most in claims?",
        "Which segments drive claims cost?"],
       [step("s1", "Claim spend concentration by product", "concentration",
             {"dimension": "product", "value_metric": "total_claim_amount", "top_n": 3},
             "How concentrated claim spend is by product."),
        step("s2", "Claim spend by channel", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["policy_count", "claim_rate", "total_claim_amount",
                          "loss_ratio", "risk_loss_ratio"],
              "sort_by": "total_claim_amount"},
             "Claim spend by distribution route."),
        step("s3", "Claim spend by age band", "multi_metric_table",
             {"dimension": "age_band",
              "metrics": ["policy_count", "claim_rate", "risk_claim_rate",
                          "total_claim_amount", "risk_loss_ratio"],
              "sort_by": "total_claim_amount"},
             "Claim spend by customer life stage."),
        step("s4", "Largest individual claims", "top_entity_concentration",
             {"column": "claim_amount", "top_n": 10, "base": "claim"},
             "How much of the claim spend sits on a handful of claims.")],
       ["policies", "claims", "customers"],
       ["claim_amount", "product_name", "sales_channel", "age"],
       ["total_claim_amount", "loss_ratio", "risk_loss_ratio"],
       ["claims", "concentration", "economics"],
       "concentration", "concentration", REL_CLAIM)

    ps("What should the claims and risk team investigate next?",
       bi.CLAIMS_RISK,
       "Turn the claims picture into a short investigation list.",
       bi.TIER_MULTI_STEP,
       ["What areas should the claims team investigate?",
        "What should the risk team look into?",
        "Give me a claims investigation list.",
        "Where should claims focus?"],
       [step("s1", "Portfolio claims baseline", "portfolio_overview", {},
             "Establish the reference numbers."),
        step("s2", "Products ranked on claims risk and materiality", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "risk_loss_ratio", "weight": 0.4, "direction": "high"},
                             {"metric": "risk_claim_rate", "weight": 0.3, "direction": "high"},
                             {"metric": "sum_assured_share", "weight": 0.3, "direction": "high"}]},
             "Where claims risk matters most in size terms."),
        step("s3", "Repudiation and early-claim hotspots", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["claim_count", "repudiation_rate", "early_claim_rate"],
              "sort_by": "repudiation_rate", "min_n": 5},
             "Quality-of-book signals."),
        step("s4", "Largest individual claims", "top_entity_concentration",
             {"column": "claim_amount", "top_n": 10, "base": "claim"},
             "Single-claim concentration risk.")],
       ["policies", "claims", "products"],
       ["claim_amount", "claim_status", "is_early_claim", "product_name"],
       ["risk_loss_ratio", "risk_claim_rate", "repudiation_rate", "early_claim_rate"],
       ["claims", "attention", "recommendation", "risk"],
       "action_plan", "action_plan", REL_CLAIM)

    ps("How do claim outcomes (settled, repudiated, pending) vary across the book?",
       bi.CLAIMS_RISK, "Operational view of claim handling.",
       bi.TIER_ANALYTICAL,
       ["How many claims are repudiated?",
        "What is our claim settlement rate?",
        "Which products have the most repudiated claims?",
        "How do claim outcomes vary?"],
       [step("s1", "Outcome grid: product x claim status", "crosstab_metric",
             {"dim_a": "product", "dim_b": "claim_status", "metric": "claim_count",
              "min_n": 1},
             "Every outcome for every product."),
        step("s2", "Repudiation rate by claim type", "multi_metric_table",
             {"dimension": "claim_type",
              "metrics": ["claim_count", "repudiation_rate", "early_claim_rate"],
              "sort_by": "repudiation_rate", "min_n": 1},
             "Which claim types get rejected."),
        step("s3", "Repudiation rate by channel", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["claim_count", "repudiation_rate"],
              "sort_by": "repudiation_rate", "min_n": 5},
             "Whether rejection concentrates in a distribution route.")],
       ["claims", "policies"], ["claim_status", "claim_type", "product_name", "sales_channel"],
       ["repudiation_rate", "claim_count"],
       ["claims"], "grid", "grid", REL_CLAIM)

    ps("Which zones carry the highest claims burden?",
       bi.CLAIMS_RISK, "Geographic view of claims.",
       bi.TIER_ANALYTICAL,
       ["Which zones have higher claims burden?",
        "Where geographically do claims come from?",
        "Rank zones by loss ratio.",
        "Is claims risk regional?"],
       [step("s1", "Claims by zone", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["policy_count", "claim_rate", "risk_claim_rate",
                          "total_claim_amount", "loss_ratio", "risk_loss_ratio"],
              "sort_by": "risk_loss_ratio"},
             "Frequency and cost per zone."),
        step("s2", "Loss ratio gap to baseline", "compare_to_baseline",
             {"dimension": "zone", "metric": "loss_ratio"},
             "Which zones genuinely deviate.")],
       ["policies", "claims"], ["zone", "claim_amount", "total_premium_paid"],
       ["claim_rate", "loss_ratio", "risk_loss_ratio"],
       ["claims", "zone"], "leaderboard", "leaderboard", REL_CLAIM)

    ps("Why does a specific product show high claim activity?",
       bi.CLAIMS_RISK,
       "Decompose one product's claims into type, segment and severity.",
       bi.TIER_MULTI_STEP,
       ["Why does Term Life have a high loss ratio?",
        "Why are claims high on Annuity?",
        "Explain the claims on ULIP.",
        "What is driving claims in Endowment?"],
       [step("s1", "Product claims vs every other product", "compare_to_baseline",
             {"dimension": "product", "metric": "loss_ratio"},
             "Confirm the product is genuinely worse."),
        step("s2", "Claim-type mix inside the product", "multi_metric_table",
             {"dimension": "claim_type",
              "metrics": ["claim_count", "early_claim_rate", "repudiation_rate"],
              "filters": {"product": "$product"}, "sort_by": "claim_count", "min_n": 1},
             "Whether the ratio is maturity payouts or underwriting losses."),
        step("s3", "Risk-only view", "compare_to_baseline",
             {"dimension": "product", "metric": "risk_loss_ratio"},
             "The same comparison with contractual payouts stripped out."),
        step("s4", "Segment deviations inside the product", "driver_scan",
             {"metric": "claim_rate", "focus_filters": {"product": "$product"},
              "min_n": 15, "top_k": 6},
             "Where inside the product the claims sit."),
        step("s5", "Product profile vs portfolio", "segment_profile",
             {"filters": {"product": "$product"}},
             "Structural context for the result.")],
       ["policies", "claims", "customers", "products"],
       ["product_name", "claim_type", "claim_amount", "total_premium_paid"],
       ["loss_ratio", "risk_loss_ratio", "claim_rate"],
       ["claims", "product", "diagnostic", "economics"],
       "diagnostic", "diagnostic", REL_CLAIM,
       parameters={"product": {"dimension": "product", "default": "Term Life",
                               "description": "Product to diagnose"}},
       caveat="A high all-claims loss ratio on a maturity-heavy product reflects "
              "contractual payouts, not underwriting loss. Always read the risk-only "
              "ratio alongside it.")


# =====================================================================
# I. PROFITABILITY / CLAIMS ECONOMICS
# =====================================================================

def domain_profitability():
    ps("Which products have the highest loss ratios?",
       bi.PROFITABILITY, "Rank products on claims-to-premium, both views.",
       bi.TIER_ANALYTICAL,
       ["Which products have the highest loss ratios?",
        "What is the loss ratio by product?",
        "Rank products by loss ratio.",
        "Which product costs us most in claims per rupee of premium?"],
       [step("s1", "Loss ratios by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "total_premium_collected", "total_claim_amount",
                          "loss_ratio", "risk_loss_ratio", "claim_rate"],
              "sort_by": "loss_ratio"},
             "All-claims and risk-only ratios side by side."),
        step("s2", "Loss ratio gap to baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "loss_ratio"},
             "Which products genuinely deviate.")],
       ["policies", "claims"],
       ["product_name", "claim_amount", "total_premium_paid"],
       ["loss_ratio", "risk_loss_ratio"],
       ["economics", "product", "claims"], "economics", "economics", REL_CLAIM,
       caveat="No expense, commission or reserving data exists in this dataset, so "
              "loss ratio here is claims-to-premium only, not underwriting profit.")

    ps("Which products appear economically attractive versus unattractive?",
       bi.PROFITABILITY,
       "Combine claims economics with persistency and scale into one judgement.",
       bi.TIER_MULTI_STEP,
       ["Which products appear economically attractive versus unattractive?",
        "Which products make us money?",
        "Which products are economically unattractive?",
        "Rank products on economics."],
       [step("s1", "Economic attractiveness score", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "risk_loss_ratio", "weight": 0.3, "direction": "low"},
                             {"metric": "loss_ratio", "weight": 0.2, "direction": "low"},
                             {"metric": "persistency_rate", "weight": 0.25, "direction": "high"},
                             {"metric": "premium_share", "weight": 0.25, "direction": "high"}]},
             "Score attractiveness explicitly rather than by loss ratio alone."),
        step("s2", "Underlying economics", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "total_premium_collected", "total_claim_amount",
                          "loss_ratio", "risk_loss_ratio", "persistency_rate",
                          "avg_annual_premium"],
              "sort_by": "loss_ratio"},
             "The numbers behind the score."),
        step("s3", "Portfolio baseline", "portfolio_overview", {},
             "Anchor attractiveness against the book.")],
       ["policies", "claims", "products"],
       ["product_name", "claim_amount", "total_premium_paid", "policy_status"],
       ["loss_ratio", "risk_loss_ratio", "persistency_rate", "premium_share"],
       ["economics", "product", "recommendation"],
       "economics", "economics", REL_CLAIM,
       caveat="Without expense and commission data this ranks claims economics and "
              "persistency, not profitability.")

    ps("Where are claims disproportionately high relative to premiums collected?",
       bi.PROFITABILITY,
       "Scan every dimension for the worst claims-to-premium pockets.",
       bi.TIER_MULTI_STEP,
       ["Where are claims disproportionately high relative to premiums?",
        "Where do claims outstrip premium?",
        "Which segments have bad claims economics?",
        "Where are we losing money on claims?"],
       [step("s1", "Loss ratio by product", "compare_to_baseline",
             {"dimension": "product", "metric": "loss_ratio"}, "Product view."),
        step("s2", "Loss ratio by channel", "compare_to_baseline",
             {"dimension": "channel", "metric": "loss_ratio"}, "Channel view."),
        step("s3", "Loss ratio by zone", "compare_to_baseline",
             {"dimension": "zone", "metric": "loss_ratio"}, "Geographic view."),
        step("s4", "Strongest deviations across all dimensions", "driver_scan",
             {"metric": "loss_ratio", "focus_filters": {}, "min_n": 40, "top_k": 8},
             "Rank every dimension by deviation in loss ratio.")],
       ["policies", "claims"],
       ["claim_amount", "total_premium_paid", "product_name", "sales_channel", "zone"],
       ["loss_ratio", "risk_loss_ratio"],
       ["economics", "claims", "risk"],
       "driver_analysis", "driver_analysis", REL_CLAIM)

    ps("Which customer segments contribute most to poor claims economics?",
       bi.PROFITABILITY, "Customer-side view of claims economics.",
       bi.TIER_ANALYTICAL,
       ["Which segments contribute most to poor claims economics?",
        "Which customers cost us most relative to premium?",
        "How does loss ratio vary by customer segment?",
        "Which customer groups have bad economics?"],
       [step("s1", "Loss ratio by age band", "multi_metric_table",
             {"dimension": "age_band",
              "metrics": ["policy_count", "total_premium_collected", "total_claim_amount",
                          "loss_ratio", "risk_loss_ratio", "risk_claim_rate"],
              "sort_by": "loss_ratio"},
             "Life-stage view."),
        step("s2", "Loss ratio by income band", "multi_metric_table",
             {"dimension": "income_band",
              "metrics": ["policy_count", "loss_ratio", "risk_loss_ratio", "claim_rate"],
              "sort_by": "loss_ratio"},
             "Income view."),
        step("s3", "Loss ratio by smoker status", "multi_metric_table",
             {"dimension": "smoker",
              "metrics": ["policy_count", "loss_ratio", "risk_loss_ratio",
                          "risk_claim_rate"],
              "sort_by": "risk_loss_ratio"},
             "Underwriting-class view.")],
       ["policies", "claims", "customers"],
       ["age", "annual_income", "is_smoker", "claim_amount", "total_premium_paid"],
       ["loss_ratio", "risk_loss_ratio", "risk_claim_rate"],
       ["economics", "customer", "claims"], "economics", "economics", REL_CLAIM)

    ps("How do channels compare on claims economics?",
       bi.PROFITABILITY, "Distribution view of claims-to-premium.",
       bi.TIER_ANALYTICAL,
       ["Which channels have the best economics?",
        "Compare channels on loss ratio.",
        "Does any channel write unprofitable business?",
        "What is the loss ratio by channel?"],
       [step("s1", "Economics by channel", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["policy_count", "total_premium_collected", "total_claim_amount",
                          "loss_ratio", "risk_loss_ratio", "persistency_rate"],
              "sort_by": "loss_ratio"},
             "Premium in, claims out, per channel."),
        step("s2", "Loss ratio gap to baseline", "compare_to_baseline",
             {"dimension": "channel", "metric": "loss_ratio"},
             "Which channels genuinely deviate.")],
       ["policies", "claims"], ["sales_channel", "claim_amount", "total_premium_paid"],
       ["loss_ratio", "risk_loss_ratio"],
       ["economics", "channel"], "economics", "economics", REL_CLAIM)

    ps("Which areas of claims economics require investigation?",
       bi.PROFITABILITY, "Prioritised economics investigation list.",
       bi.TIER_MULTI_STEP,
       ["Which areas require investigation on economics?",
        "Where should finance look?",
        "What economics issues need attention?",
        "Give me an economics watch list."],
       [step("s1", "Product economics priority", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "loss_ratio", "weight": 0.35, "direction": "high"},
                             {"metric": "risk_loss_ratio", "weight": 0.3, "direction": "high"},
                             {"metric": "premium_share", "weight": 0.35, "direction": "high"}]},
             "Rank products by bad economics weighted by premium at stake."),
        step("s2", "Economics detail", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["total_premium_collected", "total_claim_amount", "loss_ratio",
                          "risk_loss_ratio", "claim_rate", "policy_count"],
              "sort_by": "loss_ratio"},
             "The evidence behind the ranking."),
        step("s3", "Outlier detection on product loss ratio", "outliers",
             {"dimension": "product", "metric": "loss_ratio", "method": "iqr", "min_n": 20},
             "Which products are statistical outliers, not just top of a list.")],
       ["policies", "claims", "products"],
       ["claim_amount", "total_premium_paid", "product_name"],
       ["loss_ratio", "risk_loss_ratio", "premium_share"],
       ["economics", "attention", "anomaly"],
       "action_plan", "action_plan", REL_CLAIM)

    ps("How much premium has the book collected and how much has gone back out?",
       bi.PROFITABILITY, "The simplest money-in money-out view, with the split.",
       bi.TIER_ANALYTICAL,
       ["How much premium have we collected versus paid out?",
        "What is our total premium and total claims?",
        "What is the money in versus money out?",
        "Show me overall claims economics."],
       [step("s1", "Portfolio economics", "portfolio_overview", {},
             "Premium collected, claims paid, both loss ratios."),
        step("s2", "By product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["total_premium_collected", "total_claim_amount",
                          "total_surrender_value_paid", "loss_ratio", "risk_loss_ratio"],
              "sort_by": "total_premium_collected"},
             "The same split per product.")],
       ["policies", "claims", "surrenders"],
       ["total_premium_paid", "claim_amount", "surrender_value_paid"],
       ["loss_ratio", "risk_loss_ratio", "total_premium_collected"],
       ["economics", "portfolio"], "economics", "economics", REL_CLAIM)

    ps("Do policies with riders show different claims economics?",
       bi.PROFITABILITY, "Test whether rider attachment changes the economics.",
       bi.TIER_ANALYTICAL,
       ["Do riders affect claims economics?",
        "Are rider policies more profitable?",
        "How do policies with riders compare on loss ratio?",
        "Does rider attachment change claim behaviour?"],
       [step("s1", "Economics by rider attachment", "multi_metric_table",
             {"dimension": "rider",
              "metrics": ["policy_count", "avg_annual_premium", "claim_rate",
                          "risk_claim_rate", "loss_ratio", "risk_loss_ratio",
                          "persistency_rate"],
              "sort_by": "loss_ratio"},
             "With rider versus without."),
        step("s2", "Rider attachment by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["rider_attachment_rate", "loss_ratio", "risk_loss_ratio"],
              "sort_by": "rider_attachment_rate", "ascending": False},
             "Where riders are actually attached.")],
       ["policies", "claims"], ["rider_count", "claim_amount", "total_premium_paid"],
       ["loss_ratio", "risk_loss_ratio", "rider_attachment_rate"],
       ["economics", "product", "underwriting"], "comparison", "comparison", REL_CLAIM)

    ps("Does medical underwriting pay for itself in claims economics?",
       bi.PROFITABILITY,
       "Compare the claims outcomes of underwritten and non-underwritten business.",
       bi.TIER_ANALYTICAL,
       ["Does medical underwriting improve claims economics?",
        "Are medically underwritten policies better?",
        "Compare underwritten and non-underwritten business.",
        "Is underwriting worth it?"],
       [step("s1", "Economics by underwriting flag", "multi_metric_table",
             {"dimension": "medical_underwriting",
              "metrics": ["policy_count", "avg_sum_assured", "claim_rate",
                          "risk_claim_rate", "early_claim_rate", "loss_ratio",
                          "risk_loss_ratio", "repudiation_rate"],
              "sort_by": "risk_loss_ratio"},
             "Every claims metric split by underwriting."),
        step("s2", "Underwriting share by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["medical_underwriting_share", "avg_sum_assured",
                          "risk_loss_ratio"],
              "sort_by": "medical_underwriting_share", "ascending": False},
             "Where underwriting is applied.")],
       ["policies", "claims"],
       ["medical_underwriting_flag", "claim_amount", "total_premium_paid", "sum_assured"],
       ["risk_loss_ratio", "risk_claim_rate", "early_claim_rate"],
       ["economics", "underwriting", "claims"], "comparison", "comparison", REL_CLAIM,
       caveat="Underwriting is applied selectively to larger or riskier cases, so "
              "the two groups are not comparable populations.")

    ps("How do claims economics vary by policy vintage?",
       bi.PROFITABILITY,
       "Older policies have paid more premium and had more time to claim.",
       bi.TIER_ANALYTICAL,
       ["How does loss ratio vary by policy age?",
        "Do older policies have worse economics?",
        "How do claims economics change over a policy's life?",
        "Loss ratio by vintage?"],
       [step("s1", "Economics by policy vintage band", "multi_metric_table",
             {"dimension": "policy_age_band",
              "metrics": ["policy_count", "total_premium_collected", "total_claim_amount",
                          "loss_ratio", "risk_loss_ratio", "claim_rate"],
              "sort_by": "policy_age_band", "ascending": True},
             "Premium and claims by cohort age."),
        step("s2", "Loss ratio gap to baseline", "compare_to_baseline",
             {"dimension": "policy_age_band", "metric": "loss_ratio"},
             "Which vintages deviate.")],
       ["policies", "claims"], ["issuance_date", "claim_amount", "total_premium_paid"],
       ["loss_ratio", "risk_loss_ratio"],
       ["economics", "portfolio"], "trend", "leaderboard", REL_CLAIM,
       caveat="Maturity claims land only on old policies, so vintage loss ratios "
              "are mechanically higher at the old end.")
