"""
build_business_ps3.py  (part 3 of the library: domains J-O)
==========================================================
Geography, agents, anomaly/concentration, comparative benchmarking,
root-cause diagnostics and actionable targeting.
"""

from __future__ import annotations

import business_intents as bi
from build_business_ps import (
    ps, step, PERF_METRICS, RISK_METRICS, VALUE_METRICS,
    P_TABLES, ALL_TABLES, REL_CORE, REL_CLAIM, REL_SURR, REL_RET,
)


# =====================================================================
# J. GEOGRAPHIC / ZONE ANALYSIS
# =====================================================================

def domain_geography():
    ps("Which zones perform best across volume, value, persistency and claims?",
       bi.GEOGRAPHIC, "Give regional management a balanced league table.",
       bi.TIER_MULTI_STEP,
       ["Which zones perform best?",
        "Rank our zones on performance.",
        "Which region is strongest?",
        "How do zones compare overall?",
        "Compare zones on portfolio health."],
       [step("s1", "Zone scorecard", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["policy_count", "policy_share", "sum_assured_share",
                          "avg_sum_assured", "persistency_rate", "lapse_rate",
                          "surrender_rate", "loss_ratio"],
              "sort_by": "persistency_rate", "ascending": False},
             "Every zone on every metric."),
        step("s2", "Balanced zone score", "composite_score",
             {"dimension": "zone",
              "components": [{"metric": "persistency_rate", "weight": 0.35, "direction": "high"},
                             {"metric": "lapse_rate", "weight": 0.25, "direction": "low"},
                             {"metric": "loss_ratio", "weight": 0.2, "direction": "low"},
                             {"metric": "sum_assured_share", "weight": 0.2, "direction": "high"}]},
             "Collapse the scorecard into a ranking."),
        step("s3", "Retention performance by zone", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False},
             "Whether a weak zone can save its business.")],
       ALL_TABLES, ["zone", "policy_status", "sum_assured", "claim_amount", "retention_status"],
       ["persistency_rate", "lapse_rate", "loss_ratio", "retention_success_rate"],
       ["zone", "comparison", "health"],
       "priority_ranking", "priority_ranking", REL_RET)

    ps("Which zones have higher lapse or surrender risk?",
       bi.GEOGRAPHIC, "Attrition view by geography.", bi.TIER_ANALYTICAL,
       ["Which zones have higher lapse/surrender risk?",
        "Where is attrition worst geographically?",
        "Which region loses the most policies?",
        "Rank zones on attrition."],
       [step("s1", "Attrition by zone", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["policy_count", "lapse_rate", "surrender_rate",
                          "attrition_rate", "persistency_rate"],
              "sort_by": "attrition_rate"},
             "Lapse, surrender and combined attrition per zone."),
        step("s2", "Lapse gap to baseline", "compare_to_baseline",
             {"dimension": "zone", "metric": "lapse_rate"}, "Which zones deviate."),
        step("s3", "Branch detail", "compare_to_baseline",
             {"dimension": "branch", "metric": "lapse_rate", "min_n": 25},
             "Whether a zone problem is really one or two branches.")],
       P_TABLES, ["zone", "branch_name", "policy_status"],
       ["lapse_rate", "surrender_rate", "attrition_rate"],
       ["zone", "lapse", "surrender"], "leaderboard", "leaderboard", REL_SURR)

    ps("Which zones carry the highest claims burden relative to premium?",
       bi.GEOGRAPHIC, "Claims economics by geography.", bi.TIER_ANALYTICAL,
       ["Which zones have higher claims burden?",
        "Which region costs most in claims?",
        "Loss ratio by zone?",
        "Where geographically are claims worst?"],
       [step("s1", "Claims economics by zone", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["policy_count", "claim_rate", "risk_claim_rate",
                          "total_claim_amount", "loss_ratio", "risk_loss_ratio"],
              "sort_by": "loss_ratio"},
             "Frequency and cost per zone."),
        step("s2", "Loss ratio gap to baseline", "compare_to_baseline",
             {"dimension": "zone", "metric": "loss_ratio"}, "Which zones deviate.")],
       ["policies", "claims"], ["zone", "claim_amount", "total_premium_paid"],
       ["loss_ratio", "risk_loss_ratio", "claim_rate"],
       ["zone", "claims", "economics"], "economics", "economics", REL_CLAIM)

    ps("Which zones have the strongest retention performance?",
       bi.GEOGRAPHIC, "Retention capability by geography.", bi.TIER_ANALYTICAL,
       ["Which zones have stronger retention?",
        "Where does retention work best geographically?",
        "Rank zones on retention success.",
        "Which region saves the most policies?"],
       [step("s1", "Retention by zone vs baseline", "compare_to_baseline",
             {"dimension": "zone", "metric": "retention_success_rate"},
             "Save rate and gap per zone."),
        step("s2", "Zone retention detail", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["retention_contacts", "retention_success_rate",
                          "retention_loss_to_lapse_rate", "incentive_per_retained_policy"],
              "sort_by": "retention_success_rate", "ascending": False},
             "Effectiveness and cost per zone."),
        step("s3", "Outreach mix by zone", "crosstab_metric",
             {"dim_a": "zone", "dim_b": "contact_channel",
              "metric": "retention_contacts", "min_n": 1},
             "Whether strong zones simply use better channels.")],
       ["retention", "policies"], ["zone", "retention_status", "contact_channel"],
       ["retention_success_rate", "incentive_per_retained_policy"],
       ["zone", "retention"], "leaderboard", "leaderboard", REL_RET)

    ps("Are there meaningful differences in product and channel mix across zones?",
       bi.GEOGRAPHIC, "Explain zone performance gaps through what each zone sells.",
       bi.TIER_MULTI_STEP,
       ["Are there meaningful differences in product/channel mix across zones?",
        "Do zones sell different products?",
        "How does channel mix vary by region?",
        "Is zone performance a mix effect?"],
       [step("s1", "Product mix by zone", "crosstab_metric",
             {"dim_a": "zone", "dim_b": "product", "metric": "policy_count", "min_n": 1},
             "What each zone sells."),
        step("s2", "Channel mix by zone", "crosstab_metric",
             {"dim_a": "zone", "dim_b": "channel", "metric": "policy_count", "min_n": 1},
             "How each zone distributes."),
        step("s3", "Lapse grid: zone x product", "crosstab_metric",
             {"dim_a": "zone", "dim_b": "product", "metric": "lapse_rate", "min_n": 15},
             "Whether zone lapse gaps survive once product is held roughly constant."),
        step("s4", "Zone lapse baseline", "compare_to_baseline",
             {"dimension": "zone", "metric": "lapse_rate"},
             "The headline gap the mix analysis is trying to explain.")],
       P_TABLES, ["zone", "product_name", "sales_channel", "policy_status"],
       ["policy_count", "lapse_rate"],
       ["zone", "product", "channel", "diagnostic"], "grid", "grid", REL_CORE,
       caveat="A cross-tab can show that mix differs; it cannot decompose how much "
              "of the zone gap is mix versus zone-specific execution.")

    ps("Which zones require management attention?",
       bi.GEOGRAPHIC, "Prioritised regional agenda.", bi.TIER_MULTI_STEP,
       ["Which zones require management attention?",
        "Which region needs help?",
        "Where should regional management focus?",
        "Give me a zone action list."],
       [step("s1", "Zone attention score", "composite_score",
             {"dimension": "zone",
              "components": [{"metric": "lapse_rate", "weight": 0.35, "direction": "high"},
                             {"metric": "surrender_rate", "weight": 0.15, "direction": "high"},
                             {"metric": "policy_share", "weight": 0.3, "direction": "high"},
                             {"metric": "loss_ratio", "weight": 0.2, "direction": "high"}]},
             "Rank zones by risk weighted by materiality."),
        step("s2", "Zone evidence table", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["policy_count", "policy_share", "lapse_rate", "surrender_rate",
                          "persistency_rate", "loss_ratio", "avg_sum_assured"],
              "sort_by": "lapse_rate"},
             "The numbers behind the ranking."),
        step("s3", "Drivers inside the priority zone", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {"zone": "$priority_zone"},
              "min_n": 12, "top_k": 6},
             "Make the instruction specific.")],
       ALL_TABLES, ["zone", "policy_status", "claim_amount", "sum_assured"],
       ["lapse_rate", "policy_share", "loss_ratio"],
       ["zone", "attention", "recommendation"],
       "priority_ranking", "priority_ranking", REL_CLAIM,
       parameters={"priority_zone": {"source": "step:s1", "field": "zone",
                                     "description": "Top-priority zone from step 1"}})

    ps("How do individual branches compare on portfolio quality?",
       bi.GEOGRAPHIC, "Branch-level operational league table.", bi.TIER_ANALYTICAL,
       ["Which branches perform best?",
        "Rank branches on lapse.",
        "Which branch has the worst persistency?",
        "Compare branches."],
       [step("s1", "Branch scorecard", "multi_metric_table",
             {"dimension": "branch",
              "metrics": ["policy_count", "avg_sum_assured", "lapse_rate",
                          "surrender_rate", "persistency_rate", "loss_ratio"],
              "sort_by": "lapse_rate", "min_n": 25},
             "Every branch with enough volume to judge."),
        step("s2", "Branch outliers on lapse", "outliers",
             {"dimension": "branch", "metric": "lapse_rate", "method": "iqr", "min_n": 25},
             "Which branches are genuine statistical outliers.")],
       ALL_TABLES, ["branch_name", "zone", "policy_status", "sum_assured"],
       ["lapse_rate", "persistency_rate", "loss_ratio"],
       ["zone", "anomaly", "comparison"], "leaderboard", "leaderboard", REL_CLAIM,
       caveat="With 20 branches over ~1,000 policies each branch holds ~50 policies, "
              "so branch rates move a lot on a handful of cases.")

    ps("How does a single named zone perform against the rest of the book?",
       bi.GEOGRAPHIC, "Zone-head scorecard.", bi.TIER_MULTI_STEP,
       ["How does the West zone compare with the rest?",
        "Assess the North zone.",
        "How is the Central zone doing?",
        "Give me the South zone numbers."],
       [step("s1", "Zone vs portfolio profile", "segment_profile",
             {"filters": {"zone": "$zone"}}, "Every headline metric against the book."),
        step("s2", "Product mix inside the zone", "multi_metric_table",
             {"dimension": "product", "metrics": RISK_METRICS,
              "filters": {"zone": "$zone"}, "sort_by": "lapse_rate", "min_n": 10},
             "What the zone sells and how it holds."),
        step("s3", "Branch detail inside the zone", "multi_metric_table",
             {"dimension": "branch",
              "metrics": ["policy_count", "lapse_rate", "persistency_rate",
                          "avg_sum_assured"],
              "filters": {"zone": "$zone"}, "sort_by": "lapse_rate", "min_n": 15},
             "Which branches drive the zone result.")],
       ALL_TABLES, ["zone", "branch_name", "product_name", "policy_status"],
       ["lapse_rate", "persistency_rate", "loss_ratio"],
       ["zone", "health"], "segment_assessment", "segment_contrast", REL_CLAIM,
       parameters={"zone": {"dimension": "zone", "default": "West",
                            "description": "Zone to assess"}})

    ps("Which states carry the most business and how do they perform?",
       bi.GEOGRAPHIC, "State-level view beneath the zone.", bi.TIER_ANALYTICAL,
       ["Which states have the most policies?",
        "How do states compare on lapse?",
        "Rank states by volume and persistency.",
        "Which state performs best?"],
       [step("s1", "State scorecard", "multi_metric_table",
             {"dimension": "state",
              "metrics": ["policy_count", "policy_share", "avg_sum_assured",
                          "lapse_rate", "persistency_rate"],
              "sort_by": "policy_share", "min_n": 25},
             "Volume and quality per state."),
        step("s2", "Volume concentration by state", "concentration",
             {"dimension": "state", "value_metric": "total_sum_assured", "top_n": 5},
             "How geographically concentrated the book is.")],
       P_TABLES, ["state", "zone", "policy_status", "sum_assured"],
       ["policy_share", "lapse_rate", "sum_assured_share"],
       ["zone", "concentration"], "leaderboard", "leaderboard", REL_CORE)


# =====================================================================
# K. AGENT / SALES PERFORMANCE
# =====================================================================

AGENT_COLS = ["servicing_agent_id", "full_name", "branch_id", "zone", "qualification",
              "employment_status", "policies_sold", "policies_serviced",
              "sum_assured_sold", "total_annual_premium", "avg_sum_assured",
              "target_achievement_pct", "observed_persistency_rate",
              "observed_lapse_rate", "observed_surrender_rate", "claims"]


def domain_agents():
    ps("Which agents are strongest overall once portfolio quality is taken into account?",
       bi.AGENT_PERFORMANCE,
       "Rank agents on a balanced scorecard rather than on volume alone.",
       bi.TIER_MULTI_STEP,
       ["Which agents are strongest overall?",
        "Who are our best agents?",
        "Rank agents on overall performance.",
        "Which advisors perform best?",
        "Who should we reward?"],
       [step("s1", "Balanced agent ranking", "entity_shortlist",
             {"base": "agent",
              "score_components": [
                  {"column": "target_achievement_pct", "weight": 0.25, "direction": "high"},
                  {"column": "observed_persistency_rate", "weight": 0.3, "direction": "high"},
                  {"column": "observed_lapse_rate", "weight": 0.25, "direction": "low"},
                  {"column": "sum_assured_sold", "weight": 0.2, "direction": "high"}],
              "top_n": 20, "columns": AGENT_COLS},
             "Score volume, target delivery and what actually stayed on the books."),
        step("s2", "Agent quality by qualification", "multi_metric_table",
             {"dimension": "agent_qualification",
              "metrics": ["policy_count", "lapse_rate", "persistency_rate",
                          "avg_sum_assured"],
              "sort_by": "persistency_rate", "ascending": False, "min_n": 25},
             "Whether agent background relates to book quality."),
        step("s3", "Portfolio baseline", "portfolio_overview", {},
             "Anchor agent numbers against the book.")],
       ["sales", "policies", "customers"],
       ["sales_person_id", "policies_sold", "target_achievement_pct",
        "persistency_rate", "lapse_rate", "sum_assured_sold", "policy_status"],
       ["lapse_rate", "persistency_rate", "avg_sum_assured"],
       ["agent", "comparison", "value"],
       "shortlist", "shortlist", REL_CORE,
       caveat="Agents service between 5 and 33 policies, so individual persistency "
              "rates move by 10-20 percentage points on a single policy.")

    ps("Which agents generate high volume but poor persistency?",
       bi.AGENT_PERFORMANCE,
       "Find the sell-hard keep-badly pattern at individual agent level.",
       bi.TIER_MULTI_STEP,
       ["Which agents generate high volume but poor persistency?",
        "Which agents sell a lot but their business lapses?",
        "Who writes bad business?",
        "Which agents have a quality problem?"],
       [step("s1", "High-volume, high-lapse agents", "entity_shortlist",
             {"base": "agent", "filters": {"policies_serviced": {"min": 10}},
              "score_components": [
                  {"column": "policies_serviced", "weight": 0.4, "direction": "high"},
                  {"column": "observed_lapse_rate", "weight": 0.6, "direction": "high"}],
              "top_n": 15, "columns": AGENT_COLS},
             "Rank on the combination of size and lapse."),
        step("s2", "Agent lapse outliers", "outliers",
             {"dimension": "agent", "metric": "lapse_rate", "method": "iqr", "min_n": 12},
             "Which of these are genuine statistical outliers."),
        step("s3", "Portfolio baseline", "portfolio_overview", {},
             "The lapse rate they are being compared against.")],
       ["sales", "policies"],
       ["sales_person_id", "policies_sold", "lapse_rate", "policy_status"],
       ["lapse_rate", "policy_count"],
       ["agent", "lapse", "anomaly"], "shortlist", "shortlist", REL_CORE,
       caveat="Small books make individual agent lapse rates unstable; treat this "
              "as a list to review, not a performance verdict.")

    ps("Which agents generate the highest-value policies?",
       bi.AGENT_PERFORMANCE, "Identify the big-ticket writers.", bi.TIER_ANALYTICAL,
       ["Which agents generate high-value policies?",
        "Who writes the biggest cases?",
        "Which agent has the highest average sum assured?",
        "Who brings in the most premium?"],
       [step("s1", "Agents ranked by value written", "entity_shortlist",
             {"base": "agent",
              "score_components": [
                  {"column": "avg_sum_assured", "weight": 0.5, "direction": "high"},
                  {"column": "total_annual_premium", "weight": 0.5, "direction": "high"}],
              "top_n": 20, "columns": AGENT_COLS},
             "Average case size and total premium written."),
        step("s2", "Value concentration by agent", "concentration",
             {"dimension": "agent", "value_metric": "total_sum_assured", "top_n": 10},
             "How much of the book depends on the top agents.")],
       ["sales", "policies"],
       ["sales_person_id", "sum_assured_sold", "sum_assured", "annual_premium"],
       ["avg_sum_assured", "total_annual_premium"],
       ["agent", "value", "concentration"], "shortlist", "shortlist", REL_CORE)

    ps("Which agents outperform targets but carry concerning portfolio quality?",
       bi.AGENT_PERFORMANCE,
       "Catch the case where incentive delivery and book quality point opposite ways.",
       bi.TIER_MULTI_STEP,
       ["Which agents outperform targets but have concerning portfolio quality?",
        "Are any high performers writing bad business?",
        "Who beats target but lapses badly?",
        "Show me agents where target and quality disagree."],
       [step("s1", "Above-target agents ranked by lapse", "entity_shortlist",
             {"base": "agent", "filters": {"target_achievement_pct": {"min": 100}},
              "score_components": [
                  {"column": "observed_lapse_rate", "weight": 0.5, "direction": "high"},
                  {"column": "target_achievement_pct", "weight": 0.3, "direction": "high"},
                  {"column": "observed_surrender_rate", "weight": 0.2, "direction": "high"}],
              "top_n": 15, "columns": AGENT_COLS},
             "Agents delivering on target whose book does not stick."),
        step("s2", "Agent lapse outliers", "outliers",
             {"dimension": "agent", "metric": "lapse_rate", "method": "zscore", "min_n": 12},
             "Statistical confirmation."),
        step("s3", "Portfolio baseline", "portfolio_overview", {},
             "Reference lapse rate.")],
       ["sales", "policies"],
       ["target_achievement_pct", "nbp_achieved", "nbp_target", "lapse_rate",
        "surrender_rate", "policy_status"],
       ["lapse_rate", "surrender_rate"],
       ["agent", "anomaly", "attention"], "shortlist", "shortlist", REL_CORE)

    ps("Are there agents with unusual performance patterns worth investigating?",
       bi.AGENT_PERFORMANCE, "Outlier detection across the sales force.",
       bi.TIER_MULTI_STEP,
       ["Are there agents with unusual performance patterns?",
        "Which agents look statistically unusual?",
        "Any red flags in the sales force?",
        "Which agents should management investigate?"],
       [step("s1", "Lapse-rate outliers", "outliers",
             {"dimension": "agent", "metric": "lapse_rate", "method": "iqr", "min_n": 10},
             "Agents whose lapse rate sits outside the fence."),
        step("s2", "Surrender-rate outliers", "outliers",
             {"dimension": "agent", "metric": "surrender_rate", "method": "iqr", "min_n": 10},
             "Agents whose surrender rate sits outside the fence."),
        step("s3", "Average case-size outliers", "outliers",
             {"dimension": "agent", "metric": "avg_sum_assured", "method": "zscore",
              "min_n": 10},
             "Agents writing unusually large or small cases."),
        step("s4", "Sum assured concentration by agent", "concentration",
             {"dimension": "agent", "value_metric": "total_sum_assured", "top_n": 10},
             "Whether the book depends on a few individuals.")],
       ["sales", "policies"],
       ["sales_person_id", "policy_status", "sum_assured", "lapse_rate"],
       ["lapse_rate", "surrender_rate", "avg_sum_assured"],
       ["agent", "anomaly", "concentration"], "anomaly", "anomaly", REL_CORE,
       caveat="Outlier flags are statistical, based on small individual books. They "
              "are prompts for review, not findings of misconduct.")

    ps("How does agent target achievement relate to the quality of the book they write?",
       bi.AGENT_PERFORMANCE,
       "Test whether the incentive system is buying volume at the cost of persistency.",
       bi.TIER_MULTI_STEP,
       ["Does target achievement relate to portfolio quality?",
        "Do high-achieving agents write worse business?",
        "Is our incentive structure creating bad business?",
        "How does NBP achievement relate to lapse?"],
       [step("s1", "Agent-level table", "entity_shortlist",
             {"base": "agent", "filters": {"policies_serviced": {"min": 8}},
              "score_components": [
                  {"column": "target_achievement_pct", "weight": 1.0, "direction": "high"}],
              "top_n": 80, "columns": AGENT_COLS},
             "The full agent table sorted by target achievement, for inspection."),
        step("s2", "Quality by agent qualification", "multi_metric_table",
             {"dimension": "agent_qualification",
              "metrics": ["policy_count", "lapse_rate", "persistency_rate",
                          "avg_sum_assured", "avg_annual_premium"],
              "sort_by": "lapse_rate", "min_n": 25},
             "The one agent attribute with enough volume to compare reliably."),
        step("s3", "Portfolio baseline", "portfolio_overview", {},
             "Reference numbers.")],
       ["sales", "policies"],
       ["target_achievement_pct", "persistency_rate", "lapse_rate", "qualification"],
       ["lapse_rate", "persistency_rate"],
       ["agent", "diagnostic"], "shortlist", "shortlist", REL_CORE,
       caveat="`target_achievement_pct` and `persistency_rate` in the sales table are "
              "supplied fields; the observed rates recomputed from the policy table "
              "are shown alongside so the two can be compared.")

    ps("How does agent performance vary by branch and zone?",
       bi.AGENT_PERFORMANCE, "Aggregate the sales force up to management units.",
       bi.TIER_ANALYTICAL,
       ["How does agent performance vary by branch?",
        "Which branch has the best agents?",
        "Compare zones on sales force quality.",
        "Is agent quality geographic?"],
       [step("s1", "Book quality by branch", "multi_metric_table",
             {"dimension": "branch",
              "metrics": ["policy_count", "avg_sum_assured", "lapse_rate",
                          "persistency_rate"],
              "sort_by": "persistency_rate", "ascending": False, "min_n": 25},
             "Branch-level book quality."),
        step("s2", "Book quality by zone", "compare_to_baseline",
             {"dimension": "zone", "metric": "persistency_rate"},
             "Zone-level roll-up."),
        step("s3", "Top agents overall", "entity_shortlist",
             {"base": "agent",
              "score_components": [
                  {"column": "observed_persistency_rate", "weight": 0.5, "direction": "high"},
                  {"column": "sum_assured_sold", "weight": 0.5, "direction": "high"}],
              "top_n": 15, "columns": AGENT_COLS},
             "Named agents behind the branch numbers.")],
       ["sales", "policies"], ["branch_id", "zone", "policy_status", "sum_assured"],
       ["lapse_rate", "persistency_rate", "avg_sum_assured"],
       ["agent", "zone"], "leaderboard", "leaderboard", REL_CORE)

    ps("Which agents should management prioritise for coaching or review?",
       bi.AGENT_PERFORMANCE, "A ranked, named review list.", bi.TIER_MULTI_STEP,
       ["Which agents should management investigate?",
        "Who needs coaching?",
        "Give me an agent review list.",
        "Which agents need intervention?"],
       [step("s1", "Coaching priority ranking", "entity_shortlist",
             {"base": "agent", "filters": {"policies_serviced": {"min": 8}},
              "score_components": [
                  {"column": "observed_lapse_rate", "weight": 0.4, "direction": "high"},
                  {"column": "observed_surrender_rate", "weight": 0.2, "direction": "high"},
                  {"column": "policies_serviced", "weight": 0.2, "direction": "high"},
                  {"column": "target_achievement_pct", "weight": 0.2, "direction": "low"}],
              "top_n": 15, "columns": AGENT_COLS},
             "Weight poor book quality by how much business the agent touches."),
        step("s2", "Statistical confirmation", "outliers",
             {"dimension": "agent", "metric": "lapse_rate", "method": "iqr", "min_n": 10},
             "Separate genuine outliers from ordinary variation."),
        step("s3", "Portfolio baseline", "portfolio_overview", {},
             "Reference lapse rate.")],
       ["sales", "policies"],
       ["sales_person_id", "policy_status", "target_achievement_pct"],
       ["lapse_rate", "surrender_rate"],
       ["agent", "attention", "recommendation"], "shortlist", "shortlist", REL_CORE,
       caveat="Small individual books mean these rankings are unstable; use them to "
              "select cases for review, not to conclude anything about an agent.")

    ps("Which agents handle retention cases most effectively?",
       bi.AGENT_PERFORMANCE, "Agent view of the retention function.",
       bi.TIER_ANALYTICAL,
       ["Which agents retain policies best?",
        "Who is best at saving policies?",
        "Rank agents on retention success.",
        "Which agents should handle retention calls?"],
       [step("s1", "Retention success by agent", "multi_metric_table",
             {"dimension": "agent",
              "metrics": ["retention_contacts", "retention_success_rate",
                          "total_retention_incentive"],
              "sort_by": "retention_success_rate", "ascending": False, "min_n": 6},
             "Save rate per agent where enough cases exist."),
        step("s2", "Retention baseline", "portfolio_overview", {},
             "The average save rate."),
        step("s3", "Retention success by contact channel", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False},
             "Channel effect, which agents cannot be credited for.")],
       ["retention", "sales", "policies"],
       ["servicing_agent_id", "retention_status", "contact_channel"],
       ["retention_success_rate", "retention_contacts"],
       ["agent", "retention"], "leaderboard", "leaderboard", REL_RET,
       caveat="Each agent handled roughly 5-6 retention cases, so per-agent save "
              "rates are extremely noisy.")

    ps("Does the sales table's reported performance agree with what the policy book shows?",
       bi.AGENT_PERFORMANCE,
       "Reconcile supplied agent KPIs against rates recomputed from policies.",
       bi.TIER_ANALYTICAL,
       ["Do the agent statistics match the policy data?",
        "Is the reported persistency rate accurate?",
        "Compare reported and observed agent lapse rates.",
        "Can we trust the sales table numbers?"],
       [step("s1", "Reported vs observed per agent", "entity_shortlist",
             {"base": "agent", "filters": {"policies_serviced": {"min": 5}},
              "score_components": [
                  {"column": "policies_serviced", "weight": 1.0, "direction": "high"}],
              "top_n": 80,
              "columns": ["servicing_agent_id", "full_name", "policies_sold",
                          "policies_serviced", "persistency_rate",
                          "observed_persistency_rate", "lapse_rate",
                          "observed_lapse_rate", "surrender_rate",
                          "observed_surrender_rate"]},
             "Side-by-side of supplied and recomputed rates."),
        step("s2", "Portfolio baseline", "portfolio_overview", {},
             "Book-level reference.")],
       ["sales", "policies"],
       ["persistency_rate", "lapse_rate", "surrender_rate", "policies_sold"],
       ["lapse_rate", "persistency_rate"],
       ["agent", "anomaly"], "shortlist", "shortlist", REL_CORE)


# =====================================================================
# L. ANOMALY / CONCENTRATION / RISK DETECTION
# =====================================================================

def domain_anomaly():
    ps("Are there unusual concentrations or patterns management should investigate?",
       bi.ANOMALY_CONCENTRATION,
       "One sweep across concentration and outlier detection.",
       bi.TIER_MULTI_STEP,
       ["Are there unusual concentrations or patterns management should investigate?",
        "Are there unusual patterns in the portfolio?",
        "What looks odd in our book?",
        "Show me the anomalies.",
        "What stands out as unusual?"],
       [step("s1", "Sum assured concentration by product", "concentration",
             {"dimension": "product", "value_metric": "total_sum_assured", "top_n": 3},
             "Product dependency."),
        step("s2", "Single-policy exposure", "top_entity_concentration",
             {"column": "sum_assured", "top_n": 10},
             "How much cover sits on the ten largest policies."),
        step("s3", "Single-claim exposure", "top_entity_concentration",
             {"column": "claim_amount", "top_n": 10, "base": "claim"},
             "How much claim spend sits on the ten largest claims."),
        step("s4", "Agent lapse outliers", "outliers",
             {"dimension": "agent", "metric": "lapse_rate", "method": "iqr", "min_n": 10},
             "Distribution-quality outliers."),
        step("s5", "Product loss-ratio outliers", "outliers",
             {"dimension": "product", "metric": "loss_ratio", "method": "iqr", "min_n": 20},
             "Economics outliers."),
        step("s6", "Branch lapse outliers", "outliers",
             {"dimension": "branch", "metric": "lapse_rate", "method": "iqr", "min_n": 25},
             "Operational outliers.")],
       ALL_TABLES,
       ["sum_assured", "claim_amount", "policy_status", "product_name",
        "servicing_agent_id", "branch_name"],
       ["sum_assured_share", "loss_ratio", "lapse_rate"],
       ["anomaly", "concentration", "risk", "attention"],
       "anomaly", "anomaly", REL_CLAIM,
       caveat="Outlier flags are statistical signals, not findings. Each needs "
              "operational review before any conclusion is drawn.")

    ps("Are policies or sum assured unusually concentrated?",
       bi.ANOMALY_CONCENTRATION, "Measure diversification with HHI and top-N share.",
       bi.TIER_MULTI_STEP,
       ["Are policies or sum assured unusually concentrated?",
        "How concentrated is our portfolio?",
        "Are we over-reliant on one product?",
        "Measure our diversification."],
       [step("s1", "Concentration by product", "concentration",
             {"dimension": "product", "value_metric": "total_sum_assured", "top_n": 3},
             "Product concentration with HHI."),
        step("s2", "Concentration by channel", "concentration",
             {"dimension": "channel", "value_metric": "total_sum_assured", "top_n": 2},
             "Distribution concentration."),
        step("s3", "Concentration by zone", "concentration",
             {"dimension": "zone", "value_metric": "total_sum_assured", "top_n": 2},
             "Geographic concentration."),
        step("s4", "Single-policy exposure", "top_entity_concentration",
             {"column": "sum_assured", "top_n": 10},
             "Individual-policy concentration."),
        step("s5", "Concentration by agent", "concentration",
             {"dimension": "agent", "value_metric": "total_sum_assured", "top_n": 10},
             "Key-person concentration.")],
       ALL_TABLES, ["sum_assured", "product_name", "sales_channel", "zone",
                    "servicing_agent_id"],
       ["sum_assured_share", "total_sum_assured"],
       ["concentration", "risk", "portfolio"],
       "concentration", "concentration", REL_CORE)

    ps("Are claims unusually concentrated in particular products or segments?",
       bi.ANOMALY_CONCENTRATION, "Concentration analysis applied to claim spend.",
       bi.TIER_MULTI_STEP,
       ["Are claims unusually concentrated in certain products or segments?",
        "Is our claim spend concentrated?",
        "Do a few claims dominate?",
        "Where does claim spend cluster?"],
       [step("s1", "Claim spend concentration by product", "concentration",
             {"dimension": "product", "value_metric": "total_claim_amount", "top_n": 3},
             "Product concentration of claim spend."),
        step("s2", "Largest individual claims", "top_entity_concentration",
             {"column": "claim_amount", "top_n": 10, "base": "claim"},
             "How much sits on the ten biggest claims."),
        step("s3", "Claim spend by claim type", "multi_metric_table",
             {"dimension": "claim_type",
              "metrics": ["claim_count", "early_claim_rate", "repudiation_rate"],
              "sort_by": "claim_count", "min_n": 1},
             "Which claim types dominate."),
        step("s4", "Loss ratio outliers", "outliers",
             {"dimension": "product", "metric": "loss_ratio", "method": "iqr", "min_n": 20},
             "Products that are statistical outliers on economics.")],
       ["policies", "claims"], ["claim_amount", "claim_type", "product_name"],
       ["total_claim_amount", "loss_ratio"],
       ["anomaly", "concentration", "claims"],
       "concentration", "concentration", REL_CLAIM)

    ps("Are there channels or agents with unusual behaviour?",
       bi.ANOMALY_CONCENTRATION, "Outlier sweep across distribution.",
       bi.TIER_MULTI_STEP,
       ["Are there agents or channels with unusual behaviour?",
        "Does any channel behave oddly?",
        "Which agents are statistical outliers?",
        "Show me distribution anomalies."],
       [step("s1", "Channel lapse against baseline", "compare_to_baseline",
             {"dimension": "channel", "metric": "lapse_rate"}, "Channel deviations."),
        step("s2", "Agent lapse outliers", "outliers",
             {"dimension": "agent", "metric": "lapse_rate", "method": "iqr", "min_n": 10},
             "Agent-level outliers on lapse."),
        step("s3", "Agent case-size outliers", "outliers",
             {"dimension": "agent", "metric": "avg_sum_assured", "method": "zscore",
              "min_n": 10},
             "Agents writing unusual case sizes."),
        step("s4", "Agent surrender outliers", "outliers",
             {"dimension": "agent", "metric": "surrender_rate", "method": "iqr",
              "min_n": 10},
             "Agent-level outliers on surrender.")],
       ["sales", "policies"],
       ["sales_channel", "servicing_agent_id", "policy_status", "sum_assured"],
       ["lapse_rate", "surrender_rate", "avg_sum_assured"],
       ["anomaly", "agent", "channel"], "anomaly", "anomaly", REL_CORE)

    ps("Which segments are statistical or business outliers on persistency?",
       bi.ANOMALY_CONCENTRATION, "Systematic outlier detection on the lapse metric.",
       bi.TIER_MULTI_STEP,
       ["Which areas are statistical outliers?",
        "Which segments are outliers on lapse?",
        "What is statistically unusual about persistency?",
        "Where does lapse deviate abnormally?"],
       [step("s1", "Product outliers", "outliers",
             {"dimension": "product", "metric": "lapse_rate", "method": "iqr", "min_n": 25},
             "Products outside the fence."),
        step("s2", "Channel outliers", "outliers",
             {"dimension": "channel", "metric": "lapse_rate", "method": "zscore",
              "min_n": 25},
             "Channels beyond two standard deviations."),
        step("s3", "Branch outliers", "outliers",
             {"dimension": "branch", "metric": "lapse_rate", "method": "iqr", "min_n": 25},
             "Branches outside the fence."),
        step("s4", "Ranked deviations across all dimensions", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {}, "min_n": 25, "top_k": 10},
             "Everything ranked by size of deviation.")],
       ALL_TABLES, ["policy_status", "product_name", "sales_channel", "branch_name"],
       ["lapse_rate"], ["anomaly", "lapse"], "anomaly", "anomaly", REL_CORE)

    ps("Where are the concentration risks the board should know about?",
       bi.ANOMALY_CONCENTRATION,
       "Board-level concentration summary across every dimension that matters.",
       bi.TIER_MULTI_STEP,
       ["Where are the concentration risks?",
        "What concentration risk do we carry?",
        "Summarise concentration for the board.",
        "What are we over-exposed to?"],
       [step("s1", "Product concentration", "concentration",
             {"dimension": "product", "value_metric": "total_sum_assured", "top_n": 3},
             "Product dependency."),
        step("s2", "Channel concentration", "concentration",
             {"dimension": "channel", "value_metric": "total_annual_premium", "top_n": 2},
             "Distribution dependency on premium."),
        step("s3", "Geographic concentration", "concentration",
             {"dimension": "state", "value_metric": "total_sum_assured", "top_n": 5},
             "Geographic dependency."),
        step("s4", "Customer concentration", "concentration",
             {"dimension": "income_band", "value_metric": "total_annual_premium",
              "top_n": 2},
             "Segment dependency."),
        step("s5", "Single-policy exposure", "top_entity_concentration",
             {"column": "sum_assured", "top_n": 10},
             "Largest individual exposures.")],
       ALL_TABLES, ["sum_assured", "annual_premium", "product_name", "sales_channel",
                    "state", "annual_income"],
       ["sum_assured_share", "premium_share"],
       ["concentration", "risk", "portfolio"],
       "concentration", "concentration", REL_CORE)

    ps("Are there policies with unusual financial characteristics?",
       bi.ANOMALY_CONCENTRATION,
       "Record-level anomaly scan on affordability and cover ratios.",
       bi.TIER_MULTI_STEP,
       ["Are there policies with unusual financial characteristics?",
        "Any policies that look wrong?",
        "Which policies have odd premium-to-income ratios?",
        "Find unusual policies."],
       [step("s1", "Highest premium-to-income policies", "entity_shortlist",
             {"base": "policy",
              "score_components": [{"column": "premium_to_income", "weight": 1.0,
                                    "direction": "high"}],
              "top_n": 15,
              "columns": ["policy_number", "customer_name", "product_name", "sales_channel",
                          "annual_premium", "annual_income", "premium_to_income",
                          "sum_assured", "policy_status", "servicing_agent_id"]},
             "Policies where premium is very large relative to stated income."),
        step("s2", "Highest cover-to-income policies", "entity_shortlist",
             {"base": "policy",
              "score_components": [{"column": "sa_to_income", "weight": 1.0,
                                    "direction": "high"}],
              "top_n": 15,
              "columns": ["policy_number", "customer_name", "product_name",
                          "sum_assured", "annual_income", "sa_to_income",
                          "medical_underwriting_flag", "policy_status"]},
             "Policies with very high cover relative to stated income."),
        step("s3", "Affordability strain and lapse", "compare_to_baseline",
             {"dimension": "premium_to_income_band", "metric": "lapse_rate"},
             "Whether the strained band actually lapses more.")],
       ["policies", "customers"],
       ["annual_premium", "annual_income", "sum_assured", "medical_underwriting_flag"],
       ["avg_premium_to_income", "lapse_rate"],
       ["anomaly", "underwriting", "risk"], "anomaly", "anomaly", REL_CORE,
       caveat="Extreme ratios may be data-quality issues rather than genuine "
              "underwriting problems; each case needs verification.")

    ps("Which product, channel and segment cells look anomalous on attrition?",
       bi.ANOMALY_CONCENTRATION,
       "Two-way cell scan for pockets that behave unlike the rest of the book.",
       bi.TIER_MULTI_STEP,
       ["Which combinations look anomalous?",
        "Are there odd pockets in the portfolio?",
        "Which cells behave unusually?",
        "Find abnormal segments."],
       [step("s1", "Product x channel attrition", "crosstab_metric",
             {"dim_a": "product", "dim_b": "channel", "metric": "attrition_rate",
              "min_n": 15},
             "Worst and best product-channel cells."),
        step("s2", "Zone x product attrition", "crosstab_metric",
             {"dim_a": "zone", "dim_b": "product", "metric": "attrition_rate",
              "min_n": 15},
             "Worst and best zone-product cells."),
        step("s3", "Income band x payment mode attrition", "crosstab_metric",
             {"dim_a": "income_band", "dim_b": "payment_mode",
              "metric": "attrition_rate", "min_n": 15},
             "Worst and best affordability-billing cells."),
        step("s4", "Portfolio baseline", "portfolio_overview", {},
             "The rate every cell is compared with.")],
       P_TABLES, ["product_name", "sales_channel", "zone", "payment_mode",
                  "annual_income", "policy_status"],
       ["attrition_rate"], ["anomaly", "concentration", "lapse"],
       "grid", "grid", REL_CORE)


# =====================================================================
# M. COMPARATIVE / BENCHMARKING
# =====================================================================

def domain_comparative():
    ps("Compare the major sales channels across volume, policy value, lapse, "
       "surrender and retention.",
       bi.COMPARATIVE, "The full multi-metric channel benchmark.", bi.TIER_MULTI_STEP,
       ["Compare the major sales channels across volume, policy value, lapse, surrender and retention.",
        "Compare Agency vs Online vs Broker on volume, value, lapse and retention.",
        "Benchmark our channels.",
        "Side-by-side comparison of sales channels.",
        "How do Agency and Bancassurance compare?"],
       [step("s1", "Channel benchmark table", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["policy_count", "policy_share", "avg_sum_assured",
                          "avg_annual_premium", "premium_share", "lapse_rate",
                          "surrender_rate", "persistency_rate", "loss_ratio"],
              "sort_by": "policy_share"},
             "Every channel on every metric in one table."),
        step("s2", "Retention performance by channel", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False},
             "The retention column of the comparison."),
        step("s3", "Lapse gap to baseline", "compare_to_baseline",
             {"dimension": "channel", "metric": "lapse_rate"},
             "Which differences are real rather than noise.")],
       ALL_TABLES, ["sales_channel", "policy_status", "sum_assured", "annual_premium",
                    "retention_status", "claim_amount"],
       ["policy_share", "lapse_rate", "surrender_rate", "retention_success_rate"],
       ["comparison", "channel", "value", "lapse", "retention"],
       "comparison", "comparison", REL_RET)

    ps("Compare products across risk and performance.",
       bi.COMPARATIVE, "The full multi-metric product benchmark.", bi.TIER_ANALYTICAL,
       ["Compare Whole Life vs Term Life across risk and performance.",
        "Compare our products.",
        "Benchmark products side by side.",
        "How does Endowment compare with ULIP?"],
       [step("s1", "Product benchmark table", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "policy_share", "avg_sum_assured",
                          "avg_annual_premium", "sum_assured_share", "lapse_rate",
                          "surrender_rate", "persistency_rate", "claim_rate",
                          "loss_ratio", "risk_loss_ratio"],
              "sort_by": "policy_share"},
             "Every product on every metric."),
        step("s2", "Lapse gap to baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "lapse_rate"},
             "Which lapse differences are material."),
        step("s3", "Loss ratio gap to baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "loss_ratio"},
             "Which economics differences are material.")],
       ALL_TABLES, ["product_name", "policy_status", "sum_assured", "claim_amount"],
       ["lapse_rate", "loss_ratio", "persistency_rate"],
       ["comparison", "product", "risk"], "comparison", "comparison", REL_CLAIM)

    ps("Compare zones on portfolio health.",
       bi.COMPARATIVE, "Multi-metric zone benchmark.", bi.TIER_ANALYTICAL,
       ["Compare zones on portfolio health.",
        "Benchmark our zones.",
        "Side-by-side zone comparison.",
        "How do North and South compare?"],
       [step("s1", "Zone benchmark table", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["policy_count", "policy_share", "sum_assured_share",
                          "avg_sum_assured", "lapse_rate", "surrender_rate",
                          "persistency_rate", "loss_ratio"],
              "sort_by": "policy_share"},
             "Every zone on every metric."),
        step("s2", "Persistency gap to baseline", "compare_to_baseline",
             {"dimension": "zone", "metric": "persistency_rate"},
             "Which zones are genuinely ahead or behind."),
        step("s3", "Retention by zone", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False},
             "The retention column of the comparison.")],
       ALL_TABLES, ["zone", "policy_status", "sum_assured", "claim_amount",
                    "retention_status"],
       ["lapse_rate", "persistency_rate", "loss_ratio", "retention_success_rate"],
       ["comparison", "zone"], "comparison", "comparison", REL_RET)

    ps("Compare smoker and non-smoker customers across policy value and risk.",
       bi.COMPARATIVE, "Underwriting-class benchmark.", bi.TIER_ANALYTICAL,
       ["Compare smoker vs non-smoker customers across policy value and risk.",
        "Benchmark smokers against non-smokers.",
        "How do smokers differ?",
        "Smoker versus non-smoker comparison."],
       [step("s1", "Smoker benchmark table", "multi_metric_table",
             {"dimension": "smoker",
              "metrics": ["policy_count", "avg_sum_assured", "avg_annual_premium",
                          "avg_customer_age", "avg_customer_income", "lapse_rate",
                          "surrender_rate", "claim_rate", "risk_claim_rate",
                          "loss_ratio", "risk_loss_ratio", "medical_underwriting_share"],
              "sort_by": "risk_claim_rate"},
             "Both classes on every metric."),
        step("s2", "Smoker segment vs portfolio", "segment_profile",
             {"filters": {"smoker": "Smoker"}},
             "Explicit gaps against the book.")],
       ALL_TABLES, ["is_smoker", "sum_assured", "annual_premium", "claim_amount",
                    "policy_status"],
       ["risk_claim_rate", "risk_loss_ratio", "lapse_rate"],
       ["comparison", "customer", "underwriting"], "comparison", "comparison", REL_CLAIM,
       caveat="126 of 708 customers are smokers, so claim-based differences rest on "
              "small counts.")

    ps("Compare payment modes on persistency and value.",
       bi.COMPARATIVE, "Billing-frequency benchmark.", bi.TIER_ANALYTICAL,
       ["Compare payment modes on persistency.",
        "Benchmark monthly against annual payers.",
        "How do payment modes compare?",
        "Side-by-side payment mode comparison."],
       [step("s1", "Payment mode benchmark table", "multi_metric_table",
             {"dimension": "payment_mode",
              "metrics": ["policy_count", "policy_share", "avg_annual_premium",
                          "avg_customer_income", "avg_premium_to_income",
                          "lapse_rate", "surrender_rate", "persistency_rate"],
              "sort_by": "lapse_rate"},
             "Every mode on every metric."),
        step("s2", "Lapse gap to baseline", "compare_to_baseline",
             {"dimension": "payment_mode", "metric": "lapse_rate"},
             "Which differences are material.")],
       P_TABLES, ["payment_mode", "policy_status", "annual_premium", "annual_income"],
       ["lapse_rate", "persistency_rate", "avg_premium_to_income"],
       ["comparison", "payment", "lapse"], "comparison", "comparison", REL_CORE)

    ps("Compare products on claims economics.",
       bi.COMPARATIVE, "Economics-only product benchmark.", bi.TIER_ANALYTICAL,
       ["Compare products on claims economics.",
        "Benchmark product loss ratios.",
        "Which products compare best on economics?",
        "Product economics comparison."],
       [step("s1", "Economics benchmark table", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "total_premium_collected", "total_claim_amount",
                          "loss_ratio", "risk_loss_ratio", "claim_rate",
                          "risk_claim_rate", "avg_claim_amount"],
              "sort_by": "loss_ratio"},
             "Premium in, claims out, both ratios."),
        step("s2", "Claim mix by product", "crosstab_metric",
             {"dim_a": "product", "dim_b": "claim_type", "metric": "claim_count",
              "min_n": 1},
             "Why a product's ratio is what it is."),
        step("s3", "Loss ratio gap to baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "loss_ratio"},
             "Which differences are material.")],
       ["policies", "claims"], ["product_name", "claim_amount", "claim_type",
                                "total_premium_paid"],
       ["loss_ratio", "risk_loss_ratio"],
       ["comparison", "economics", "product"], "economics", "economics", REL_CLAIM)

    ps("Compare customer income bands across value and risk.",
       bi.COMPARATIVE, "Segment benchmark on income.", bi.TIER_ANALYTICAL,
       ["Compare income segments.",
        "Benchmark high-income against low-income customers.",
        "How do income bands compare on risk?",
        "Income band comparison."],
       [step("s1", "Income band benchmark table", "multi_metric_table",
             {"dimension": "income_band",
              "metrics": ["policy_count", "policy_share", "premium_share",
                          "avg_sum_assured", "avg_annual_premium",
                          "avg_premium_to_income", "lapse_rate", "surrender_rate",
                          "claim_rate", "loss_ratio"],
              "sort_by": "income_band", "ascending": True},
             "Every band on every metric."),
        step("s2", "Lapse gap to baseline", "compare_to_baseline",
             {"dimension": "income_band", "metric": "lapse_rate"},
             "Which bands are materially different.")],
       ALL_TABLES, ["annual_income", "sum_assured", "annual_premium", "policy_status",
                    "claim_amount"],
       ["lapse_rate", "premium_share", "loss_ratio"],
       ["comparison", "customer", "value"], "comparison", "comparison", REL_CLAIM)

    ps("Compare age bands across value, persistency and claims.",
       bi.COMPARATIVE, "Segment benchmark on life stage.", bi.TIER_ANALYTICAL,
       ["Compare age groups.",
        "How do younger and older customers differ?",
        "Benchmark age bands.",
        "Age band comparison."],
       [step("s1", "Age band benchmark table", "multi_metric_table",
             {"dimension": "age_band",
              "metrics": ["policy_count", "policy_share", "avg_sum_assured",
                          "avg_annual_premium", "avg_customer_income", "lapse_rate",
                          "surrender_rate", "claim_rate", "risk_claim_rate",
                          "loss_ratio"],
              "sort_by": "age_band", "ascending": True},
             "Every band on every metric."),
        step("s2", "Risk-claim gap to baseline", "compare_to_baseline",
             {"dimension": "age_band", "metric": "risk_claim_rate"},
             "Which bands genuinely claim more.")],
       ALL_TABLES, ["age", "sum_assured", "annual_premium", "policy_status",
                    "claim_amount"],
       ["lapse_rate", "risk_claim_rate", "loss_ratio"],
       ["comparison", "customer", "claims"], "comparison", "comparison", REL_CLAIM)

    ps("Compare product categories across the full scorecard.",
       bi.COMPARATIVE, "Category-level benchmark.", bi.TIER_ANALYTICAL,
       ["Compare product categories.",
        "Benchmark protection against savings.",
        "How do investment products compare with savings products?",
        "Product category comparison."],
       [step("s1", "Category benchmark table", "multi_metric_table",
             {"dimension": "product_category",
              "metrics": ["policy_count", "policy_share", "sum_assured_share",
                          "avg_sum_assured", "avg_annual_premium", "lapse_rate",
                          "surrender_rate", "persistency_rate", "loss_ratio",
                          "risk_loss_ratio"],
              "sort_by": "policy_share"},
             "Every category on every metric."),
        step("s2", "Persistency gap to baseline", "compare_to_baseline",
             {"dimension": "product_category", "metric": "persistency_rate"},
             "Which categories are materially different.")],
       ALL_TABLES, ["product_category", "policy_status", "sum_assured", "claim_amount"],
       ["lapse_rate", "persistency_rate", "loss_ratio"],
       ["comparison", "product"], "comparison", "comparison", REL_CLAIM)

    ps("Compare retention contact channels across effectiveness and cost.",
       bi.COMPARATIVE, "Retention-channel benchmark.", bi.TIER_ANALYTICAL,
       ["Compare retention channels.",
        "Benchmark SMS against phone for retention.",
        "Which retention channel compares best?",
        "Retention channel comparison."],
       [step("s1", "Retention channel benchmark", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate",
                          "retention_loss_to_lapse_rate", "avg_retention_incentive",
                          "total_retention_incentive", "incentive_per_retained_policy"],
              "sort_by": "retention_success_rate", "ascending": False},
             "Effectiveness and cost side by side."),
        step("s2", "Success gap to baseline", "compare_to_baseline",
             {"dimension": "contact_channel", "metric": "retention_success_rate"},
             "Which channels genuinely beat the average.")],
       ["retention", "policies"],
       ["contact_channel", "retention_status", "agent_incentive_amount"],
       ["retention_success_rate", "incentive_per_retained_policy"],
       ["comparison", "retention", "channel"], "comparison", "comparison", REL_RET)


# =====================================================================
# N. ROOT-CAUSE / DIAGNOSTIC
# =====================================================================

def domain_root_cause():
    ps("Why is a specific product performing poorly?",
       bi.ROOT_CAUSE,
       "Full diagnostic decomposition of one product against the book.",
       bi.TIER_MULTI_STEP,
       ["Why is Whole Life performing poorly?",
        "Why is this product underperforming?",
        "Explain why Annuity is doing badly.",
        "What is wrong with ULIP?",
        "Why does Money Back underperform?"],
       [step("s1", "Confirm the gap", "segment_profile",
             {"filters": {"product": "$product"}},
             "Establish on which metrics the product is actually worse."),
        step("s2", "Product vs peers on lapse", "compare_to_baseline",
             {"dimension": "product", "metric": "lapse_rate"},
             "Rank the product against every other product."),
        step("s3", "Product vs peers on economics", "compare_to_baseline",
             {"dimension": "product", "metric": "loss_ratio"},
             "The economics half of the picture."),
        step("s4", "Strongest internal deviations", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {"product": "$product"},
              "min_n": 10, "top_k": 8},
             "Which segments inside the product generate the problem."),
        step("s5", "Channel split inside the product", "multi_metric_table",
             {"dimension": "channel", "metrics": ["policy_count", "lapse_rate",
                                                  "surrender_rate", "avg_annual_premium"],
              "filters": {"product": "$product"}, "sort_by": "lapse_rate", "min_n": 8},
             "Distribution contribution."),
        step("s6", "Retention effectiveness on the product", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "filters": {"product": "$product"},
              "sort_by": "retention_success_rate", "ascending": False, "min_n": 5},
             "Whether the losses were salvageable.")],
       ALL_TABLES,
       ["product_name", "policy_status", "sales_channel", "claim_amount",
        "annual_premium", "retention_status"],
       ["lapse_rate", "loss_ratio", "persistency_rate", "retention_success_rate"],
       ["diagnostic", "product", "lapse", "economics"],
       "diagnostic", "diagnostic", REL_RET,
       parameters={"product": {"dimension": "product", "default": "Whole Life",
                               "description": "Product to diagnose"}},
       caveat="This decomposition identifies where the underperformance sits. The "
              "dataset records no reason codes for lapse, so nothing here "
              "establishes cause.")

    ps("Why is lapse high in a specific customer segment?",
       bi.ROOT_CAUSE, "Diagnose one customer segment's lapse rate.",
       bi.TIER_MULTI_STEP,
       ["Why is lapse high in the low income segment?",
        "Why do young customers lapse more?",
        "Explain lapse in this segment.",
        "What is driving lapse among smokers?"],
       [step("s1", "Segment vs portfolio profile", "segment_profile",
             {"filters": "$segment_filters"},
             "Establish how the segment differs on every metric."),
        step("s2", "Strongest deviations inside the segment", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": "$segment_filters",
              "min_n": 12, "top_k": 8},
             "What varies inside the segment."),
        step("s3", "Product mix inside the segment", "multi_metric_table",
             {"dimension": "product", "metrics": ["policy_count", "lapse_rate"],
              "filters": "$segment_filters", "sort_by": "lapse_rate", "min_n": 8},
             "Whether the segment buys riskier products."),
        step("s4", "Payment mode mix inside the segment", "multi_metric_table",
             {"dimension": "payment_mode", "metrics": ["policy_count", "lapse_rate"],
              "filters": "$segment_filters", "sort_by": "lapse_rate", "min_n": 8},
             "Whether it is really a billing effect.")],
       ALL_TABLES, ["annual_income", "age", "is_smoker", "product_name",
                    "payment_mode", "policy_status"],
       ["lapse_rate", "avg_premium_to_income"],
       ["diagnostic", "lapse", "customer"], "diagnostic", "diagnostic", REL_CORE,
       parameters={"segment_filters": {"free_filters": True,
                                       "default": {"income_band": "<5L"},
                                       "description": "Segment to diagnose"}},
       caveat="Segment composition differences are associations. The dataset cannot "
              "separate a segment effect from the product and billing mix inside it.")

    ps("Why does a specific channel have poor retention?",
       bi.ROOT_CAUSE, "Diagnose one channel's persistency and save rate.",
       bi.TIER_MULTI_STEP,
       ["Why does the Online channel have poor retention?",
        "Why does this channel lose policies?",
        "Explain poor persistency in Bancassurance.",
        "What is wrong with the Broker channel?"],
       [step("s1", "Channel vs portfolio profile", "segment_profile",
             {"filters": {"channel": "$channel"}},
             "Establish where the channel is actually worse."),
        step("s2", "Channel vs peers on lapse", "compare_to_baseline",
             {"dimension": "channel", "metric": "lapse_rate"},
             "Rank against every other channel."),
        step("s3", "Strongest internal deviations", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {"channel": "$channel"},
              "min_n": 10, "top_k": 8},
             "What varies inside the channel."),
        step("s4", "Product mix inside the channel", "multi_metric_table",
             {"dimension": "product", "metrics": ["policy_count", "lapse_rate",
                                                  "avg_annual_premium"],
              "filters": {"channel": "$channel"}, "sort_by": "lapse_rate", "min_n": 8},
             "Whether the channel simply sells riskier products."),
        step("s5", "Retention effectiveness on the channel", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "filters": {"channel": "$channel"},
              "sort_by": "retention_success_rate", "ascending": False, "min_n": 5},
             "Whether outreach works on this channel's customers.")],
       ALL_TABLES, ["sales_channel", "product_name", "policy_status", "retention_status"],
       ["lapse_rate", "persistency_rate", "retention_success_rate"],
       ["diagnostic", "channel", "retention"], "diagnostic", "diagnostic", REL_RET,
       parameters={"channel": {"dimension": "channel", "default": "Online",
                               "description": "Channel to diagnose"}})

    ps("What factors are associated with a high surrender rate?",
       bi.ROOT_CAUSE, "Diagnostic scan on the surrender metric.", bi.TIER_MULTI_STEP,
       ["What factors are associated with a high surrender rate?",
        "What explains our surrender rate?",
        "Which factors relate to surrender?",
        "Diagnose surrender."],
       [step("s1", "Portfolio surrender baseline", "portfolio_overview", {},
             "The rate every segment is measured against."),
        step("s2", "Strongest associations across all dimensions", "driver_scan",
             {"metric": "surrender_rate", "focus_filters": {}, "min_n": 40, "top_k": 8},
             "Rank every dimension by deviation."),
        step("s3", "Stated surrender reasons", "multi_metric_table",
             {"dimension": "surrender_reason",
              "metrics": ["policy_count", "avg_sum_assured", "avg_annual_premium"],
              "sort_by": "policy_count", "min_n": 1},
             "What customers actually said."),
        step("s4", "Surrendered-policy profile", "segment_profile",
             {"filters": {"policy_status": "Surrendered"}},
             "Structural contrast against the book.")],
       ALL_TABLES, ["policy_status", "surrender_reason", "product_name", "sum_assured"],
       ["surrender_rate", "avg_sum_assured"],
       ["diagnostic", "surrender"], "driver_analysis", "driver_analysis", REL_SURR,
       caveat="40 surrenders total. The stated reason field is the only direct "
              "evidence of motive; everything else is association.")

    ps("What appears to distinguish high-performing groups from low-performing ones?",
       bi.ROOT_CAUSE,
       "Generic best-versus-worst contrast on any grouping the user names.",
       bi.TIER_MULTI_STEP,
       ["What appears to distinguish high-performing and low-performing groups?",
        "What separates our winners from our losers?",
        "What do the best performers have in common?",
        "Why do some groups outperform?"],
       [step("s1", "Product scorecard, best to worst", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "persistency_rate", "weight": 0.4, "direction": "high"},
                             {"metric": "lapse_rate", "weight": 0.3, "direction": "low"},
                             {"metric": "loss_ratio", "weight": 0.3, "direction": "low"}]},
             "Split products into strong and weak."),
        step("s2", "Structural characteristics by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["avg_sum_assured", "avg_annual_premium", "avg_customer_income",
                          "avg_customer_age", "avg_premium_to_income",
                          "rider_attachment_rate", "medical_underwriting_share"],
              "sort_by": "avg_premium_to_income"},
             "What differs structurally between them."),
        step("s3", "Channel scorecard, best to worst", "composite_score",
             {"dimension": "channel",
              "components": [{"metric": "persistency_rate", "weight": 0.5, "direction": "high"},
                             {"metric": "lapse_rate", "weight": 0.5, "direction": "low"}]},
             "The same split for channels."),
        step("s4", "Strongest deviations overall", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {}, "min_n": 25, "top_k": 8},
             "Ranked list of what separates good from bad on persistency.")],
       ALL_TABLES, ["product_name", "sales_channel", "policy_status", "annual_premium",
                    "annual_income", "rider_count"],
       ["persistency_rate", "lapse_rate", "loss_ratio", "avg_premium_to_income"],
       ["diagnostic", "comparison"], "diagnostic", "diagnostic", REL_CLAIM)

    ps("Why does a specific zone underperform?",
       bi.ROOT_CAUSE, "Diagnose one zone.", bi.TIER_MULTI_STEP,
       ["Why is the East zone underperforming?",
        "Why does this zone have high lapse?",
        "Explain the West zone result.",
        "What is wrong in the Central zone?"],
       [step("s1", "Zone vs portfolio profile", "segment_profile",
             {"filters": {"zone": "$zone"}}, "Where the zone is actually worse."),
        step("s2", "Zone vs peers on lapse", "compare_to_baseline",
             {"dimension": "zone", "metric": "lapse_rate"}, "Rank against other zones."),
        step("s3", "Strongest internal deviations", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {"zone": "$zone"},
              "min_n": 10, "top_k": 8},
             "What varies inside the zone."),
        step("s4", "Branch detail inside the zone", "multi_metric_table",
             {"dimension": "branch", "metrics": ["policy_count", "lapse_rate",
                                                 "persistency_rate"],
              "filters": {"zone": "$zone"}, "sort_by": "lapse_rate", "min_n": 15},
             "Whether one or two branches carry the result."),
        step("s5", "Product mix inside the zone", "multi_metric_table",
             {"dimension": "product", "metrics": ["policy_count", "lapse_rate"],
              "filters": {"zone": "$zone"}, "sort_by": "lapse_rate", "min_n": 8},
             "Whether the zone simply sells riskier products.")],
       ALL_TABLES, ["zone", "branch_name", "product_name", "policy_status"],
       ["lapse_rate", "persistency_rate"],
       ["diagnostic", "zone", "lapse"], "diagnostic", "diagnostic", REL_CORE,
       parameters={"zone": {"dimension": "zone", "default": "East",
                            "description": "Zone to diagnose"}})

    ps("What is driving the portfolio's overall lapse rate?",
       bi.ROOT_CAUSE,
       "Decompose the headline lapse number into its largest contributors.",
       bi.TIER_MULTI_STEP,
       ["What is driving our overall lapse rate?",
        "Why is portfolio lapse where it is?",
        "Decompose our lapse rate.",
        "Where do our lapses actually come from?"],
       [step("s1", "Portfolio lapse baseline", "portfolio_overview", {},
             "The number being decomposed."),
        step("s2", "Volume of lapses by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "policy_share", "lapse_rate"],
              "sort_by": "policy_share"},
             "Big products move the average more than high-rate small ones."),
        step("s3", "Strongest rate deviations", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {}, "min_n": 25, "top_k": 10},
             "Where the rate is highest, regardless of size."),
        step("s4", "Lapse by payment mode", "compare_to_baseline",
             {"dimension": "payment_mode", "metric": "lapse_rate"},
             "The most operationally actionable single factor.")],
       ALL_TABLES, ["policy_status", "product_name", "payment_mode", "sales_channel"],
       ["lapse_rate", "policy_share"],
       ["diagnostic", "lapse", "portfolio"],
       "driver_analysis", "driver_analysis", REL_CORE)

    ps("Why does a specific segment show poor claims economics?",
       bi.ROOT_CAUSE, "Diagnose one segment's loss ratio.", bi.TIER_MULTI_STEP,
       ["Why does Term Life have a high loss ratio?",
        "Why are the economics bad in this segment?",
        "Explain the loss ratio on Annuity.",
        "What is behind the claims cost in this group?"],
       [step("s1", "Segment vs portfolio profile", "segment_profile",
             {"filters": "$segment_filters"},
             "Where the segment differs, including on claims."),
        step("s2", "Claim-type mix inside the segment", "multi_metric_table",
             {"dimension": "claim_type",
              "metrics": ["claim_count", "early_claim_rate", "repudiation_rate"],
              "filters": "$segment_filters", "sort_by": "claim_count", "min_n": 1},
             "Distinguish contractual payouts from underwriting losses."),
        step("s3", "Loss ratio against peers", "compare_to_baseline",
             {"dimension": "product", "metric": "loss_ratio"},
             "Peer context."),
        step("s4", "Risk-only loss ratio against peers", "compare_to_baseline",
             {"dimension": "product", "metric": "risk_loss_ratio"},
             "The same comparison without maturities and surrenders.")],
       ["policies", "claims", "customers"],
       ["product_name", "claim_type", "claim_amount", "total_premium_paid"],
       ["loss_ratio", "risk_loss_ratio", "claim_rate"],
       ["diagnostic", "economics", "claims"], "diagnostic", "diagnostic", REL_CLAIM,
       parameters={"segment_filters": {"free_filters": True,
                                       "default": {"product": "Term Life"},
                                       "description": "Segment to diagnose"}},
       caveat="A high all-claims loss ratio on a maturity-paying product is a "
              "contractual outflow, not a loss. Read the risk-only ratio too.")

    ps("Why is retention failing for a specific group?",
       bi.ROOT_CAUSE, "Diagnose a low save rate.", bi.TIER_MULTI_STEP,
       ["Why is retention failing for this group?",
        "Why can't we save these policies?",
        "Why is the save rate low on Whole Life?",
        "Explain poor retention in the East zone."],
       [step("s1", "Save rate vs baseline by contact channel", "compare_to_baseline",
             {"dimension": "contact_channel", "metric": "retention_success_rate"},
             "The overall retention picture first."),
        step("s2", "Save rate inside the group by channel", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate",
                          "avg_retention_incentive"],
              "filters": "$segment_filters",
              "sort_by": "retention_success_rate", "ascending": False, "min_n": 5},
             "Whether the group was reached the right way."),
        step("s3", "Offer effectiveness inside the group", "multi_metric_table",
             {"dimension": "offer",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "filters": "$segment_filters",
              "sort_by": "retention_success_rate", "ascending": False, "min_n": 5},
             "Whether the offer was the right one."),
        step("s4", "Group profile vs portfolio", "segment_profile",
             {"filters": "$segment_filters"},
             "Whether the group was harder to save to begin with.")],
       ["retention", "policies", "customers"],
       ["retention_status", "contact_channel", "offers_extended", "product_name", "zone"],
       ["retention_success_rate"],
       ["diagnostic", "retention"], "diagnostic", "diagnostic", REL_RET,
       parameters={"segment_filters": {"free_filters": True,
                                       "default": {"product": "Whole Life"},
                                       "description": "Group to diagnose"}},
       caveat="Retention outreach was not randomly assigned, so a low save rate may "
              "reflect which cases were selected for which treatment.")

    ps("Why do policies on a specific payment mode lapse more?",
       bi.ROOT_CAUSE, "Diagnose a billing-frequency effect.", bi.TIER_MULTI_STEP,
       ["Why do monthly-pay policies lapse more?",
        "Why is lapse high on quarterly payers?",
        "Explain the payment mode lapse gap.",
        "Is the monthly lapse gap real?"],
       [step("s1", "Lapse by payment mode", "compare_to_baseline",
             {"dimension": "payment_mode", "metric": "lapse_rate"},
             "Confirm and size the gap."),
        step("s2", "Who chooses each mode", "multi_metric_table",
             {"dimension": "payment_mode",
              "metrics": ["policy_count", "avg_customer_income", "avg_annual_premium",
                          "avg_premium_to_income", "avg_customer_age", "avg_sum_assured"],
              "sort_by": "avg_customer_income"},
             "Whether the modes attract different customers."),
        step("s3", "Mode x product grid", "crosstab_metric",
             {"dim_a": "payment_mode", "dim_b": "product", "metric": "lapse_rate",
              "min_n": 20},
             "Whether the gap survives inside individual products."),
        step("s4", "Mode x income band grid", "crosstab_metric",
             {"dim_a": "payment_mode", "dim_b": "income_band", "metric": "lapse_rate",
              "min_n": 20},
             "Whether the gap survives inside income bands.")],
       P_TABLES, ["payment_mode", "policy_status", "annual_income", "product_name"],
       ["lapse_rate", "avg_premium_to_income"],
       ["diagnostic", "payment", "lapse"], "diagnostic", "diagnostic", REL_CORE,
       caveat="Cross-tabulation can show that a gap persists inside sub-groups, but "
              "it is not a controlled analysis and cannot isolate the billing effect.")


# =====================================================================
# O. ACTIONABLE TARGETING
# =====================================================================

def domain_targeting():
    ps("Which individual policies represent the largest value at risk right now?",
       bi.CUSTOMER_TARGETING, "Named, ranked list of live policies worth protecting.",
       bi.TIER_MULTI_STEP,
       ["Which policies represent the largest value at risk?",
        "Which live policies should we protect?",
        "Give me the top value-at-risk policies.",
        "Which in-force policies matter most?"],
       [step("s1", "Ranked in-force policies", "entity_shortlist",
             {"base": "policy", "filters": {"policy_status": "In-Force"},
              "score_components": [{"column": "annual_premium", "weight": 0.4, "direction": "high"},
                                   {"column": "sum_assured", "weight": 0.3, "direction": "high"},
                                   {"column": "premium_to_income", "weight": 0.3, "direction": "high"}],
              "top_n": 25,
              "columns": ["policy_number", "customer_name", "customer_id", "product_name",
                          "sales_channel", "zone", "payment_mode", "annual_premium",
                          "sum_assured", "annual_income", "premium_to_income",
                          "servicing_agent_id"]},
             "Rank by premium and cover at stake plus affordability strain."),
        step("s2", "Portfolio baseline", "portfolio_overview", {},
             "Context for how much of the book this represents.")],
       ["policies", "customers"],
       ["policy_status", "annual_premium", "sum_assured", "annual_income"],
       ["avg_annual_premium", "avg_sum_assured"],
       ["customer", "value", "risk", "attention"], "shortlist", "shortlist", REL_CORE)

    ps("Which customers have already lost policies and still hold live business?",
       bi.CUSTOMER_TARGETING,
       "Customers showing attrition behaviour who still have something to lose.",
       bi.TIER_MULTI_STEP,
       ["Which customers have already lapsed once and still hold policies?",
        "Who has partial attrition?",
        "Which customers are drifting away?",
        "Show customers with mixed policy outcomes."],
       [step("s1", "Customers with attrition and live business", "entity_shortlist",
             {"base": "customer",
              "filters": {"has_attrition": True, "inforce_policies": {"min": 1}},
              "score_components": [{"column": "value_score", "weight": 0.5, "direction": "high"},
                                   {"column": "attrition_ratio", "weight": 0.5, "direction": "high"}],
              "top_n": 25,
              "columns": ["customer_id", "full_name", "age", "annual_income",
                          "policy_count", "inforce_policies", "lapsed_policies",
                          "surrendered_policies", "attrition_ratio",
                          "total_annual_premium", "total_sum_assured", "product_name",
                          "sales_channel"]},
             "Rank by value still at stake and how much has already gone."),
        step("s2", "Most effective outreach channel", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False},
             "How to approach them.")],
       ["policies", "customers", "retention"],
       ["policy_status", "customer_id", "annual_premium", "retention_status"],
       ["retention_success_rate"],
       ["customer", "retention", "attention"], "shortlist", "retention_shortlist", REL_RET)

    ps("Which customers look underinsured relative to their income?",
       bi.CUSTOMER_TARGETING, "Cross-sell targeting based on cover-to-income.",
       bi.TIER_MULTI_STEP,
       ["Which customers are underinsured?",
        "Who should we cross-sell to?",
        "Which customers have too little cover for their income?",
        "Give me a cross-sell target list."],
       [step("s1", "Cover-to-income by income band", "multi_metric_table",
             {"dimension": "income_band",
              "metrics": ["policy_count", "avg_sum_assured", "avg_customer_income",
                          "avg_annual_premium"],
              "sort_by": "income_band", "ascending": True},
             "How much cover each band actually holds."),
        step("s2", "Lowest cover-to-income live policies", "entity_shortlist",
             {"base": "policy", "filters": {"policy_status": "In-Force"},
              "score_components": [{"column": "sa_to_income", "weight": 0.6, "direction": "low"},
                                   {"column": "annual_income", "weight": 0.4, "direction": "high"}],
              "top_n": 25,
              "columns": ["policy_number", "customer_name", "customer_id", "age",
                          "annual_income", "sum_assured", "sa_to_income",
                          "product_name", "rider_count", "sales_channel"]},
             "High-income customers holding relatively little cover.")],
       ["policies", "customers"],
       ["annual_income", "sum_assured", "policy_status", "rider_count"],
       ["avg_sum_assured", "avg_customer_income"],
       ["customer", "value", "growth", "recommendation"],
       "shortlist", "shortlist", REL_CORE,
       caveat="'Underinsured' here means low cover relative to income within this "
              "book. The dataset holds no information about cover the customer may "
              "have elsewhere.")

    ps("Which live policies most resemble the profile of policies that lapsed?",
       bi.CUSTOMER_TARGETING,
       "Profile-similarity targeting built from the observed lapse profile.",
       bi.TIER_MULTI_STEP,
       ["Which live policies look like ones that lapsed?",
        "Who is most likely to lapse next?",
        "Give me a lapse-risk target list.",
        "Which policies match the lapse profile?"],
       [step("s1", "Lapsed-policy profile", "segment_profile",
             {"filters": {"policy_status": "Lapsed"}},
             "Establish what a lapse looks like in this book."),
        step("s2", "Strongest lapse associations", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {}, "min_n": 25, "top_k": 8},
             "Which characteristics carry the strongest association."),
        step("s3", "Live policies matching the strained profile", "entity_shortlist",
             {"base": "policy", "filters": {"policy_status": "In-Force"},
              "score_components": [{"column": "premium_to_income", "weight": 0.5,
                                    "direction": "high"},
                                   {"column": "annual_premium", "weight": 0.3,
                                    "direction": "high"},
                                   {"column": "annual_income", "weight": 0.2,
                                    "direction": "low"}],
              "top_n": 25,
              "columns": ["policy_number", "customer_name", "customer_id", "product_name",
                          "sales_channel", "payment_mode", "annual_premium",
                          "annual_income", "premium_to_income", "sum_assured", "zone"]},
             "Rank live policies on the strain characteristics associated with lapse.")],
       ["policies", "customers"],
       ["policy_status", "annual_premium", "annual_income", "payment_mode"],
       ["lapse_rate", "avg_premium_to_income"],
       ["customer", "lapse", "attention", "recommendation"],
       "shortlist", "shortlist", REL_CORE,
       caveat="This ranks by characteristics associated with lapse in the historical "
              "data. It is not a trained or calibrated propensity model, and it "
              "should not be presented as a probability of lapsing.")

    ps("Which surrendered or lapsed customers are the best win-back candidates?",
       bi.CUSTOMER_TARGETING, "Reactivation targeting from lost business.",
       bi.TIER_MULTI_STEP,
       ["Which lapsed customers should we try to win back?",
        "Who are our best reactivation targets?",
        "Give me a win-back list.",
        "Which lost customers were most valuable?"],
       [step("s1", "Highest-value lost policies", "entity_shortlist",
             {"base": "policy", "filters": {"policy_status": ["Lapsed", "Surrendered"]},
              "score_components": [{"column": "annual_premium", "weight": 0.4, "direction": "high"},
                                   {"column": "sum_assured", "weight": 0.3, "direction": "high"},
                                   {"column": "total_premium_paid", "weight": 0.3, "direction": "high"}],
              "top_n": 25,
              "columns": ["policy_number", "customer_name", "customer_id", "product_name",
                          "policy_status", "sales_channel", "zone", "annual_premium",
                          "sum_assured", "total_premium_paid", "annual_income",
                          "retention_status", "contact_channel"]},
             "Rank lost business by what it was worth."),
        step("s2", "Which outreach channel saves best", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False},
             "How to make the approach.")],
       ["policies", "customers", "retention"],
       ["policy_status", "annual_premium", "total_premium_paid", "retention_status"],
       ["retention_success_rate"],
       ["customer", "retention", "value"], "shortlist", "retention_shortlist", REL_RET)

    ps("Which branches or agents should receive additional retention support?",
       bi.CUSTOMER_TARGETING, "Operational resourcing target list.", bi.TIER_MULTI_STEP,
       ["Which branches need retention support?",
        "Where should we add retention resource?",
        "Which agents need retention help?",
        "Where should the retention team be deployed?"],
       [step("s1", "Branches ranked by lapse and volume", "multi_metric_table",
             {"dimension": "branch",
              "metrics": ["policy_count", "lapse_rate", "attrition_rate",
                          "avg_annual_premium"],
              "sort_by": "lapse_rate", "min_n": 25},
             "Where losses are largest."),
        step("s2", "Retention success by branch", "multi_metric_table",
             {"dimension": "branch",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": True, "min_n": 15},
             "Where the existing effort is least effective."),
        step("s3", "Agents needing support", "entity_shortlist",
             {"base": "agent", "filters": {"policies_serviced": {"min": 8}},
              "score_components": [{"column": "observed_lapse_rate", "weight": 0.6,
                                    "direction": "high"},
                                   {"column": "policies_serviced", "weight": 0.4,
                                    "direction": "high"}],
              "top_n": 15,
              "columns": ["servicing_agent_id", "full_name", "branch_id", "zone",
                          "policies_serviced", "observed_lapse_rate",
                          "observed_persistency_rate", "target_achievement_pct"]},
             "Named agents whose books are losing most.")],
       ALL_TABLES, ["branch_name", "servicing_agent_id", "policy_status",
                    "retention_status"],
       ["lapse_rate", "retention_success_rate"],
       ["agent", "zone", "retention", "attention"],
       "shortlist", "shortlist", REL_RET)
