"""
build_business_ps.py  (part 1 of the library: helpers + domains A-D)
===================================================================
Generates `business_problem_statements.json` - the business-oriented Problem
Statement library.

A business PS is NOT an SQL template. It carries an *executable analytical
plan*: an ordered list of steps, each naming an operation from
`analytics_core.OPERATIONS` plus its parameters. The planner binds runtime
values (a product name mentioned in the question, a zone, a channel) into the
`$placeholder` slots and executes the steps deterministically.

Run:  python3 build_business_ps.py
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional, Sequence

import business_intents as bi

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.join(BASE_DIR, "business_problem_statements.json")

RECORDS: List[Dict[str, Any]] = []
_COUNTER = {"n": 0}


def step(sid: str, title: str, op: str, params: Dict[str, Any], purpose: str) -> Dict[str, Any]:
    return {"id": sid, "title": title, "op": op, "params": params, "purpose": purpose}


def ps(statement: str,
       intent: str,
       objective: str,
       tier: str,
       queries: Sequence[str],
       steps: Sequence[Dict[str, Any]],
       tables: Sequence[str],
       columns: Sequence[str],
       metrics: Sequence[str],
       concepts: Sequence[str],
       answer_type: str,
       template: str,
       relationships: Optional[Sequence[str]] = None,
       parameters: Optional[Dict[str, Any]] = None,
       caveat: Optional[str] = None) -> Dict[str, Any]:
    _COUNTER["n"] += 1
    rec = {
        "problem_id": f"BPS-{_COUNTER['n']:03d}",
        "problem_statement": statement,
        "intent_type": f"Business/{intent}",
        "business_intent": intent,
        "business_domain": bi.BUSINESS_INTENTS[intent]["label"],
        "business_objective": objective,
        "analysis_tier": tier,
        "example_queries": list(queries),
        "relevant_tables": list(tables),
        "relevant_columns": list(columns),
        "required_operations": sorted({s["op"] for s in steps}),
        "required_metrics": list(metrics),
        "relationships": list(relationships or []),
        "concepts": list(concepts),
        "analytical_steps": list(steps),
        "expected_answer_type": answer_type,
        "answer_template": template,
        "parameters": parameters or {},
        "caveat": caveat,
        # backward-compatible fields so legacy consumers can read these records
        "example_sql": [],
        "example_cypher": [],
        "sql_template": None,
        "cypher_template": None,
        "example_answers": [],
    }
    RECORDS.append(rec)
    return rec


# Common metric bundles -------------------------------------------------
PERF_METRICS = ["policy_count", "sum_assured_share", "avg_sum_assured",
                "persistency_rate", "lapse_rate", "surrender_rate", "loss_ratio"]
RISK_METRICS = ["policy_count", "lapse_rate", "surrender_rate", "attrition_rate",
                "claim_rate", "risk_loss_ratio"]
VALUE_METRICS = ["policy_count", "total_annual_premium", "avg_annual_premium",
                 "avg_sum_assured", "sum_assured_share", "avg_customer_income"]

P_TABLES = ["policies", "customers", "products", "plans"]
ALL_TABLES = ["policies", "customers", "products", "plans", "claims",
              "surrenders", "retention", "sales"]

REL_CORE = ["Customer-[:HOLDS]->Policy", "Policy-[:OF_PRODUCT]->Product",
            "Policy-[:UNDER_PLAN]->Plan", "Agent-[:SOLD]->Policy",
            "Policy-[:BOOKED_AT]->Branch"]
REL_CLAIM = REL_CORE + ["Claim-[:AGAINST]->Policy", "Claim-[:FILED_BY]->Customer"]
REL_SURR = REL_CORE + ["Policy-[:HAS_SURRENDER]->Surrender"]
REL_RET = REL_CORE + ["Policy-[:HAS_RETENTION_EFFORT]->Retention",
                      "Retention-[:CONTACTED_CUSTOMER]->Customer"]


# =====================================================================
# A. EXECUTIVE / PORTFOLIO HEALTH
# =====================================================================

def domain_portfolio_health():
    ps("How healthy is the overall insurance portfolio across size, persistency, "
       "claims economics and concentration?",
       bi.PORTFOLIO_HEALTH,
       "Give management a single, evidence-backed read on the state of the book.",
       bi.TIER_MULTI_STEP,
       ["How healthy is the overall insurance portfolio?",
        "Give me a management-level assessment of the current portfolio.",
        "What is the overall state of our book of business?",
        "Give me an executive summary of portfolio health.",
        "How are we doing overall?"],
       [step("s1", "Portfolio KPI block", "portfolio_overview", {},
             "Establish headline size, persistency, claims and retention numbers."),
        step("s2", "Product mix and performance", "multi_metric_table",
             {"dimension": "product", "metrics": PERF_METRICS, "sort_by": "lapse_rate"},
             "See which products carry the book and how each performs."),
        step("s3", "Channel mix and performance", "multi_metric_table",
             {"dimension": "channel", "metrics": PERF_METRICS, "sort_by": "lapse_rate"},
             "See how distribution splits and whether any channel is weak."),
        step("s4", "Zone performance", "compare_to_baseline",
             {"dimension": "zone", "metric": "lapse_rate"},
             "Check whether persistency problems are geographic."),
        step("s5", "Sum-assured concentration by product", "concentration",
             {"dimension": "product", "value_metric": "total_sum_assured", "top_n": 3},
             "Quantify how dependent the book is on a few products.")],
       ALL_TABLES,
       ["policy_status", "sum_assured", "annual_premium", "total_premium_paid",
        "product_name", "sales_channel", "zone", "claim_amount", "retention_status"],
       ["persistency_rate", "lapse_rate", "surrender_rate", "loss_ratio",
        "risk_loss_ratio", "retention_success_rate", "sum_assured_share"],
       ["portfolio", "health", "risk", "product", "channel", "zone"],
       "executive_assessment", "executive_assessment", REL_CLAIM + REL_RET)

    ps("What are the biggest risks currently sitting in the portfolio?",
       bi.PORTFOLIO_HEALTH,
       "Surface the handful of exposures most likely to hurt the book, ranked by evidence.",
       bi.TIER_MULTI_STEP,
       ["What are the biggest risks in our insurance portfolio?",
        "What are the biggest risks in the current portfolio?",
        "Where is our biggest exposure?",
        "What should the risk team be worried about?",
        "What are the top threats to the book right now?"],
       [step("s1", "Portfolio KPI block", "portfolio_overview", {},
             "Set the baseline every risk is measured against."),
        step("s2", "Products with worst persistency", "compare_to_baseline",
             {"dimension": "product", "metric": "lapse_rate"},
             "Identify products lapsing materially faster than the book."),
        step("s3", "Products with worst claims economics", "compare_to_baseline",
             {"dimension": "product", "metric": "loss_ratio"},
             "Identify where claim outflow is high relative to premium collected."),
        step("s4", "Sum-assured concentration by product", "concentration",
             {"dimension": "product", "value_metric": "total_sum_assured", "top_n": 3},
             "Measure single-product dependency."),
        step("s5", "Largest single-policy exposure", "top_entity_concentration",
             {"column": "sum_assured", "top_n": 10},
             "Measure how much cover sits on a handful of policies."),
        step("s6", "Agents with outlier lapse behaviour", "outliers",
             {"dimension": "agent", "metric": "lapse_rate", "method": "iqr", "min_n": 10},
             "Flag distribution-quality outliers worth investigating.")],
       ALL_TABLES,
       ["policy_status", "sum_assured", "total_premium_paid", "claim_amount",
        "product_name", "servicing_agent_id"],
       ["lapse_rate", "loss_ratio", "sum_assured_share", "surrender_rate"],
       ["portfolio", "risk", "attention", "concentration", "anomaly"],
       "risk_register", "risk_register", REL_CLAIM,
       caveat="These are observed exposures in the current book, not forward-looking "
              "projections; the dataset has no future-dated information.")

    ps("Which parts of the portfolio require management attention, ranked by a "
       "declared risk-and-materiality framework?",
       bi.PORTFOLIO_HEALTH,
       "Convert portfolio data into a ranked management agenda.",
       bi.TIER_MULTI_STEP,
       ["Which areas of the portfolio require management attention?",
        "Where should management focus?",
        "What needs attention in the portfolio?",
        "Give me a prioritised management agenda.",
        "Which areas need intervention?"],
       [step("s1", "Product priority ranking", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "lapse_rate", "weight": 0.35, "direction": "high"},
                             {"metric": "surrender_rate", "weight": 0.2, "direction": "high"},
                             {"metric": "loss_ratio", "weight": 0.2, "direction": "high"},
                             {"metric": "sum_assured_share", "weight": 0.25, "direction": "high"}]},
             "Rank products by risk weighted for how much of the book they represent."),
        step("s2", "Channel priority ranking", "composite_score",
             {"dimension": "channel",
              "components": [{"metric": "lapse_rate", "weight": 0.4, "direction": "high"},
                             {"metric": "surrender_rate", "weight": 0.2, "direction": "high"},
                             {"metric": "policy_share", "weight": 0.4, "direction": "high"}]},
             "Rank channels the same way."),
        step("s3", "Zone priority ranking", "composite_score",
             {"dimension": "zone",
              "components": [{"metric": "lapse_rate", "weight": 0.4, "direction": "high"},
                             {"metric": "attrition_rate", "weight": 0.2, "direction": "high"},
                             {"metric": "policy_share", "weight": 0.4, "direction": "high"}]},
             "Rank zones the same way."),
        step("s4", "Portfolio baseline", "portfolio_overview", {},
             "Provide the comparison numbers for the narrative.")],
       ALL_TABLES,
       ["product_name", "sales_channel", "zone", "policy_status", "sum_assured",
        "claim_amount", "total_premium_paid"],
       ["lapse_rate", "surrender_rate", "loss_ratio", "sum_assured_share", "policy_share"],
       ["portfolio", "attention", "risk", "recommendation"],
       "priority_ranking", "priority_ranking", REL_CLAIM)

    ps("What are the strongest and the weakest parts of the portfolio?",
       bi.PORTFOLIO_HEALTH,
       "Contrast the best and worst performing products on a balanced scorecard.",
       bi.TIER_MULTI_STEP,
       ["What are the strongest and weakest parts of the portfolio?",
        "Which products are our best and worst?",
        "What is working and what is not?",
        "Show me the best and worst performers."],
       [step("s1", "Balanced product scorecard", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "persistency_rate", "weight": 0.3, "direction": "high"},
                             {"metric": "lapse_rate", "weight": 0.25, "direction": "low"},
                             {"metric": "loss_ratio", "weight": 0.25, "direction": "low"},
                             {"metric": "sum_assured_share", "weight": 0.2, "direction": "high"}]},
             "Score products so that a high score means a genuinely strong product."),
        step("s2", "Underlying product metrics", "multi_metric_table",
             {"dimension": "product", "metrics": PERF_METRICS, "sort_by": "persistency_rate",
              "ascending": False},
             "Expose the raw numbers behind the score."),
        step("s3", "Portfolio baseline", "portfolio_overview", {},
             "Anchor 'strong' and 'weak' against the book average.")],
       ALL_TABLES,
       ["product_name", "policy_status", "sum_assured", "total_premium_paid", "claim_amount"],
       ["persistency_rate", "lapse_rate", "loss_ratio", "sum_assured_share"],
       ["portfolio", "health", "product", "comparison"],
       "strength_weakness", "strength_weakness", REL_CLAIM)

    ps("How is the portfolio distributed across products, channels, zones and "
       "policy statuses?",
       bi.PORTFOLIO_HEALTH,
       "Describe the shape of the book before judging it.",
       bi.TIER_ANALYTICAL,
       ["How is the portfolio distributed across products, channels, zones and policy statuses?",
        "What is our portfolio mix?",
        "Show me the distribution of the book.",
        "What does our product and channel mix look like?"],
       [step("s1", "Status mix", "portfolio_overview", {},
             "Policy-status split of the book."),
        step("s2", "Product mix", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "policy_share", "sum_assured_share", "premium_share"],
              "sort_by": "policy_share"},
             "Volume and value share by product."),
        step("s3", "Channel mix", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["policy_count", "policy_share", "sum_assured_share", "premium_share"],
              "sort_by": "policy_share"},
             "Volume and value share by channel."),
        step("s4", "Zone mix", "multi_metric_table",
             {"dimension": "zone",
              "metrics": ["policy_count", "policy_share", "sum_assured_share"],
              "sort_by": "policy_share"},
             "Volume and value share by zone.")],
       P_TABLES,
       ["product_name", "sales_channel", "zone", "policy_status", "sum_assured", "annual_premium"],
       ["policy_share", "sum_assured_share", "premium_share"],
       ["portfolio", "product", "channel", "zone"],
       "distribution", "distribution", REL_CORE)

    ps("What are the key indicators of portfolio health and where does each stand?",
       bi.PORTFOLIO_HEALTH,
       "Publish the KPI set with explicit denominators so numbers can be trusted.",
       bi.TIER_ANALYTICAL,
       ["What are the key indicators of portfolio health?",
        "Show me the portfolio KPIs.",
        "What metrics should we track for portfolio health?",
        "Give me the portfolio scorecard."],
       [step("s1", "KPI block with definitions", "portfolio_overview", {},
             "Every headline metric with the denominator it was computed on.")],
       ALL_TABLES,
       ["policy_status", "sum_assured", "annual_premium", "total_premium_paid",
        "claim_amount", "retention_status"],
       ["persistency_rate", "lapse_rate", "surrender_rate", "claim_rate",
        "loss_ratio", "risk_loss_ratio", "retention_success_rate"],
       ["portfolio", "health"],
       "kpi_block", "kpi_block", REL_CLAIM + REL_RET)

    ps("How does portfolio quality vary by policy vintage (year of issuance)?",
       bi.PORTFOLIO_HEALTH,
       "Check whether newer business is better or worse quality than older business.",
       bi.TIER_ANALYTICAL,
       ["How does portfolio quality vary by policy vintage?",
        "Is newer business better than older business?",
        "How does lapse vary by year of issuance?",
        "Show me quality by issuance year."],
       [step("s1", "Quality by issuance year", "multi_metric_table",
             {"dimension": "issuance_year",
              "metrics": ["policy_count", "lapse_rate", "persistency_rate",
                          "avg_sum_assured", "claim_rate"],
              "sort_by": "issuance_year", "ascending": True, "min_n": 15},
             "Track persistency and claims by cohort."),
        step("s2", "Quality by policy age band", "compare_to_baseline",
             {"dimension": "policy_age_band", "metric": "lapse_rate"},
             "Group vintages into bands to smooth thin years.")],
       P_TABLES,
       ["issuance_date", "policy_status", "sum_assured"],
       ["lapse_rate", "persistency_rate", "claim_rate"],
       ["portfolio", "health", "growth"],
       "trend", "leaderboard", REL_CORE,
       caveat="Older cohorts have had more time to lapse, so vintage comparisons "
              "are exposure-biased and should not be read as a deterioration trend.")

    ps("How healthy is the portfolio within a specific zone compared with the book?",
       bi.PORTFOLIO_HEALTH,
       "Give a zone head the same assessment management gets for the whole book.",
       bi.TIER_MULTI_STEP,
       ["How healthy is the portfolio in the South zone?",
        "Give me a portfolio assessment for the West zone.",
        "How is the North zone performing overall?",
        "Assess the East zone book."],
       [step("s1", "Zone vs portfolio profile", "segment_profile",
             {"filters": {"zone": "$zone"}},
             "Side-by-side of the zone against the whole portfolio."),
        step("s2", "Product mix inside the zone", "multi_metric_table",
             {"dimension": "product", "metrics": PERF_METRICS, "filters": {"zone": "$zone"},
              "sort_by": "lapse_rate"},
             "Show which products drive the zone result."),
        step("s3", "Channel mix inside the zone", "multi_metric_table",
             {"dimension": "channel", "metrics": PERF_METRICS, "filters": {"zone": "$zone"},
              "sort_by": "lapse_rate"},
             "Show which channels drive the zone result.")],
       ALL_TABLES, ["zone", "product_name", "sales_channel", "policy_status"],
       ["lapse_rate", "persistency_rate", "loss_ratio"],
       ["portfolio", "zone", "health"],
       "segment_assessment", "segment_contrast", REL_CLAIM,
       parameters={"zone": {"dimension": "zone", "default": "South",
                            "description": "Zone to assess"}})


# =====================================================================
# B. PRODUCT PERFORMANCE & STRATEGY
# =====================================================================

def domain_product():
    ps("Which products are performing well across volume, value, retention and claims?",
       bi.PRODUCT_PERFORMANCE,
       "Judge products on a balanced scorecard rather than a single number.",
       bi.TIER_MULTI_STEP,
       ["Which products are performing well across volume, value, retention and claims?",
        "Which products are performing well?",
        "Which are our best products?",
        "Rank products on overall performance.",
        "How do our products compare on performance?"],
       [step("s1", "Full product scorecard", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "sum_assured_share", "avg_sum_assured",
                          "total_annual_premium", "persistency_rate", "lapse_rate",
                          "surrender_rate", "claim_rate", "loss_ratio"],
              "sort_by": "persistency_rate", "ascending": False},
             "Every product on every relevant dimension at once."),
        step("s2", "Balanced composite score", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "persistency_rate", "weight": 0.3, "direction": "high"},
                             {"metric": "lapse_rate", "weight": 0.2, "direction": "low"},
                             {"metric": "loss_ratio", "weight": 0.25, "direction": "low"},
                             {"metric": "sum_assured_share", "weight": 0.25, "direction": "high"}]},
             "Collapse the scorecard into a defensible ranking."),
        step("s3", "Portfolio baseline", "portfolio_overview", {},
             "Anchor 'well' against the book average.")],
       ALL_TABLES,
       ["product_name", "policy_status", "sum_assured", "annual_premium",
        "total_premium_paid", "claim_amount"],
       PERF_METRICS, ["product", "health", "comparison", "value"],
       "strength_weakness", "strength_weakness", REL_CLAIM)

    ps("Which products need management attention because risk is high relative to "
       "the share of the book they represent?",
       bi.PRODUCT_PERFORMANCE,
       "Focus attention where poor performance actually matters in size terms.",
       bi.TIER_MULTI_STEP,
       ["Which products need management attention?",
        "Which products are problematic?",
        "Which products should we worry about?",
        "Which products are underperforming and material?"],
       [step("s1", "Risk-weighted product priority", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "lapse_rate", "weight": 0.3, "direction": "high"},
                             {"metric": "surrender_rate", "weight": 0.2, "direction": "high"},
                             {"metric": "loss_ratio", "weight": 0.25, "direction": "high"},
                             {"metric": "sum_assured_share", "weight": 0.25, "direction": "high"}]},
             "Rank products by risk weighted by materiality."),
        step("s2", "Lapse vs portfolio baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "lapse_rate"},
             "Quantify the gap to the book average."),
        step("s3", "Claims economics vs baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "loss_ratio"},
             "Quantify the claims-economics gap.")],
       ALL_TABLES, ["product_name", "policy_status", "sum_assured", "claim_amount"],
       ["lapse_rate", "surrender_rate", "loss_ratio", "sum_assured_share"],
       ["product", "attention", "risk"],
       "priority_ranking", "priority_ranking", REL_CLAIM)

    ps("Which products carry high volume but poor persistency?",
       bi.PRODUCT_PERFORMANCE,
       "Find products that are being sold well but not kept.",
       bi.TIER_ANALYTICAL,
       ["Which products have high volume but poor persistency?",
        "Which products sell well but lapse a lot?",
        "Where do we sell a lot but retain badly?",
        "High volume low persistency products?"],
       [step("s1", "Volume and persistency together", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "policy_share", "persistency_rate",
                          "lapse_rate", "attrition_rate"],
              "sort_by": "lapse_rate"},
             "Put volume and persistency side by side."),
        step("s2", "Volume-weighted persistency risk", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "policy_share", "weight": 0.5, "direction": "high"},
                             {"metric": "lapse_rate", "weight": 0.5, "direction": "high"}]},
             "Rank by the combination of size and lapse."),
        step("s3", "Lapse gap to baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "lapse_rate"},
             "Show which gaps are genuinely above average.")],
       P_TABLES, ["product_name", "policy_status"],
       ["policy_share", "persistency_rate", "lapse_rate"],
       ["product", "lapse", "growth"],
       "priority_ranking", "priority_ranking", REL_CORE)

    ps("Which products carry the highest lapse and surrender risk?",
       bi.PRODUCT_PERFORMANCE,
       "Rank products on attrition, with surrender measured only where it is possible.",
       bi.TIER_ANALYTICAL,
       ["Which products have high lapse or surrender risk?",
        "Which products have the highest lapse risk?",
        "Which products have the highest surrender risk?",
        "Where is attrition risk concentrated by product?"],
       [step("s1", "Attrition metrics by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "lapse_rate", "surrender_rate", "attrition_rate",
                          "persistency_rate"],
              "sort_by": "attrition_rate"},
             "Lapse, surrender and combined attrition per product."),
        step("s2", "Attrition gap to baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "attrition_rate"},
             "Separate genuinely elevated products from noise.")],
       P_TABLES, ["product_name", "policy_status", "has_surrender_value"],
       ["lapse_rate", "surrender_rate", "attrition_rate"],
       ["product", "lapse", "surrender", "risk"],
       "leaderboard", "leaderboard", REL_SURR,
       caveat="Term Life and Health Rider carry no surrender value, so they are "
              "excluded from the surrender-rate denominator rather than shown as 0%.")

    ps("Which products have unfavourable claims economics?",
       bi.PRODUCT_PERFORMANCE,
       "Identify products where claim outflow is high relative to premium collected.",
       bi.TIER_MULTI_STEP,
       ["Which products have unfavorable claims economics?",
        "Which products have unfavourable claims economics?",
        "Which products have the highest loss ratios?",
        "Where are claims disproportionately high relative to premiums?",
        "Which products are economically unattractive?"],
       [step("s1", "Loss ratios by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "loss_ratio", "risk_loss_ratio",
                          "claim_rate", "risk_claim_rate", "total_claim_amount",
                          "total_premium_collected"],
              "sort_by": "loss_ratio"},
             "All-claims and risk-only loss ratios side by side."),
        step("s2", "Loss ratio gap to baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "loss_ratio"},
             "Quantify how far each product sits from the book."),
        step("s3", "Claim-type mix by product", "crosstab_metric",
             {"dim_a": "product", "dim_b": "claim_type", "metric": "claim_count", "min_n": 1},
             "Show whether the ratio is driven by maturities or by risk claims.")],
       ["policies", "claims", "products"],
       ["product_name", "claim_amount", "claim_type", "total_premium_paid"],
       ["loss_ratio", "risk_loss_ratio", "claim_rate"],
       ["product", "economics", "claims"],
       "economics", "economics", REL_CLAIM,
       caveat="The dataset has no expense, commission or reserve data, so this is "
              "claims economics only - not true profitability.")

    ps("Which products look attractive from both a growth and a risk perspective?",
       bi.PRODUCT_PERFORMANCE,
       "Find products worth pushing: they sell, they stick and they do not bleed claims.",
       bi.TIER_MULTI_STEP,
       ["Which products are attractive from both growth and risk perspectives?",
        "Which products should we push?",
        "Which products give us growth without risk?",
        "Where should we invest sales effort by product?"],
       [step("s1", "Growth-and-quality composite", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "policy_share", "weight": 0.25, "direction": "high"},
                             {"metric": "avg_annual_premium", "weight": 0.25, "direction": "high"},
                             {"metric": "persistency_rate", "weight": 0.25, "direction": "high"},
                             {"metric": "loss_ratio", "weight": 0.25, "direction": "low"}]},
             "Score products for attractiveness rather than for risk."),
        step("s2", "Underlying metrics", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["policy_count", "avg_annual_premium", "avg_sum_assured",
                          "persistency_rate", "lapse_rate", "loss_ratio"],
              "sort_by": "persistency_rate", "ascending": False},
             "Expose the numbers behind the score.")],
       ALL_TABLES, ["product_name", "policy_status", "annual_premium", "claim_amount"],
       ["policy_share", "persistency_rate", "loss_ratio", "avg_annual_premium"],
       ["product", "growth", "risk", "recommendation"],
       "priority_ranking", "priority_ranking", REL_CLAIM)

    ps("Which products should be prioritised for retention initiatives?",
       bi.PRODUCT_PERFORMANCE,
       "Direct finite retention capacity at the products where it will move the most value.",
       bi.TIER_MULTI_STEP,
       ["Which products should management prioritize for retention?",
        "Which products should we prioritise for retention?",
        "Where should the retention team focus by product?",
        "Which product should we target with retention effort?"],
       [step("s1", "Retention priority score", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "lapse_rate", "weight": 0.35, "direction": "high"},
                             {"metric": "surrender_rate", "weight": 0.15, "direction": "high"},
                             {"metric": "policy_share", "weight": 0.25, "direction": "high"},
                             {"metric": "avg_annual_premium", "weight": 0.25, "direction": "high"}]},
             "Weight attrition by how much premium is at stake."),
        step("s2", "Lapse gap to baseline", "compare_to_baseline",
             {"dimension": "product", "metric": "lapse_rate"},
             "Show which products are genuinely above the book lapse rate."),
        step("s3", "Retention effectiveness by product so far", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": True},
             "Check whether retention effort already works on that product."),
        step("s4", "Where the top product's lapses concentrate", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {"product": "$top_product"},
              "min_n": 12, "top_k": 6},
             "Point the intervention at segments rather than the whole product.")],
       ALL_TABLES,
       ["product_name", "policy_status", "annual_premium", "retention_status"],
       ["lapse_rate", "surrender_rate", "policy_share", "retention_success_rate"],
       ["product", "retention", "attention", "recommendation"],
       "priority_ranking", "retention_priority", REL_RET,
       parameters={"top_product": {"source": "step:s1", "field": "product_name",
                                   "description": "Highest-priority product from step 1"}})

    ps("What characteristics distinguish strong-performing products from weak ones?",
       bi.PRODUCT_PERFORMANCE,
       "Explain what 'good' looks like structurally, not just which product wins.",
       bi.TIER_MULTI_STEP,
       ["What characteristics distinguish strong-performing products from weak-performing products?",
        "What makes a product perform well?",
        "What separates our good products from the bad ones?",
        "Why do some products perform better than others?"],
       [step("s1", "Balanced product scorecard", "composite_score",
             {"dimension": "product",
              "components": [{"metric": "persistency_rate", "weight": 0.35, "direction": "high"},
                             {"metric": "lapse_rate", "weight": 0.25, "direction": "low"},
                             {"metric": "loss_ratio", "weight": 0.4, "direction": "low"}]},
             "Split the estate into strong and weak."),
        step("s2", "Structural characteristics by product", "multi_metric_table",
             {"dimension": "product",
              "metrics": ["avg_sum_assured", "avg_annual_premium", "avg_customer_income",
                          "avg_customer_age", "avg_premium_to_income", "rider_attachment_rate",
                          "medical_underwriting_share", "smoker_share"],
              "sort_by": "avg_premium_to_income"},
             "Compare customer and design characteristics across products."),
        step("s3", "Product-category view", "multi_metric_table",
             {"dimension": "product_category",
              "metrics": ["policy_count", "persistency_rate", "lapse_rate", "loss_ratio"],
              "sort_by": "lapse_rate"},
             "Check whether the pattern holds at category level.")],
       ALL_TABLES,
       ["product_name", "product_category", "sum_assured", "annual_premium",
        "annual_income", "age", "rider_count", "medical_underwriting_flag"],
       ["persistency_rate", "loss_ratio", "avg_premium_to_income", "rider_attachment_rate"],
       ["product", "diagnostic", "comparison"],
       "diagnostic", "diagnostic", REL_CLAIM,
       caveat="These are structural associations across only eight products; with "
              "n=8 they are directional, not statistically established.")

    ps("How does a single named product perform across every relevant dimension?",
       bi.PRODUCT_PERFORMANCE,
       "Give a product manager a full read on one product.",
       bi.TIER_MULTI_STEP,
       ["How is Whole Life performing?",
        "Give me a full assessment of Term Life.",
        "How does ULIP perform across the board?",
        "Show me everything about the Endowment product."],
       [step("s1", "Product vs portfolio profile", "segment_profile",
             {"filters": {"product": "$product"}},
             "Every headline metric for the product against the book."),
        step("s2", "Channel split inside the product", "multi_metric_table",
             {"dimension": "channel", "metrics": RISK_METRICS,
              "filters": {"product": "$product"}, "sort_by": "lapse_rate", "min_n": 10},
             "Where the product is sold and how each route performs."),
        step("s3", "Zone split inside the product", "multi_metric_table",
             {"dimension": "zone", "metrics": RISK_METRICS,
              "filters": {"product": "$product"}, "sort_by": "lapse_rate", "min_n": 10},
             "Geographic variation within the product."),
        step("s4", "Retention performance on the product", "multi_metric_table",
             {"dimension": "contact_channel",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "filters": {"product": "$product"}, "sort_by": "retention_success_rate",
              "ascending": False, "min_n": 5},
             "Whether retention effort works on this product.")],
       ALL_TABLES, ["product_name", "sales_channel", "zone", "policy_status", "retention_status"],
       ["lapse_rate", "surrender_rate", "loss_ratio", "retention_success_rate"],
       ["product", "health"],
       "segment_assessment", "segment_contrast", REL_RET,
       parameters={"product": {"dimension": "product", "default": "Whole Life",
                               "description": "Product to assess"}})

    ps("How do product categories (Protection, Savings, Investment, Retirement, "
       "Health) compare on risk and value?",
       bi.PRODUCT_PERFORMANCE,
       "Compare at the strategy level rather than the SKU level.",
       bi.TIER_ANALYTICAL,
       ["How do product categories compare?",
        "Compare protection versus savings products.",
        "Which product category performs best?",
        "How do savings and investment products differ on risk?"],
       [step("s1", "Category scorecard", "multi_metric_table",
             {"dimension": "product_category",
              "metrics": ["policy_count", "sum_assured_share", "avg_sum_assured",
                          "persistency_rate", "lapse_rate", "surrender_rate", "loss_ratio"],
              "sort_by": "lapse_rate"},
             "Every category on every metric."),
        step("s2", "Category gap to baseline", "compare_to_baseline",
             {"dimension": "product_category", "metric": "lapse_rate"},
             "Which categories are genuinely off the book average.")],
       ALL_TABLES, ["product_category", "policy_status", "sum_assured", "claim_amount"],
       ["persistency_rate", "lapse_rate", "loss_ratio", "sum_assured_share"],
       ["product", "comparison"],
       "comparison", "comparison", REL_CLAIM)

    ps("How does plan design (regular pay versus limited pay) relate to persistency?",
       bi.PRODUCT_PERFORMANCE,
       "Test whether the premium-payment structure is associated with retention.",
       bi.TIER_ANALYTICAL,
       ["Does plan design affect persistency?",
        "How does regular pay compare to limited pay on lapse?",
        "Which premium payment type has better persistency?",
        "Does premium paying term relate to lapse?"],
       [step("s1", "Persistency by premium payment type", "multi_metric_table",
             {"dimension": "premium_payment_type",
              "metrics": ["policy_count", "lapse_rate", "persistency_rate",
                          "surrender_rate", "avg_annual_premium"],
              "sort_by": "lapse_rate"},
             "Compare regular against limited pay."),
        step("s2", "Persistency by policy term band", "compare_to_baseline",
             {"dimension": "tenure_band", "metric": "lapse_rate"},
             "Check whether longer terms lapse more."),
        step("s3", "Plan-level detail", "multi_metric_table",
             {"dimension": "plan",
              "metrics": ["policy_count", "lapse_rate", "avg_annual_premium"],
              "sort_by": "lapse_rate", "min_n": 20},
             "Drill to individual plans where samples allow.")],
       P_TABLES, ["premium_payment_type", "premium_paying_term_years",
                  "policy_tenure_years", "policy_status", "plan_name"],
       ["lapse_rate", "persistency_rate"],
       ["product", "lapse", "diagnostic"],
       "comparison", "comparison", REL_CORE)

    ps("Which products generate the highest-value policies?",
       bi.PRODUCT_PERFORMANCE,
       "Separate volume leaders from value leaders.",
       bi.TIER_ANALYTICAL,
       ["Which products generate the highest value policies?",
        "Which products bring in the most premium?",
        "Which products have the biggest average ticket size?",
        "Where does our premium actually come from?"],
       [step("s1", "Value metrics by product", "multi_metric_table",
             {"dimension": "product", "metrics": VALUE_METRICS,
              "sort_by": "avg_annual_premium"},
             "Average and total value per product."),
        step("s2", "Premium concentration by product", "concentration",
             {"dimension": "product", "value_metric": "total_annual_premium", "top_n": 3},
             "How much premium depends on how few products.")],
       P_TABLES, ["product_name", "annual_premium", "sum_assured", "annual_income"],
       ["avg_annual_premium", "total_annual_premium", "sum_assured_share"],
       ["product", "value", "growth"],
       "leaderboard", "leaderboard", REL_CORE)


# =====================================================================
# C. SALES CHANNEL PERFORMANCE
# =====================================================================

def domain_channel():
    ps("Which sales channel gives the best balance between growth and persistency?",
       bi.CHANNEL_PERFORMANCE,
       "Stop judging channels on volume alone; weigh what they keep.",
       bi.TIER_MULTI_STEP,
       ["Which sales channel gives us the best balance of growth and persistency?",
        "Which sales channel provides the best balance between volume and retention?",
        "Which channel is genuinely our best?",
        "Which channel should we grow?",
        "Which distribution channel performs best overall?"],
       [step("s1", "Channel scorecard", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["policy_count", "policy_share", "avg_sum_assured",
                          "avg_annual_premium", "persistency_rate", "lapse_rate",
                          "surrender_rate", "loss_ratio"],
              "sort_by": "persistency_rate", "ascending": False},
             "Volume, value and persistency in one table."),
        step("s2", "Balanced channel score", "composite_score",
             {"dimension": "channel",
              "components": [{"metric": "policy_share", "weight": 0.25, "direction": "high"},
                             {"metric": "avg_annual_premium", "weight": 0.2, "direction": "high"},
                             {"metric": "persistency_rate", "weight": 0.35, "direction": "high"},
                             {"metric": "lapse_rate", "weight": 0.2, "direction": "low"}]},
             "Rank channels on the growth/persistency trade-off explicitly."),
        step("s3", "Retention effectiveness by channel", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False},
             "Whether a channel's business can be saved when it wobbles.")],
       ALL_TABLES, ["sales_channel", "policy_status", "sum_assured", "annual_premium",
                    "retention_status"],
       ["policy_share", "persistency_rate", "lapse_rate", "retention_success_rate"],
       ["channel", "growth", "lapse", "comparison"],
       "priority_ranking", "priority_ranking", REL_RET)

    ps("Which channels generate the highest-value policies?",
       bi.CHANNEL_PERFORMANCE,
       "Find where the big-ticket business comes from.",
       bi.TIER_ANALYTICAL,
       ["Which channels generate high-value policies?",
        "Which channel brings the biggest policies?",
        "Where does our large-ticket business come from?",
        "Which channel has the highest average sum assured?"],
       [step("s1", "Value metrics by channel", "multi_metric_table",
             {"dimension": "channel", "metrics": VALUE_METRICS,
              "sort_by": "avg_sum_assured"},
             "Average and total value per channel."),
        step("s2", "Value concentration by channel", "concentration",
             {"dimension": "channel", "value_metric": "total_sum_assured", "top_n": 2},
             "How dependent value is on one or two channels.")],
       P_TABLES, ["sales_channel", "sum_assured", "annual_premium", "annual_income"],
       ["avg_sum_assured", "avg_annual_premium", "sum_assured_share"],
       ["channel", "value"],
       "leaderboard", "leaderboard", REL_CORE)

    ps("Which channels have elevated lapse or surrender rates?",
       bi.CHANNEL_PERFORMANCE,
       "Identify distribution routes whose business does not stick.",
       bi.TIER_ANALYTICAL,
       ["Which channels have elevated lapse or surrender rates?",
        "Which channel has the worst persistency?",
        "Where is attrition worst by channel?",
        "Which sales channel loses the most policies?"],
       [step("s1", "Attrition by channel", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["policy_count", "lapse_rate", "surrender_rate",
                          "attrition_rate", "persistency_rate"],
              "sort_by": "attrition_rate"},
             "Lapse, surrender and combined attrition per channel."),
        step("s2", "Lapse gap to baseline", "compare_to_baseline",
             {"dimension": "channel", "metric": "lapse_rate"},
             "Separate genuinely elevated channels from noise."),
        step("s3", "Surrender gap to baseline", "compare_to_baseline",
             {"dimension": "channel", "metric": "surrender_rate"},
             "Same test for surrender.")],
       P_TABLES, ["sales_channel", "policy_status"],
       ["lapse_rate", "surrender_rate", "attrition_rate"],
       ["channel", "lapse", "surrender", "risk"],
       "leaderboard", "leaderboard", REL_SURR)

    ps("Is any channel producing high acquisition volume but weak persistency?",
       bi.CHANNEL_PERFORMANCE,
       "Detect the classic 'sells hard, keeps badly' pattern before it compounds.",
       bi.TIER_MULTI_STEP,
       ["Is there evidence that a channel is producing high acquisition but weak persistency?",
        "Which channel sells a lot but keeps little?",
        "Do any channels have a volume-versus-quality problem?",
        "Is any channel writing bad business?"],
       [step("s1", "Volume against persistency", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["policy_count", "policy_share", "persistency_rate",
                          "lapse_rate", "attrition_rate"],
              "sort_by": "lapse_rate"},
             "Directly contrast how much a channel writes with how much it keeps."),
        step("s2", "Volume-weighted lapse risk", "composite_score",
             {"dimension": "channel",
              "components": [{"metric": "policy_share", "weight": 0.5, "direction": "high"},
                             {"metric": "lapse_rate", "weight": 0.5, "direction": "high"}]},
             "Rank on the combination of size and lapse."),
        step("s3", "Where the worst channel's lapses sit", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {"channel": "$worst_channel"},
              "min_n": 12, "top_k": 6},
             "Decompose the weak channel into segments.")],
       P_TABLES, ["sales_channel", "policy_status", "product_name"],
       ["policy_share", "lapse_rate", "persistency_rate"],
       ["channel", "lapse", "growth", "diagnostic"],
       "diagnostic", "diagnostic", REL_CORE,
       parameters={"worst_channel": {"source": "step:s2", "field": "sales_channel",
                                     "description": "Highest volume-weighted lapse channel"}})

    ps("Which channels perform best for which products?",
       bi.CHANNEL_PERFORMANCE,
       "Match distribution to product instead of applying one channel strategy everywhere.",
       bi.TIER_MULTI_STEP,
       ["Which channels perform well for different products?",
        "Which channel works best for each product?",
        "Show me product performance by channel.",
        "Which product-channel combinations are strongest?"],
       [step("s1", "Lapse grid: product x channel", "crosstab_metric",
             {"dim_a": "product", "dim_b": "channel", "metric": "lapse_rate", "min_n": 15},
             "Find the product-channel cells that lapse most and least."),
        step("s2", "Volume grid: product x channel", "crosstab_metric",
             {"dim_a": "product", "dim_b": "channel", "metric": "policy_count", "min_n": 1},
             "Show which cells actually carry volume."),
        step("s3", "Channel baseline", "compare_to_baseline",
             {"dimension": "channel", "metric": "lapse_rate"},
             "Anchor the grid against channel averages.")],
       P_TABLES, ["sales_channel", "product_name", "policy_status"],
       ["lapse_rate", "policy_count"],
       ["channel", "product", "comparison"],
       "grid", "grid", REL_CORE,
       caveat="Product-channel cells are small; cells below the minimum sample "
              "size are dropped rather than ranked.")

    ps("Which channels perform best for which customer segments?",
       bi.CHANNEL_PERFORMANCE,
       "Align channel strategy to the customers each channel actually reaches.",
       bi.TIER_MULTI_STEP,
       ["Which channels perform well for different customer segments?",
        "Which channel suits high-income customers?",
        "How does channel performance vary by customer age?",
        "Do channels serve different customer types?"],
       [step("s1", "Customer profile by channel", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["avg_customer_income", "avg_customer_age", "smoker_share",
                          "avg_sum_assured", "avg_premium_to_income"],
              "sort_by": "avg_customer_income"},
             "Show which customers each channel brings in."),
        step("s2", "Lapse grid: income band x channel", "crosstab_metric",
             {"dim_a": "income_band", "dim_b": "channel", "metric": "lapse_rate", "min_n": 15},
             "Find income segments a channel handles badly."),
        step("s3", "Lapse grid: age band x channel", "crosstab_metric",
             {"dim_a": "age_band", "dim_b": "channel", "metric": "lapse_rate", "min_n": 15},
             "Same test on age.")],
       P_TABLES, ["sales_channel", "annual_income", "age", "policy_status"],
       ["avg_customer_income", "lapse_rate"],
       ["channel", "customer", "comparison"],
       "grid", "grid", REL_CORE)

    ps("Where should sales management focus across channels?",
       bi.CHANNEL_PERFORMANCE,
       "Turn channel data into a specific management instruction.",
       bi.TIER_MULTI_STEP,
       ["Where should sales management focus?",
        "What should the sales head do about channels?",
        "Which channel needs intervention?",
        "Give me a channel action plan."],
       [step("s1", "Channel attention score", "composite_score",
             {"dimension": "channel",
              "components": [{"metric": "lapse_rate", "weight": 0.35, "direction": "high"},
                             {"metric": "surrender_rate", "weight": 0.15, "direction": "high"},
                             {"metric": "policy_share", "weight": 0.3, "direction": "high"},
                             {"metric": "avg_annual_premium", "weight": 0.2, "direction": "high"}]},
             "Rank channels by risk weighted by materiality."),
        step("s2", "Channel scorecard", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["policy_count", "policy_share", "persistency_rate", "lapse_rate",
                          "surrender_rate", "avg_annual_premium", "loss_ratio"],
              "sort_by": "lapse_rate"},
             "The evidence behind the ranking."),
        step("s3", "Drivers inside the priority channel", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {"channel": "$priority_channel"},
              "min_n": 12, "top_k": 6},
             "Make the instruction specific rather than 'fix the channel'.")],
       ALL_TABLES, ["sales_channel", "policy_status", "annual_premium", "claim_amount"],
       ["lapse_rate", "policy_share", "avg_annual_premium"],
       ["channel", "attention", "recommendation"],
       "priority_ranking", "priority_ranking", REL_CLAIM,
       parameters={"priority_channel": {"source": "step:s1", "field": "sales_channel",
                                        "description": "Top-priority channel from step 1"}})

    ps("How does a single named channel perform against the rest of the book?",
       bi.CHANNEL_PERFORMANCE,
       "Give a channel head their own scorecard.",
       bi.TIER_MULTI_STEP,
       ["How is the Agency channel performing?",
        "Give me an assessment of Bancassurance.",
        "How does the Online channel compare with the book?",
        "Assess the Broker channel."],
       [step("s1", "Channel vs portfolio profile", "segment_profile",
             {"filters": {"channel": "$channel"}},
             "Headline metrics for the channel against the book."),
        step("s2", "Product mix inside the channel", "multi_metric_table",
             {"dimension": "product", "metrics": RISK_METRICS,
              "filters": {"channel": "$channel"}, "sort_by": "lapse_rate", "min_n": 10},
             "What the channel actually sells and how it holds up."),
        step("s3", "Zone mix inside the channel", "multi_metric_table",
             {"dimension": "zone", "metrics": RISK_METRICS,
              "filters": {"channel": "$channel"}, "sort_by": "lapse_rate", "min_n": 10},
             "Geographic variation within the channel.")],
       ALL_TABLES, ["sales_channel", "product_name", "zone", "policy_status"],
       ["lapse_rate", "persistency_rate", "loss_ratio"],
       ["channel", "health"],
       "segment_assessment", "segment_contrast", REL_CLAIM,
       parameters={"channel": {"dimension": "channel", "default": "Agency",
                               "description": "Channel to assess"}})

    ps("Do payment modes differ by channel in a way that affects persistency?",
       bi.CHANNEL_PERFORMANCE,
       "Test whether channel persistency gaps are really a billing-frequency effect.",
       bi.TIER_MULTI_STEP,
       ["Do payment modes differ by channel?",
        "Is channel lapse explained by payment mode?",
        "How does payment mode interact with sales channel?",
        "Which channel sells more monthly-pay business?"],
       [step("s1", "Payment mode mix by channel", "crosstab_metric",
             {"dim_a": "channel", "dim_b": "payment_mode", "metric": "policy_count", "min_n": 1},
             "Show how billing frequency differs across channels."),
        step("s2", "Lapse by payment mode", "compare_to_baseline",
             {"dimension": "payment_mode", "metric": "lapse_rate"},
             "Establish whether payment mode matters at all."),
        step("s3", "Lapse grid: channel x payment mode", "crosstab_metric",
             {"dim_a": "channel", "dim_b": "payment_mode", "metric": "lapse_rate", "min_n": 20},
             "Test whether the channel gap survives once mode is held roughly constant.")],
       P_TABLES, ["sales_channel", "payment_mode", "policy_status"],
       ["lapse_rate", "policy_count"],
       ["channel", "payment", "lapse", "diagnostic"],
       "grid", "grid", REL_CORE,
       caveat="This is a cross-tabulation, not a controlled model; it can suggest "
              "confounding but cannot isolate an independent channel effect.")

    ps("Which channels have the strongest claims economics?",
       bi.CHANNEL_PERFORMANCE,
       "Check whether some routes to market write systematically worse risk.",
       bi.TIER_ANALYTICAL,
       ["Which channels have the best claims economics?",
        "Do some channels write worse risk than others?",
        "What is the loss ratio by channel?",
        "Which channel has the highest claims burden?"],
       [step("s1", "Claims economics by channel", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["policy_count", "claim_rate", "risk_claim_rate",
                          "loss_ratio", "risk_loss_ratio", "total_claim_amount"],
              "sort_by": "loss_ratio"},
             "Frequency and severity view per channel."),
        step("s2", "Loss ratio gap to baseline", "compare_to_baseline",
             {"dimension": "channel", "metric": "loss_ratio"},
             "Which channels genuinely deviate."),
        step("s3", "Underwriting mix by channel", "multi_metric_table",
             {"dimension": "channel",
              "metrics": ["medical_underwriting_share", "smoker_share", "avg_customer_age"],
              "sort_by": "medical_underwriting_share"},
             "Context: whether risk-selection intensity differs by channel.")],
       ["policies", "claims", "customers"],
       ["sales_channel", "claim_amount", "total_premium_paid", "medical_underwriting_flag"],
       ["loss_ratio", "risk_loss_ratio", "claim_rate"],
       ["channel", "economics", "claims"],
       "economics", "economics", REL_CLAIM)


# =====================================================================
# D. CUSTOMER SEGMENTATION & VALUE
# =====================================================================

def domain_customer():
    ps("Which customer segments are the most valuable?",
       bi.CUSTOMER_SEGMENTATION,
       "Identify where premium and cover actually concentrate.",
       bi.TIER_MULTI_STEP,
       ["Which customer segments are most valuable?",
        "Where does our value come from?",
        "Which customers are worth the most to us?",
        "Which segments contribute most premium?"],
       [step("s1", "Value by income band", "multi_metric_table",
             {"dimension": "income_band",
              "metrics": ["policy_count", "policy_share", "sum_assured_share",
                          "premium_share", "avg_annual_premium", "avg_sum_assured"],
              "sort_by": "premium_share"},
             "Value contribution by income."),
        step("s2", "Value by age band", "multi_metric_table",
             {"dimension": "age_band",
              "metrics": ["policy_count", "policy_share", "premium_share",
                          "avg_annual_premium"],
              "sort_by": "premium_share"},
             "Value contribution by life stage."),
        step("s3", "Premium concentration by income band", "concentration",
             {"dimension": "income_band", "value_metric": "total_annual_premium", "top_n": 2},
             "How dependent premium is on the top segments."),
        step("s4", "Top customers by value", "entity_shortlist",
             {"base": "customer",
              "score_components": [{"column": "value_score", "weight": 1.0, "direction": "high"}],
              "top_n": 15,
              "columns": ["customer_id", "full_name", "annual_income", "policy_count",
                          "total_annual_premium", "total_premium_paid", "total_sum_assured"]},
             "Name the individual customers behind the aggregate.")],
       ["policies", "customers"],
       ["annual_income", "age", "annual_premium", "sum_assured"],
       ["premium_share", "sum_assured_share", "avg_annual_premium"],
       ["customer", "value", "portfolio"],
       "value_segmentation", "leaderboard", REL_CORE)

    ps("Which customer segments are most at risk of lapsing?",
       bi.CUSTOMER_SEGMENTATION,
       "Point retention at the customer characteristics associated with attrition.",
       bi.TIER_MULTI_STEP,
       ["Which customer segments are most at risk of lapsing?",
        "Which customers are most likely to lapse?",
        "Which customer segments have the highest lapse risk?",
        "Who is most likely to stop paying?",
        "Which segments are most at risk?"],
       [step("s1", "Lapse by income band", "compare_to_baseline",
             {"dimension": "income_band", "metric": "lapse_rate"},
             "Income is the strongest available affordability signal."),
        step("s2", "Lapse by premium-to-income band", "compare_to_baseline",
             {"dimension": "premium_to_income_band", "metric": "lapse_rate"},
             "Direct affordability strain measure."),
        step("s3", "Lapse by age band", "compare_to_baseline",
             {"dimension": "age_band", "metric": "lapse_rate"},
             "Life-stage effect."),
        step("s4", "Lapse by smoker status", "compare_to_baseline",
             {"dimension": "smoker", "metric": "lapse_rate"},
             "Health-proxy segmentation."),
        step("s5", "Strongest segment associations overall", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {}, "min_n": 25, "top_k": 8},
             "Rank every candidate segment by deviation from the book average.")],
       ["policies", "customers"],
       ["annual_income", "age", "is_smoker", "annual_premium", "policy_status"],
       ["lapse_rate"],
       ["customer", "lapse", "risk"],
       "risk_segmentation", "risk_segmentation", REL_CORE,
       caveat="These are observed associations across segments, not causes of lapse "
              "and not individual-level predictions.")

    ps("What characteristics distinguish high-value customers from the rest?",
       bi.CUSTOMER_SEGMENTATION,
       "Describe the high-value customer so acquisition can look for more of them.",
       bi.TIER_MULTI_STEP,
       ["What characteristics distinguish high-value customers?",
        "What do our best customers look like?",
        "Describe our high value customers.",
        "What is the profile of a high-value policyholder?"],
       [step("s1", "High-value segment profile", "segment_profile",
             {"filters": {"income_band": ["20-50L", "50L+"]}},
             "Contrast the top income bands with the whole portfolio."),
        step("s2", "Value and risk by income band", "multi_metric_table",
             {"dimension": "income_band",
              "metrics": ["policy_count", "avg_sum_assured", "avg_annual_premium",
                          "avg_premium_to_income", "rider_attachment_rate",
                          "lapse_rate", "persistency_rate"],
              "sort_by": "avg_annual_premium"},
             "How characteristics change as value rises."),
        step("s3", "Product preference by income band", "crosstab_metric",
             {"dim_a": "income_band", "dim_b": "product", "metric": "policy_count", "min_n": 1},
             "What high-value customers actually buy."),
        step("s4", "Top customers by value", "entity_shortlist",
             {"base": "customer",
              "score_components": [{"column": "value_score", "weight": 1.0, "direction": "high"}],
              "top_n": 15,
              "columns": ["customer_id", "full_name", "age", "annual_income",
                          "policy_count", "total_annual_premium", "total_sum_assured",
                          "product_name"]},
             "Ground the profile in real records.")],
       ["policies", "customers", "products"],
       ["annual_income", "age", "sum_assured", "annual_premium", "rider_count"],
       ["avg_sum_assured", "avg_annual_premium", "rider_attachment_rate"],
       ["customer", "value"],
       "segment_assessment", "segment_contrast", REL_CORE)

    ps("What characteristics distinguish customers with poor persistency?",
       bi.CUSTOMER_SEGMENTATION,
       "Profile the customers the book loses, so intervention can be targeted.",
       bi.TIER_MULTI_STEP,
       ["What characteristics distinguish customers with poor persistency?",
        "What do lapsing customers look like?",
        "Profile customers who stop paying.",
        "What separates customers who lapse from those who stay?"],
       [step("s1", "Lapsed-policy segment profile", "segment_profile",
             {"filters": {"policy_status": "Lapsed"}},
             "Contrast lapsed policies with the whole book on every characteristic."),
        step("s2", "In-force segment profile", "segment_profile",
             {"filters": {"policy_status": "In-Force"}},
             "The comparison group."),
        step("s3", "Strongest segment associations with lapse", "driver_scan",
             {"metric": "lapse_rate", "focus_filters": {}, "min_n": 25, "top_k": 8},
             "Rank characteristics by how far their lapse rate sits from the book.")],
       ["policies", "customers"],
       ["policy_status", "annual_income", "age", "is_smoker", "bmi",
        "annual_premium", "payment_mode"],
       ["lapse_rate", "avg_customer_income", "avg_premium_to_income"],
       ["customer", "lapse", "diagnostic"],
       "segment_contrast", "segment_contrast", REL_CORE,
       caveat="Differences between lapsed and in-force groups are associations. "
              "The data cannot establish that any characteristic causes lapse.")

    ps("How does customer income relate to policy value, lapse, surrender and claims?",
       bi.CUSTOMER_SEGMENTATION,
       "Trace one customer attribute all the way through the financial outcomes.",
       bi.TIER_MULTI_STEP,
       ["How does customer income relate to policy value, lapse, surrender or claims?",
        "Does income affect lapse?",
        "How does income relate to policy size?",
        "What is the relationship between income and outcomes?"],
       [step("s1", "Every outcome by income band", "multi_metric_table",
             {"dimension": "income_band",
              "metrics": ["policy_count", "avg_sum_assured", "avg_annual_premium",
                          "avg_premium_to_income", "lapse_rate", "surrender_rate",
                          "claim_rate", "loss_ratio"],
              "sort_by": "income_band", "ascending": True},
             "One table, income on the rows, every outcome on the columns."),
        step("s2", "Lapse gap by income band", "compare_to_baseline",
             {"dimension": "income_band", "metric": "lapse_rate"},
             "Which income bands are genuinely off the book average."),
        step("s3", "Surrender gap by income band", "compare_to_baseline",
             {"dimension": "income_band", "metric": "surrender_rate"},
             "Same test for surrender.")],
       ALL_TABLES, ["annual_income", "sum_assured", "annual_premium", "policy_status",
                    "claim_amount"],
       ["lapse_rate", "surrender_rate", "claim_rate", "avg_sum_assured"],
       ["customer", "value", "lapse", "surrender"],
       "relationship", "leaderboard", REL_CLAIM)

    ps("How do smoker and non-smoker segments differ across financial outcomes?",
       bi.CUSTOMER_SEGMENTATION,
       "Test whether the underwriting distinction shows up in the book's economics.",
       bi.TIER_MULTI_STEP,
       ["How do smoker/non-smoker segments differ across financial outcomes?",
        "Compare smoker versus non-smoker customers.",
        "Do smokers claim more?",
        "How do smokers differ on policy value and risk?"],
       [step("s1", "Smoker vs non-smoker on every metric", "multi_metric_table",
             {"dimension": "smoker",
              "metrics": ["policy_count", "avg_sum_assured", "avg_annual_premium",
                          "avg_customer_age", "lapse_rate", "surrender_rate",
                          "claim_rate", "risk_claim_rate", "loss_ratio", "risk_loss_ratio",
                          "medical_underwriting_share"],
              "sort_by": "risk_claim_rate"},
             "The full contrast in one table."),
        step("s2", "Smoker segment vs portfolio", "segment_profile",
             {"filters": {"smoker": "Smoker"}},
             "Explicit gap against the book."),
        step("s3", "Smoker share by product", "multi_metric_table",
             {"dimension": "product", "metrics": ["smoker_share", "risk_claim_rate",
                                                  "risk_loss_ratio"],
              "sort_by": "smoker_share"},
             "Whether smoker exposure concentrates in particular products.")],
       ALL_TABLES, ["is_smoker", "sum_assured", "annual_premium", "claim_amount",
                    "policy_status", "medical_underwriting_flag"],
       ["risk_claim_rate", "risk_loss_ratio", "lapse_rate", "avg_sum_assured"],
       ["customer", "underwriting", "comparison", "claims"],
       "comparison", "comparison", REL_CLAIM,
       caveat="With 126 smoker customers in the dataset, claim-rate differences are "
              "based on small counts and should be treated as indicative.")

    ps("Which combinations of customer characteristics and products look risky?",
       bi.CUSTOMER_SEGMENTATION,
       "Find the specific customer-product cells where attrition concentrates.",
       bi.TIER_MULTI_STEP,
       ["Which combinations of customer characteristics and products appear risky?",
        "Which customer-product combinations are risky?",
        "Where do bad customer and product combinations show up?",
        "Which segment buys the wrong product?"],
       [step("s1", "Lapse grid: income band x product", "crosstab_metric",
             {"dim_a": "income_band", "dim_b": "product", "metric": "lapse_rate", "min_n": 15},
             "Worst-performing income-product cells."),
        step("s2", "Lapse grid: age band x product", "crosstab_metric",
             {"dim_a": "age_band", "dim_b": "product", "metric": "lapse_rate", "min_n": 15},
             "Worst-performing age-product cells."),
        step("s3", "Lapse grid: premium-to-income x product", "crosstab_metric",
             {"dim_a": "premium_to_income_band", "dim_b": "product",
              "metric": "lapse_rate", "min_n": 15},
             "Affordability strain crossed with product."),
        step("s4", "Portfolio lapse baseline", "portfolio_overview", {},
             "The number every cell is judged against.")],
       ["policies", "customers", "products"],
       ["annual_income", "age", "product_name", "annual_premium", "policy_status"],
       ["lapse_rate"],
       ["customer", "product", "risk", "anomaly"],
       "grid", "grid", REL_CORE,
       caveat="Cells below the minimum sample size are excluded; the remaining "
              "cells are still small, so treat them as leads to investigate.")

    ps("How do customer segments differ on claims behaviour?",
       bi.CUSTOMER_SEGMENTATION,
       "See whether claim activity clusters in particular customer types.",
       bi.TIER_ANALYTICAL,
       ["How do customer segments differ on claims?",
        "Which customer segments claim most?",
        "Do older customers claim more?",
        "Which segments drive claims?"],
       [step("s1", "Claims by age band", "multi_metric_table",
             {"dimension": "age_band",
              "metrics": ["policy_count", "claim_rate", "risk_claim_rate",
                          "avg_claim_amount", "loss_ratio", "risk_loss_ratio"],
              "sort_by": "risk_claim_rate"},
             "Claim frequency and severity by life stage."),
        step("s2", "Claims by income band", "multi_metric_table",
             {"dimension": "income_band",
              "metrics": ["policy_count", "claim_rate", "risk_claim_rate", "loss_ratio"],
              "sort_by": "risk_claim_rate"},
             "Claim behaviour by income."),
        step("s3", "Risk-claim gap by age band", "compare_to_baseline",
             {"dimension": "age_band", "metric": "risk_claim_rate"},
             "Which bands genuinely deviate.")],
       ["policies", "customers", "claims"],
       ["age", "annual_income", "claim_amount", "claim_type"],
       ["claim_rate", "risk_claim_rate", "loss_ratio"],
       ["customer", "claims", "risk"],
       "leaderboard", "leaderboard", REL_CLAIM)

    ps("Which customers hold multiple policies and how do they behave?",
       bi.CUSTOMER_SEGMENTATION,
       "Test whether depth of relationship is associated with better retention.",
       bi.TIER_MULTI_STEP,
       ["Which customers hold multiple policies?",
        "Do multi-policy customers behave differently?",
        "Does holding more than one policy improve retention?",
        "How valuable are our multi-policy customers?"],
       [step("s1", "Multi-policy customers ranked by value", "entity_shortlist",
             {"base": "customer", "filters": {"policy_count": {"min": 2}},
              "score_components": [{"column": "value_score", "weight": 0.6, "direction": "high"},
                                   {"column": "policy_count", "weight": 0.4, "direction": "high"}],
              "top_n": 20,
              "columns": ["customer_id", "full_name", "policy_count", "products_held",
                          "total_annual_premium", "total_sum_assured", "lapsed_policies",
                          "surrendered_policies", "attrition_ratio"]},
             "Who they are and how much they are worth."),
        step("s2", "Portfolio baseline", "portfolio_overview", {},
             "For comparison against single-policy behaviour.")],
       ["policies", "customers"],
       ["customer_id", "policy_count", "annual_premium", "sum_assured", "policy_status"],
       ["policy_count", "avg_annual_premium"],
       ["customer", "value", "retention"],
       "shortlist", "shortlist", REL_CORE)

    ps("How do gender, marital status and occupation relate to portfolio outcomes?",
       bi.CUSTOMER_SEGMENTATION,
       "Cover the remaining demographic dimensions the dataset carries.",
       bi.TIER_ANALYTICAL,
       ["How do gender and marital status relate to outcomes?",
        "Do male and female customers behave differently?",
        "Does marital status affect lapse?",
        "Which occupations lapse most?"],
       [step("s1", "Outcomes by gender", "multi_metric_table",
             {"dimension": "gender",
              "metrics": ["policy_count", "avg_sum_assured", "avg_annual_premium",
                          "lapse_rate", "surrender_rate", "claim_rate"],
              "sort_by": "lapse_rate"},
             "Gender split on value and risk."),
        step("s2", "Outcomes by marital status", "multi_metric_table",
             {"dimension": "marital_status",
              "metrics": ["policy_count", "avg_sum_assured", "lapse_rate", "surrender_rate"],
              "sort_by": "lapse_rate", "min_n": 25},
             "Marital status split."),
        step("s3", "Lapse by occupation", "compare_to_baseline",
             {"dimension": "occupation", "metric": "lapse_rate", "min_n": 25},
             "Occupation groups that deviate from the book.")],
       ["policies", "customers"],
       ["gender", "marital_status", "occupation_id", "policy_status", "sum_assured"],
       ["lapse_rate", "surrender_rate", "avg_sum_assured"],
       ["customer", "comparison"],
       "leaderboard", "leaderboard", REL_CORE)

    ps("Are customers buying cover proportionate to their income?",
       bi.CUSTOMER_SEGMENTATION,
       "Check suitability: whether premium load and cover match customer means.",
       bi.TIER_MULTI_STEP,
       ["Are customers buying cover proportionate to their income?",
        "Is premium affordable for our customers?",
        "Are any customers over-committed on premium?",
        "How does premium-to-income vary across the book?"],
       [step("s1", "Affordability strain by band", "multi_metric_table",
             {"dimension": "premium_to_income_band",
              "metrics": ["policy_count", "policy_share", "avg_annual_premium",
                          "avg_customer_income", "lapse_rate", "surrender_rate"],
              "sort_by": "lapse_rate"},
             "Whether high premium-to-income policies lapse more."),
        step("s2", "Strain gap to baseline", "compare_to_baseline",
             {"dimension": "premium_to_income_band", "metric": "lapse_rate"},
             "Isolate the genuinely elevated bands."),
        step("s3", "Most strained policies", "entity_shortlist",
             {"base": "policy", "filters": {"policy_status": "In-Force"},
              "score_components": [{"column": "premium_to_income", "weight": 1.0,
                                    "direction": "high"}],
              "top_n": 15,
              "columns": ["policy_number", "customer_name", "product_name", "sales_channel",
                          "annual_premium", "annual_income", "premium_to_income",
                          "payment_mode", "policy_status"]},
             "Name the in-force policies carrying the highest premium load.")],
       ["policies", "customers"],
       ["annual_premium", "annual_income", "policy_status", "sum_assured"],
       ["avg_premium_to_income", "lapse_rate"],
       ["customer", "underwriting", "risk"],
       "risk_segmentation", "risk_segmentation", REL_CORE)

    ps("How do customer segments compare on retention success when contacted?",
       bi.CUSTOMER_SEGMENTATION,
       "Find which customers are actually saveable, not just which are at risk.",
       bi.TIER_MULTI_STEP,
       ["Does retention effectiveness differ by customer segment?",
        "Which customers respond to retention outreach?",
        "Are some segments easier to save than others?",
        "Which segments have the best retention success rate?"],
       [step("s1", "Retention success by income band", "multi_metric_table",
             {"dimension": "income_band",
              "metrics": ["retention_contacts", "retention_success_rate",
                          "retention_loss_to_lapse_rate"],
              "sort_by": "retention_success_rate", "ascending": False, "min_n": 20},
             "Whether saveability varies with means."),
        step("s2", "Retention success by age band", "multi_metric_table",
             {"dimension": "age_band",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False, "min_n": 20},
             "Whether saveability varies with life stage."),
        step("s3", "Retention success by sum-assured band", "multi_metric_table",
             {"dimension": "sa_band",
              "metrics": ["retention_contacts", "retention_success_rate"],
              "sort_by": "retention_success_rate", "ascending": False, "min_n": 20},
             "Whether bigger policies are easier or harder to save.")],
       ["retention", "policies", "customers"],
       ["retention_status", "annual_income", "age", "sum_assured"],
       ["retention_success_rate", "retention_contacts"],
       ["customer", "retention", "comparison"],
       "leaderboard", "leaderboard", REL_RET)


if __name__ == "__main__":  # pragma: no cover - see build_business_ps2.py
    raise SystemExit("Run build_business_ps_all.py to generate the full library.")
